/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { PipeshubError } from "./pipeshub-error.js";

/**
 * Authentication error response with details for debugging and user feedback.<br><br>
 *
 * @remarks
 * <b>Common Error Codes:</b><br>
 * <ul>
 * <li><code>INVALID_CREDENTIALS</code> - Wrong password or OTP</li>
 * <li><code>ACCOUNT_BLOCKED</code> - Account locked after 5 failed attempts</li>
 * <li><code>SESSION_EXPIRED</code> - Session token has expired</li>
 * <li><code>OTP_EXPIRED</code> - OTP code has expired (10 min validity)</li>
 * <li><code>USER_NOT_FOUND</code> - Email not registered</li>
 * <li><code>INVALID_TOKEN</code> - JWT token is invalid or malformed</li>
 * <li><code>METHOD_NOT_ALLOWED</code> - Auth method not enabled for org</li>
 * </ul>
 */
export type AuthErrorData = {
  /**
   * Error type identifier
   */
  error?: string | undefined;
  /**
   * Human-readable error message
   */
  message?: string | undefined;
  /**
   * Error code for programmatic handling
   */
  code?: string | undefined;
  /**
   * HTTP status code
   */
  statusCode?: number | undefined;
};

/**
 * Authentication error response with details for debugging and user feedback.<br><br>
 *
 * @remarks
 * <b>Common Error Codes:</b><br>
 * <ul>
 * <li><code>INVALID_CREDENTIALS</code> - Wrong password or OTP</li>
 * <li><code>ACCOUNT_BLOCKED</code> - Account locked after 5 failed attempts</li>
 * <li><code>SESSION_EXPIRED</code> - Session token has expired</li>
 * <li><code>OTP_EXPIRED</code> - OTP code has expired (10 min validity)</li>
 * <li><code>USER_NOT_FOUND</code> - Email not registered</li>
 * <li><code>INVALID_TOKEN</code> - JWT token is invalid or malformed</li>
 * <li><code>METHOD_NOT_ALLOWED</code> - Auth method not enabled for org</li>
 * </ul>
 */
export class AuthError extends PipeshubError {
  /**
   * Error type identifier
   */
  error?: string | undefined;
  /**
   * Error code for programmatic handling
   */
  code?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: AuthErrorData;

  constructor(
    err: AuthErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.code != null) this.code = err.code;

    this.name = "AuthError";
  }
}

/** @internal */
export const AuthError$inboundSchema: z.ZodMiniType<AuthError, unknown> = z
  .pipe(
    z.object({
      error: types.optional(types.string()),
      message: types.optional(types.string()),
      code: types.optional(types.string()),
      statusCode: types.optional(types.number()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new AuthError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
