/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { PipeshubCore } from "../core.js";
import { appendForm } from "../lib/encodings.js";
import {
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import { PipeshubError } from "../models/errors/pipeshub-error.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Upload Google Workspace credentials
 *
 * @remarks
 * Upload Google Workspace credentials (service account JSON for business, or OAuth tokens for individual users). File must be valid JSON.
 */
export function connectorOAuthConfigurationCreateGoogleWorkspaceCredentials(
  client: PipeshubCore,
  request: operations.CreateGoogleWorkspaceCredentialsRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    void,
    | PipeshubError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: PipeshubCore,
  request: operations.CreateGoogleWorkspaceCredentialsRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      void,
      | PipeshubError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      z.parse(
        operations.CreateGoogleWorkspaceCredentialsRequest$outboundSchema,
        value,
      ),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = new FormData();

  if (isBlobLike(payload.googleWorkspaceCredentials)) {
    appendForm(
      body,
      "googleWorkspaceCredentials",
      payload.googleWorkspaceCredentials,
    );
  } else if (isReadableStream(payload.googleWorkspaceCredentials.content)) {
    const buffer = await readableStreamToArrayBuffer(
      payload.googleWorkspaceCredentials.content,
    );
    const contentType =
      getContentTypeFromFileName(payload.googleWorkspaceCredentials.fileName)
      || "application/octet-stream";
    const blob = new Blob([buffer], { type: contentType });
    appendForm(
      body,
      "googleWorkspaceCredentials",
      blob,
      payload.googleWorkspaceCredentials.fileName,
    );
  } else {
    const contentType =
      getContentTypeFromFileName(payload.googleWorkspaceCredentials.fileName)
      || "application/octet-stream";
    appendForm(
      body,
      "googleWorkspaceCredentials",
      new Blob([payload.googleWorkspaceCredentials.content], {
        type: contentType,
      }),
      payload.googleWorkspaceCredentials.fileName,
    );
  }
  appendForm(body, "userType", payload.userType);

  const path = pathToFunc(
    "/configurationManager/connectors/googleWorkspaceCredentials",
  )();

  const headers = new Headers(compactMap({
    Accept: "*/*",
  }));

  const secConfig = await extractSecurity(client._options.bearerAuth);
  const securityInput = secConfig == null ? {} : { bearerAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "createGoogleWorkspaceCredentials",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: client._options.bearerAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "401", "403", "4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const [result] = await M.match<
    void,
    | PipeshubError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.nil(200, z.void()),
    M.fail([400, 401, 403, "4XX"]),
    M.fail("5XX"),
  )(response, req);
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
