/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Pipeshub } from "../index.js";
import { createTestHTTPClient } from "./test-client.js";

test("Connector Configuration Get Connector Config", async () => {
  const testHttpClient = createTestHTTPClient("getConnectorConfig");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.connectorConfiguration.getConnectorConfig({
    connectorId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    config: {
      scope: "team",
    },
  });
});

test("Connector Configuration Update Connector Config", async () => {
  const testHttpClient = createTestHTTPClient("updateConnectorConfig");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.connectorConfiguration.updateConnectorConfig({
    connectorId: "<id>",
    body: {
      auth: {
        values: {
          "apiKey": "sk-xxxxx",
          "baseUrl": "https://api.example.com",
        },
        oauthConfigId: "oauth_config_123",
      },
      sync: {
        scheduledConfig: {
          cronExpression: "0 */6 * * *",
          timezone: "America/New_York",
        },
        webhookConfig: {
          events: [
            "file.created",
            "file.modified",
            "file.deleted",
          ],
        },
      },
      filters: {
        sync: {
          values: {
            "fileTypes": [
              "pdf",
              "docx",
              "xlsx",
            ],
            "folders": [
              "folder_id_1",
              "folder_id_2",
            ],
            "includeShared": true,
          },
        },
      },
      baseUrl: "https://confluence.mycompany.com",
    },
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    config: {
      scope: "team",
    },
  });
});

test("Connector Configuration Update Connector Auth Config", async () => {
  const testHttpClient = createTestHTTPClient("updateConnectorAuthConfig");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.connectorConfiguration
    .updateConnectorAuthConfig({
      connectorId: "<id>",
      body: {
        auth: {
          values: {
            "apiKey": "sk-xxxxx",
            "baseUrl": "https://api.example.com",
          },
          oauthConfigId: "oauth_config_123",
        },
      },
    });
  expect(result).toBeDefined();
  expect(result).toEqual({
    config: {
      scope: "team",
    },
  });
});

test("Connector Configuration Update Connector Filters Sync Config", async () => {
  const testHttpClient = createTestHTTPClient(
    "updateConnectorFiltersSyncConfig",
  );

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.connectorConfiguration
    .updateConnectorFiltersSyncConfig({
      connectorId: "<id>",
      body: {
        sync: {
          scheduledConfig: {
            cronExpression: "0 */6 * * *",
            timezone: "America/New_York",
          },
          webhookConfig: {
            events: [
              "file.created",
              "file.modified",
              "file.deleted",
            ],
          },
        },
        filters: {
          sync: {
            values: {
              "fileTypes": [
                "pdf",
                "docx",
                "xlsx",
              ],
              "folders": [
                "folder_id_1",
                "folder_id_2",
              ],
              "includeShared": true,
            },
          },
        },
      },
    });
  expect(result).toBeDefined();
  expect(result).toEqual({
    config: {
      scope: "team",
    },
  });
});
