/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Pipeshub } from "../index.js";
import { createTestHTTPClient } from "./test-client.js";

test("Knowledge Bases Create Knowledge Base", async () => {
  const testHttpClient = createTestHTTPClient("createKnowledgeBase");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.knowledgeBases.createKnowledgeBase({
    kbName: "Product Documentation",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    name: "<value>",
  });
});

test("Knowledge Bases List Knowledge Bases", async () => {
  const testHttpClient = createTestHTTPClient("listKnowledgeBases");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.knowledgeBases.listKnowledgeBases({
    permissions: "OWNER,ORGANIZER,WRITER",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});

test("Knowledge Bases Get Knowledge Base", async () => {
  const testHttpClient = createTestHTTPClient("getKnowledgeBase");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.knowledgeBases.getKnowledgeBase({
    kbId: "kb_550e8400-e29b-41d4-a716",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    name: "<value>",
  });
});

test("Knowledge Bases Update Knowledge Base", async () => {
  const testHttpClient = createTestHTTPClient("updateKnowledgeBase");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.knowledgeBases.updateKnowledgeBase({
    kbId: "<id>",
    body: {
      kbName: "Updated Documentation Hub",
    },
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    name: "<value>",
  });
});

test("Knowledge Bases Delete Knowledge Base", async () => {
  const testHttpClient = createTestHTTPClient("deleteKnowledgeBase");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.knowledgeBases.deleteKnowledgeBase({
    kbId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    success: true,
    message: "Knowledge base deleted successfully",
  });
});

test("Knowledge Bases Get Knowledge Hub Root Nodes", async () => {
  const testHttpClient = createTestHTTPClient("getKnowledgeHubRootNodes");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.knowledgeBases.getKnowledgeHubRootNodes();
  expect(result).toBeDefined();
  expect(result).toEqual({});
});

test("Knowledge Bases Get Knowledge Hub Child Nodes", async () => {
  const testHttpClient = createTestHTTPClient("getKnowledgeHubChildNodes");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.knowledgeBases.getKnowledgeHubChildNodes({
    parentType: "<value>",
    parentId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});
