/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Pipeshub } from "../index.js";
import { createTestHTTPClient } from "./test-client.js";

test("Oauth Provider Oauth Authorize Consent", async () => {
  const testHttpClient = createTestHTTPClient("oauthAuthorizeConsent");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.oAuthProvider.oauthAuthorizeConsent({
    clientId: "<id>",
    redirectUri: "https://excellent-license.com",
    scope: "<value>",
    state: "South Dakota",
    consent: "denied",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});

test("Oauth Provider Oauth Token", async () => {
  const testHttpClient = createTestHTTPClient("oauthToken");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.oAuthProvider.oauthToken({
    grantType: "client_credentials",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    tokenType: "Bearer",
    expiresIn: 3600,
  });
});

test("Oauth Provider Oauth Introspect Active", async () => {
  const testHttpClient = createTestHTTPClient("oauthIntrospect-active");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.oAuthProvider.oauthIntrospect({
    token: "<value>",
    clientId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    active: true,
    scope: "openid profile email",
    clientId: "abc123",
    username: "user@example.com",
    tokenType: "Bearer",
    exp: 1735686000,
    iat: 1735682400,
    userId: "user-id-123",
    iss: "https://api.pipeshub.com",
  });
});

test("Oauth Provider Oauth Introspect Inactive", async () => {
  const testHttpClient = createTestHTTPClient("oauthIntrospect-inactive");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.oAuthProvider.oauthIntrospect({
    token: "<value>",
    clientId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    active: false,
  });
});
