/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Pipeshub } from "../index.js";
import { filesToStream } from "./files.js";
import { createTestHTTPClient } from "./test-client.js";

test("Organizations Check Org Exists", async () => {
  const testHttpClient = createTestHTTPClient("checkOrgExists");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.organizations.checkOrgExists();
  expect(result).toBeDefined();
  expect(result).toEqual({
    exists: true,
  });
});

test("Organizations Create Organization", async () => {
  const testHttpClient = createTestHTTPClient("createOrganization");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.organizations.createOrganization({
    accountType: "business",
    shortName: "Acme",
    registeredName: "Acme Corporation Inc.",
    contactEmail: "admin@acme.com",
    adminFullName: "John Smith",
    password: "SecurePassword123!",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    success: true,
    message: "Organization created successfully",
  });
});

test("Organizations Get Current Organization", async () => {
  const testHttpClient = createTestHTTPClient("getCurrentOrganization");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.getCurrentOrganization();
  expect(result).toBeDefined();
  expect(result).toEqual({
    domain: "excited-sand.info",
    contactEmail: "Russell_Reichel@hotmail.com",
    accountType: "individual",
    isDeleted: false,
  });
});

test("Organizations Update Organization", async () => {
  const testHttpClient = createTestHTTPClient("updateOrganization");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.updateOrganization({
    registeredName: "Acme Corporation Inc.",
    shortName: "Acme Corp",
    phoneNumber: "+15551234567",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    message: "Organization updated successfully",
  });
});

test("Organizations Delete Organization", async () => {
  const testHttpClient = createTestHTTPClient("deleteOrganization");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.deleteOrganization({
    confirm: "DELETE",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    success: true,
    message:
      "Organization and all associated data have been permanently deleted",
  });
});

test("Organizations Upload Organization Logo", async () => {
  const testHttpClient = createTestHTTPClient("uploadOrganizationLogo");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.uploadOrganizationLogo({
    logo: {
      fileName: "example.file",
      content: filesToStream(".speakeasy/testfiles/example.file"),
    },
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    success: true,
    logoUrl:
      "https://storage.pipeshub.com/org/507f1f77bcf86cd799439011/logo.png",
  });
});

test("Organizations Get Organization Logo", async () => {
  const testHttpClient = createTestHTTPClient("getOrganizationLogo");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.getOrganizationLogo();
  expect(result).toBeDefined();
  expect(result).toEqual({
    success: true,
    hasLogo: true,
    logoUrl:
      "https://storage.pipeshub.com/org/507f1f77bcf86cd799439011/logo.png?token=...",
  });
});

test("Organizations Delete Organization Logo", async () => {
  const testHttpClient = createTestHTTPClient("deleteOrganizationLogo");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.deleteOrganizationLogo();
  expect(result).toBeDefined();
  expect(result).toEqual({
    success: true,
    message: "Organization logo deleted successfully",
  });
});

test("Organizations Get Onboarding Status", async () => {
  const testHttpClient = createTestHTTPClient("getOnboardingStatus");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.getOnboardingStatus();
  expect(result).toBeDefined();
  expect(result).toEqual({});
});

test("Organizations Update Onboarding Status", async () => {
  const testHttpClient = createTestHTTPClient("updateOnboardingStatus");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.organizations.updateOnboardingStatus({
    stepId: "invite_team",
    action: "complete",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    success: true,
    message: "Step 'invite_team' marked as complete",
    isOnboardingComplete: false,
    nextStep: "connect_integrations",
  });
});
