/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Pipeshub } from "../index.js";
import { createTestHTTPClient } from "./test-client.js";

test("Permissions Create Kb Permission", async () => {
  const testHttpClient = createTestHTTPClient("createKBPermission");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.permissions.createKBPermission({
    kbId: "<id>",
    body: {
      role: "OWNER",
    },
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});

test("Permissions List Kb Permissions", async () => {
  const testHttpClient = createTestHTTPClient("listKBPermissions");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.permissions.listKBPermissions({
    kbId: "<id>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});
