/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Pipeshub } from "../index.js";
import { createTestHTTPClient } from "./test-client.js";

test("User Account Init Auth", async () => {
  const testHttpClient = createTestHTTPClient("initAuth");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.userAccount.initAuth({
    email: "user@example.com",
  });
  expect(result).toBeDefined();
  expect(result!.result).toBeDefined();
  expect(result!.result).toEqual({
    currentStep: 0,
    allowedMethods: [
      "password",
      "google",
      "otp",
    ],
    message: "Authentication initialized",
  });
});

test("User Account Authenticate", async () => {
  const testHttpClient = createTestHTTPClient("authenticate");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.userAccount.authenticate({
    xSessionToken: "<value>",
    body: {
      method: "oauth",
      credentials: {
        password: "o_5N_tt72qMx3WV",
      },
    },
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    message: "Fully authenticated",
  });
});

test("User Account Generate Login Otp", async () => {
  const testHttpClient = createTestHTTPClient("generateLoginOtp");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.userAccount.generateLoginOtp({
    email: "Garland.Sipes42@hotmail.com",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    message: "OTP sent to your email",
  });
});

test("User Account Forgot Password", async () => {
  const testHttpClient = createTestHTTPClient("forgotPassword");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.userAccount.forgotPassword({
    email: "Barton.Gutkowski68@yahoo.com",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    message: "Password reset email sent",
  });
});

test("User Account Reset Password With Token", async () => {
  const testHttpClient = createTestHTTPClient("resetPasswordWithToken");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.userAccount.resetPasswordWithToken({
    scopedToken: "<YOUR_BEARER_TOKEN_HERE>",
  }, {
    password: "H9GEHoL829GXj06",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({
    data: "password reset",
  });
});

test("User Account Refresh Token", async () => {
  const testHttpClient = createTestHTTPClient("refreshToken");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
  });

  const result = await pipeshub.userAccount.refreshToken({
    scopedToken: "<YOUR_BEARER_TOKEN_HERE>",
  });
  expect(result).toBeDefined();
  expect(result).toEqual({});
});

test("User Account Logout", async () => {
  const testHttpClient = createTestHTTPClient("logout");

  const pipeshub = new Pipeshub({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    security: {
      bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
    },
  });

  const result = await pipeshub.userAccount.logout();
  expect(result).toBeDefined();
  expect(result).toEqual({
    message: "Logged out successfully",
  });
});
