/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentTemplatesCreate } from "../funcs/agent-templates-create.js";
import { agentTemplatesDelete } from "../funcs/agent-templates-delete.js";
import { agentTemplatesGet } from "../funcs/agent-templates-get.js";
import { agentTemplatesList } from "../funcs/agent-templates-list.js";
import { agentTemplatesUpdate } from "../funcs/agent-templates-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AgentTemplates extends ClientSDK {
  /**
   * List agent templates
   *
   * @remarks
   * Retrieve all available agent templates.<br><br>
   * <b>Overview:</b><br>
   * Agent templates provide pre-configured starting points for creating
   * custom AI agents. Templates include system prompts, recommended tools,
   * and configuration schemas.<br><br>
   * <b>Template Types:</b><br>
   * <ul>
   * <li>Public templates available to all organization users</li>
   * <li>Private templates created by individual users</li>
   * </ul>
   */
  async list(
    options?: RequestOptions,
  ): Promise<Array<models.AgentTemplate>> {
    return unwrapAsync(agentTemplatesList(
      this,
      options,
    ));
  }

  /**
   * Create agent template
   *
   * @remarks
   * Create a new reusable agent template.<br><br>
   * <b>Overview:</b><br>
   * Templates define the base configuration for agents including
   * system prompts, tool recommendations, and customization options.<br><br>
   * <b>Template Components:</b><br>
   * <ul>
   * <li><b>System prompt:</b> Default instructions for agents</li>
   * <li><b>Recommended tools:</b> Suggested tool integrations</li>
   * <li><b>Config schema:</b> JSON Schema for customization options</li>
   * </ul>
   */
  async create(
    request: operations.CreateAgentTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.AgentTemplate> {
    return unwrapAsync(agentTemplatesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get agent template
   *
   * @remarks
   * Retrieve a specific agent template by ID.
   */
  async get(
    request: operations.GetAgentTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.AgentTemplate> {
    return unwrapAsync(agentTemplatesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update agent template
   *
   * @remarks
   * Update an existing agent template.<br><br>
   * <b>Permissions:</b><br>
   * Only the template creator can update it.
   */
  async update(
    request: operations.UpdateAgentTemplateRequest,
    options?: RequestOptions,
  ): Promise<models.AgentTemplate> {
    return unwrapAsync(agentTemplatesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete agent template
   *
   * @remarks
   * Delete an agent template.<br><br>
   * <b>Note:</b><br>
   * Existing agents created from this template are not affected.
   */
  async delete(
    request: operations.DeleteAgentTemplateRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(agentTemplatesDelete(
      this,
      request,
      options,
    ));
  }
}
