/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorInstancesCreate } from "../funcs/connector-instances-create.js";
import { connectorInstancesDelete } from "../funcs/connector-instances-delete.js";
import { connectorInstancesGetActiveAgents } from "../funcs/connector-instances-get-active-agents.js";
import { connectorInstancesGet } from "../funcs/connector-instances-get.js";
import { connectorInstancesListActive } from "../funcs/connector-instances-list-active.js";
import { connectorInstancesListConfigured } from "../funcs/connector-instances-list-configured.js";
import { connectorInstancesListInactive } from "../funcs/connector-instances-list-inactive.js";
import { connectorInstancesList } from "../funcs/connector-instances-list.js";
import { connectorInstancesUpdateName } from "../funcs/connector-instances-update-name.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ConnectorInstances extends ClientSDK {
  /**
   * List connector instances
   *
   * @remarks
   * Get all configured connector instances for your organization.<br><br>
   * <b>Overview:</b><br>
   * Returns instances created by users, filtered by scope and permissions.
   * Team-scope connectors are visible to all org users. Personal connectors
   * are only visible to their creators.<br><br>
   * <b>Instance States:</b><br>
   * <ul>
   * <li><b>isConfigured:</b> All required settings are complete</li>
   * <li><b>isAuthenticated:</b> OAuth flow complete or credentials valid</li>
   * <li><b>isActive:</b> Connector is enabled for sync/agent</li>
   * </ul>
   */
  async list(
    request?: operations.ListConnectorInstancesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListConnectorInstancesResponse> {
    return unwrapAsync(connectorInstancesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create connector instance
   *
   * @remarks
   * Create a new connector instance from a registry type.<br><br>
   * <b>Overview:</b><br>
   * Creates a new connector instance that can then be configured and enabled.
   * The instance is created in an unconfigured state and needs authentication
   * and filter setup before it can be activated.<br><br>
   * <b>Scope Permissions:</b><br>
   * <ul>
   * <li><code>team</code> scope requires admin privileges</li>
   * <li><code>personal</code> scope available to all users</li>
   * </ul>
   * <b>Next Steps After Creation:</b><br>
   * <ol>
   * <li>Configure authentication via <code>PUT /{id}/config/auth</code></li>
   * <li>Complete OAuth flow if needed via <code>GET /{id}/oauth/authorize</code></li>
   * <li>Set up filters via <code>POST /{id}/filters</code></li>
   * <li>Enable connector via <code>POST /{id}/toggle</code></li>
   * </ol>
   */
  async create(
    request: models.CreateConnectorRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateConnectorInstanceResponse> {
    return unwrapAsync(connectorInstancesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List active connector instances
   *
   * @remarks
   * Get all active (enabled) connector instances.<br><br>
   * <b>Overview:</b><br>
   * Returns only instances where <code>isActive: true</code>.
   * These are connectors currently syncing data or available to AI agents.
   */
  async listActive(
    options?: RequestOptions,
  ): Promise<operations.ListActiveConnectorsResponse> {
    return unwrapAsync(connectorInstancesListActive(
      this,
      options,
    ));
  }

  /**
   * List inactive connector instances
   *
   * @remarks
   * Get all inactive (disabled) connector instances.
   */
  async listInactive(
    options?: RequestOptions,
  ): Promise<operations.ListInactiveConnectorsResponse> {
    return unwrapAsync(connectorInstancesListInactive(
      this,
      options,
    ));
  }

  /**
   * List configured connector instances
   *
   * @remarks
   * Get all connector instances that have completed configuration.<br><br>
   * <b>Overview:</b><br>
   * Returns instances where <code>isConfigured: true</code>.
   * These have all required settings but may not be active yet.
   */
  async listConfigured(
    request?: operations.ListConfiguredConnectorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListConfiguredConnectorsResponse> {
    return unwrapAsync(connectorInstancesListConfigured(
      this,
      request,
      options,
    ));
  }

  /**
   * List active agent connectors
   *
   * @remarks
   * Get connector instances enabled for AI agent integration.<br><br>
   * <b>Overview:</b><br>
   * Returns connectors where <code>agentEnabled: true</code>.
   * These are available to AI agents for querying and actions.
   */
  async getActiveAgents(
    request?: operations.ListActiveAgentConnectorsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListActiveAgentConnectorsResponse> {
    return unwrapAsync(connectorInstancesGetActiveAgents(
      this,
      request,
      options,
    ));
  }

  /**
   * Get connector instance
   *
   * @remarks
   * Retrieve a specific connector instance by ID.
   */
  async get(
    request: operations.GetConnectorInstanceRequest,
    options?: RequestOptions,
  ): Promise<operations.GetConnectorInstanceResponse> {
    return unwrapAsync(connectorInstancesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete connector instance
   *
   * @remarks
   * Delete a connector instance and all associated data.<br><br>
   * <b>Warning:</b><br>
   * This permanently removes the connector configuration.
   * Synced records in knowledge bases are NOT deleted.<br><br>
   * <b>Permissions:</b><br>
   * <ul>
   * <li>Team scope: Requires admin</li>
   * <li>Personal scope: Only creator can delete</li>
   * </ul>
   */
  async delete(
    request: operations.DeleteConnectorInstanceRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteConnectorInstanceResponse> {
    return unwrapAsync(connectorInstancesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update connector instance name
   *
   * @remarks
   * Update the display name of a connector instance.<br><br>
   * <b>Note:</b> This only updates the display name, not the connector configuration.
   */
  async updateName(
    request: operations.UpdateConnectorNameRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateConnectorNameResponse> {
    return unwrapAsync(connectorInstancesUpdateName(
      this,
      request,
      options,
    ));
  }
}
