/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorOAuthConfigurationsConfigureOneDrive } from "../funcs/connector-o-auth-configurations-configure-one-drive.js";
import { connectorOAuthConfigurationsSetGoogleWorkspaceOauth } from "../funcs/connector-o-auth-configurations-set-google-workspace-oauth.js";
import { connectorOAuthConfigurationsSetSharePointConfig } from "../funcs/connector-o-auth-configurations-set-share-point-config.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ConnectorOAuthConfigurations extends ClientSDK {
  /**
   * Configure Google Workspace OAuth
   *
   * @remarks
   * Set up OAuth credentials for Google Workspace connector. Required for user authentication with Google Drive, Gmail, etc.
   */
  async setGoogleWorkspaceOauth(
    request: models.GoogleWorkspaceOAuthConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(connectorOAuthConfigurationsSetGoogleWorkspaceOauth(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure OneDrive connector
   *
   * @remarks
   * Set up Microsoft credentials for OneDrive connector.
   */
  async configureOneDrive(
    request: models.OneDriveConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(connectorOAuthConfigurationsConfigureOneDrive(
      this,
      request,
      options,
    ));
  }

  /**
   * Configure SharePoint connector
   *
   * @remarks
   * Set up Microsoft credentials for SharePoint connector.
   */
  async setSharePointConfig(
    request: models.SharePointConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(connectorOAuthConfigurationsSetSharePointConfig(
      this,
      request,
      options,
    ));
  }
}
