/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectorConfigurationGetConnectorConfig } from "../funcs/connector-configuration-get-connector-config.js";
import { connectorConfigurationUpdateConnectorAuthConfig } from "../funcs/connector-configuration-update-connector-auth-config.js";
import { connectorConfigurationUpdateConnectorConfig } from "../funcs/connector-configuration-update-connector-config.js";
import { connectorConfigurationUpdateConnectorFiltersSyncConfig } from "../funcs/connector-configuration-update-connector-filters-sync-config.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ConnectorConfiguration extends ClientSDK {
  /**
   * Get connector configuration
   *
   * @remarks
   * Get the current configuration for a connector instance.<br><br>
   * <b>Security:</b><br>
   * Sensitive data (credentials, OAuth tokens) are redacted from the response.
   * Only admins can see partial credential information.
   */
  async getConnectorConfig(
    request: operations.GetConnectorConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.GetConnectorConfigResponse> {
    return unwrapAsync(connectorConfigurationGetConnectorConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * Update connector configuration
   *
   * @remarks
   * Update authentication, sync, and filter configuration.<br><br>
   * <b>Prerequisites:</b><br>
   * Connector must be <b>disabled</b> before updating configuration.
   * Disable it first using <code>POST /{id}/toggle</code>.<br><br>
   * <b>Partial Updates:</b><br>
   * Only provide the sections you want to update. Omitted sections
   * are not modified.
   */
  async updateConnectorConfig(
    request: operations.UpdateConnectorConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateConnectorConfigResponse> {
    return unwrapAsync(connectorConfigurationUpdateConnectorConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * Update authentication configuration
   *
   * @remarks
   * Update only the authentication configuration.<br><br>
   * <b>Use Case:</b><br>
   * Use this when you need to update credentials without changing
   * sync or filter settings. Useful for credential rotation.<br><br>
   * <b>Prerequisites:</b><br>
   * Connector must be disabled. This endpoint clears OAuth state,
   * requiring re-authentication for OAuth connectors.
   */
  async updateConnectorAuthConfig(
    request: operations.UpdateConnectorAuthConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateConnectorAuthConfigResponse> {
    return unwrapAsync(connectorConfigurationUpdateConnectorAuthConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * Update filters and sync configuration
   *
   * @remarks
   * Update filter selections and sync settings without touching auth.<br><br>
   * <b>Use Case:</b><br>
   * Use this to change what data is synced or adjust sync schedule
   * without re-authenticating.
   */
  async updateConnectorFiltersSyncConfig(
    request: operations.UpdateConnectorFiltersSyncConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateConnectorFiltersSyncConfigResponse> {
    return unwrapAsync(connectorConfigurationUpdateConnectorFiltersSyncConfig(
      this,
      request,
      options,
    ));
  }
}
