/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeBasesCreate } from "../funcs/knowledge-bases-create.js";
import { knowledgeBasesDelete } from "../funcs/knowledge-bases-delete.js";
import { knowledgeBasesGetHubChildNodes } from "../funcs/knowledge-bases-get-hub-child-nodes.js";
import { knowledgeBasesGetRootNodes } from "../funcs/knowledge-bases-get-root-nodes.js";
import { knowledgeBasesGet } from "../funcs/knowledge-bases-get.js";
import { knowledgeBasesList } from "../funcs/knowledge-bases-list.js";
import { knowledgeBasesUpdate } from "../funcs/knowledge-bases-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class KnowledgeBases extends ClientSDK {
  /**
   * Create a new knowledge base
   *
   * @remarks
   * Create a new knowledge base for organizing and managing documents within your organization.<br><br>
   * <b>Overview:</b><br>
   * A knowledge base is a container for organizing related documents, files, and content. It provides a central location for teams to collaborate on shared information.<br><br>
   * <b>Features:</b><br>
   * <ul>
   * <li>Hierarchical folder structure support</li>
   * <li>Role-based access control (OWNER, ORGANIZER, WRITER, READER, etc.)</li>
   * <li>Full-text search across all records</li>
   * <li>Integration with external connectors (Google Drive, OneDrive, etc.)</li>
   * <li>Automatic content indexing for AI-powered search</li>
   * </ul>
   * <b>Naming Rules:</b><br>
   * <ul>
   * <li>Name must be 1-255 characters</li>
   * <li>Special characters and HTML tags are sanitized</li>
   * <li>Names don't need to be unique within organization</li>
   * </ul>
   * <b>Creator Permissions:</b><br>
   * The user creating the KB automatically becomes the OWNER with full administrative rights.
   */
  async create(
    request: operations.CreateKnowledgeBaseRequest,
    options?: RequestOptions,
  ): Promise<models.KnowledgeBase> {
    return unwrapAsync(knowledgeBasesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List all knowledge bases
   *
   * @remarks
   * Retrieve a paginated list of all knowledge bases accessible to the authenticated user.<br><br>
   * <b>Overview:</b><br>
   * Returns knowledge bases where the user has at least READER permission. Results include the user's role for each KB.<br><br>
   * <b>Filtering:</b><br>
   * <ul>
   * <li><b>search:</b> Full-text search on KB names (max 1000 chars)</li>
   * <li><b>permissions:</b> Filter by user's role (comma-separated: OWNER,WRITER,READER)</li>
   * </ul>
   * <b>Sorting Options:</b><br>
   * <ul>
   * <li><code>name</code> - Alphabetical by KB name</li>
   * <li><code>createdAtTimestamp</code> - By creation date</li>
   * <li><code>updatedAtTimestamp</code> - By last modification</li>
   * <li><code>userRole</code> - By permission level</li>
   * </ul>
   * <b>Performance:</b><br>
   * Uses efficient pagination with limit/offset. For large result sets, use smaller page sizes.
   */
  async list(
    request?: operations.ListKnowledgeBasesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListKnowledgeBasesResponse> {
    return unwrapAsync(knowledgeBasesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get knowledge base by ID
   *
   * @remarks
   * Retrieve detailed information about a specific knowledge base.<br><br>
   * <b>Overview:</b><br>
   * Returns complete KB metadata including name, timestamps, and the requesting user's role/permissions.<br><br>
   * <b>Access Control:</b><br>
   * User must have at least READER permission to view KB details.
   */
  async get(
    request: operations.GetKnowledgeBaseRequest,
    options?: RequestOptions,
  ): Promise<models.KnowledgeBase> {
    return unwrapAsync(knowledgeBasesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update knowledge base
   *
   * @remarks
   * Update a knowledge base's name.<br><br>
   * <b>Required Permission:</b> OWNER or ORGANIZER<br><br>
   * <b>Validation:</b><br>
   * <ul>
   * <li>Name must be 1-255 characters</li>
   * <li>XSS protection applied to input</li>
   * </ul>
   */
  async update(
    request: operations.UpdateKnowledgeBaseRequest,
    options?: RequestOptions,
  ): Promise<models.KnowledgeBase> {
    return unwrapAsync(knowledgeBasesUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete knowledge base
   *
   * @remarks
   * Permanently delete a knowledge base and all its contents.<br><br>
   * <b>Required Permission:</b> OWNER only<br><br>
   * <b>What Gets Deleted:</b><br>
   * <ul>
   * <li>All folders within the KB</li>
   * <li>All records and their indexed content</li>
   * <li>All permission grants</li>
   * <li>Associated storage files</li>
   * </ul>
   * <b>Warning:</b> This action is irreversible. Consider exporting data before deletion.
   */
  async delete(
    request: operations.DeleteKnowledgeBaseRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteKnowledgeBaseResponse> {
    return unwrapAsync(knowledgeBasesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get knowledge hub root nodes
   *
   * @remarks
   * Retrieve root-level nodes for unified knowledge hub browsing.<br><br>
   * <b>Overview:</b><br>
   * Provides a unified view across all knowledge sources - KBs, connectors, and apps. Use for building file browser UIs.<br><br>
   * <b>Node Types:</b><br>
   * <ul>
   * <li><b>KB:</b> Knowledge bases</li>
   * <li><b>CONNECTOR:</b> External connector instances</li>
   * <li><b>APP:</b> Connected applications</li>
   * </ul>
   */
  async getRootNodes(
    request?: operations.GetKnowledgeHubRootNodesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetKnowledgeHubRootNodesResponse> {
    return unwrapAsync(knowledgeBasesGetRootNodes(
      this,
      request,
      options,
    ));
  }

  /**
   * Get knowledge hub child nodes
   *
   * @remarks
   * Retrieve child nodes under a specific parent in the knowledge hub tree.<br><br>
   * <b>Navigation:</b><br>
   * Use this to drill down into KBs, folders, and connector hierarchies.
   */
  async getHubChildNodes(
    request: operations.GetKnowledgeHubChildNodesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetKnowledgeHubChildNodesResponse> {
    return unwrapAsync(knowledgeBasesGetHubChildNodes(
      this,
      request,
      options,
    ));
  }
}
