/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oAuthConfigurationCreate } from "../funcs/o-auth-configuration-create.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class OAuthConfiguration2 extends ClientSDK {
  /**
   * Create OAuth configuration
   *
   * @remarks
   * Create a new OAuth configuration for a connector type.<br><br>
   * <b>Admin Only:</b><br>
   * Only admins can create OAuth configurations. These provide the
   * OAuth credentials needed for users to authenticate connectors.<br><br>
   * <b>Use Case:</b><br>
   * Before users can create Google Drive connectors with OAuth,
   * an admin must create an OAuth configuration with the Google
   * OAuth client ID and secret.
   */
  async create(
    request: operations.CreateOAuthConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateOAuthConfigResponse> {
    return unwrapAsync(oAuthConfigurationCreate(
      this,
      request,
      options,
    ));
  }
}
