/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oauthAppsActivate } from "../funcs/oauth-apps-activate.js";
import { oauthAppsCreate } from "../funcs/oauth-apps-create.js";
import { oauthAppsDelete } from "../funcs/oauth-apps-delete.js";
import { oauthAppsGet } from "../funcs/oauth-apps-get.js";
import { oauthAppsListScopes } from "../funcs/oauth-apps-list-scopes.js";
import { oauthAppsListTokens } from "../funcs/oauth-apps-list-tokens.js";
import { oauthAppsList } from "../funcs/oauth-apps-list.js";
import { oauthAppsRegenerateSecret } from "../funcs/oauth-apps-regenerate-secret.js";
import { oauthAppsRevokeAllTokens } from "../funcs/oauth-apps-revoke-all-tokens.js";
import { oauthAppsSuspend } from "../funcs/oauth-apps-suspend.js";
import { oauthAppsUpdate } from "../funcs/oauth-apps-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class OauthApps extends ClientSDK {
  /**
   * List OAuth apps
   *
   * @remarks
   * List all OAuth apps registered for the organization.
   * <br><br>
   * Returns a paginated list of apps with their configuration (excluding secrets).
   * <br><br>
   * <b>Filters:</b><br>
   * - `status` - Filter by app status (active, suspended, revoked)<br>
   * - `search` - Search by app name
   */
  async list(
    request?: operations.ListOAuthAppsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.OAuthAppListResponse> {
    return unwrapAsync(oauthAppsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create OAuth app
   *
   * @remarks
   * Create a new OAuth app for the organization.
   * <br><br>
   * <b>Important:</b> The client secret is only returned once during creation.
   * Store it securely - it cannot be retrieved later. If lost, you'll need to
   * regenerate it.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   * <br><br>
   * <b>Rate Limited:</b> 10 requests per minute.
   */
  async create(
    request: models.CreateOAuthAppRequest,
    options?: RequestOptions,
  ): Promise<models.OAuthAppWithSecret> {
    return unwrapAsync(oauthAppsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List available scopes
   *
   * @remarks
   * List all available OAuth scopes that can be requested by apps.
   * <br><br>
   * Returns scope names, descriptions, and categories for display
   * in app configuration UI.
   */
  async listScopes(
    options?: RequestOptions,
  ): Promise<Array<models.OAuthScopeInfo>> {
    return unwrapAsync(oauthAppsListScopes(
      this,
      options,
    ));
  }

  /**
   * Get OAuth app details
   *
   * @remarks
   * Get details of a specific OAuth app.
   * <br><br>
   * Returns app configuration without the client secret.
   */
  async get(
    request: operations.GetOAuthAppRequest,
    options?: RequestOptions,
  ): Promise<models.OAuthAppResponse> {
    return unwrapAsync(oauthAppsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update OAuth app
   *
   * @remarks
   * Update an OAuth app's configuration.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   * <br><br>
   * <b>Rate Limited:</b> 10 requests per minute.
   * <br><br>
   * <b>Note:</b> To regenerate the client secret, use the
   * `/oauth-clients/{appId}/regenerate-secret` endpoint.
   */
  async update(
    request: operations.UpdateOAuthAppRequest,
    options?: RequestOptions,
  ): Promise<models.OAuthAppResponse> {
    return unwrapAsync(oauthAppsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete OAuth app
   *
   * @remarks
   * Delete (soft delete) an OAuth app.
   * <br><br>
   * This marks the app as deleted and revokes all its tokens.
   * The app cannot be restored after deletion.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   * <br><br>
   * <b>Rate Limited:</b> 10 requests per minute.
   */
  async delete(
    request: operations.DeleteOAuthAppRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteOAuthAppResponse> {
    return unwrapAsync(oauthAppsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Regenerate client secret
   *
   * @remarks
   * Regenerate the client secret for an OAuth app.
   * <br><br>
   * The old secret is immediately invalidated. Any clients using the old
   * secret will fail to authenticate until updated with the new secret.
   * <br><br>
   * <b>Important:</b> The new secret is only returned once. Store it securely.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   * <br><br>
   * <b>Rate Limited:</b> 10 requests per minute.
   */
  async regenerateSecret(
    request: operations.RegenerateOAuthAppSecretRequest,
    options?: RequestOptions,
  ): Promise<models.OAuthAppWithSecret> {
    return unwrapAsync(oauthAppsRegenerateSecret(
      this,
      request,
      options,
    ));
  }

  /**
   * Suspend OAuth app
   *
   * @remarks
   * Suspend an OAuth app, preventing it from authenticating or issuing tokens.
   * <br><br>
   * Existing tokens remain valid until they expire, but no new tokens can
   * be obtained. Use this for temporary access suspension.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   * <br><br>
   * <b>Rate Limited:</b> 10 requests per minute.
   */
  async suspend(
    request: operations.SuspendOAuthAppRequest,
    options?: RequestOptions,
  ): Promise<models.OAuthAppResponse> {
    return unwrapAsync(oauthAppsSuspend(
      this,
      request,
      options,
    ));
  }

  /**
   * Activate suspended OAuth app
   *
   * @remarks
   * Reactivate a suspended OAuth app, allowing it to authenticate and issue tokens again.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   * <br><br>
   * <b>Rate Limited:</b> 10 requests per minute.
   */
  async activate(
    request: operations.ActivateOAuthAppRequest,
    options?: RequestOptions,
  ): Promise<models.OAuthAppResponse> {
    return unwrapAsync(oauthAppsActivate(
      this,
      request,
      options,
    ));
  }

  /**
   * List app tokens
   *
   * @remarks
   * List all active tokens issued to an OAuth app.
   * <br><br>
   * Useful for monitoring app usage and identifying tokens to revoke.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   */
  async listTokens(
    request: operations.ListOAuthAppTokensRequest,
    options?: RequestOptions,
  ): Promise<Array<models.OAuthTokenListItem>> {
    return unwrapAsync(oauthAppsListTokens(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke all app tokens
   *
   * @remarks
   * Revoke all tokens (access and refresh) issued to an OAuth app.
   * <br><br>
   * Use this for emergency access removal or when rotating credentials.
   * <br><br>
   * <b>Admin Only:</b> Requires admin privileges.
   * <br><br>
   * <b>Rate Limited:</b> 10 requests per minute.
   */
  async revokeAllTokens(
    request: operations.RevokeAllOAuthAppTokensRequest,
    options?: RequestOptions,
  ): Promise<operations.RevokeAllOAuthAppTokensResponse> {
    return unwrapAsync(oauthAppsRevokeAllTokens(
      this,
      request,
      options,
    ));
  }
}
