/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationAuthConfigsCreate } from "../funcs/organization-auth-configs-create.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class OrganizationAuthConfigs extends ClientSDK {
  /**
   * Create organization authentication configuration
   *
   * @remarks
   * Create initial organization authentication configuration during onboarding.
   * This endpoint creates a new organization with admin user and default auth settings.
   * <br><br>
   * <b>Note:</b> This is typically called during the initial setup process.
   */
  async create(
    request: models.OrgAuthConfigCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateOrgAuthConfigResponse> {
    return unwrapAsync(organizationAuthConfigsCreate(
      this,
      request,
      options,
    ));
  }
}
