/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { organizationAuthConfigurationUpdateMethod } from "../funcs/organization-auth-configuration-update-method.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class OrganizationAuthConfiguration extends ClientSDK {
  /**
   * Update organization authentication methods
   *
   * @remarks
   * Update the authentication methods configuration for an organization.
   * This allows admins to configure single or multi-factor authentication.
   * <br><br>
   * <b>Validation Rules:</b><br>
   * - Minimum 1 step, maximum 3 steps<br>
   * - Each step must have a unique order (1, 2, or 3)<br>
   * - No duplicate methods within the same step<br>
   * - No method can appear in multiple steps<br>
   * - Each step must have at least one allowed method
   * <br><br>
   * <b>Available Methods:</b><br>
   * - <code>password</code>: Email/password authentication<br>
   * - <code>otp</code>: One-time password via email<br>
   * - <code>google</code>: Google OAuth 2.0<br>
   * - <code>microsoft</code>: Microsoft OAuth 2.0<br>
   * - <code>azureAd</code>: Azure Active Directory<br>
   * - <code>samlSso</code>: SAML 2.0 Single Sign-On<br>
   * - <code>oauth</code>: Generic OAuth 2.0 provider
   * <br><br>
   * <b>Example - Single Factor (Password or Google):</b><br>
   * <pre>
   * {
   *   "authMethods": [
   *     { "order": 1, "allowedMethods": [{ "type": "password" }, { "type": "google" }] }
   *   ]
   * }
   * </pre>
   * <br>
   * <b>Example - Two Factor (Password + OTP):</b><br>
   * <pre>
   * {
   *   "authMethods": [
   *     { "order": 1, "allowedMethods": [{ "type": "password" }] },
   *     { "order": 2, "allowedMethods": [{ "type": "otp" }] }
   *   ]
   * }
   * </pre>
   * <br>
   * <b>Admin Access Required:</b> Only organization admins can update auth configuration.
   */
  async updateMethod(
    request: models.AuthConfig,
    options?: RequestOptions,
  ): Promise<operations.UpdateAuthMethodResponse> {
    return unwrapAsync(organizationAuthConfigurationUpdateMethod(
      this,
      request,
      options,
    ));
  }
}
