/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { platformSettingsGetAvailableFeatureFlags } from "../funcs/platform-settings-get-available-feature-flags.js";
import { platformSettingsGetCustomSystemPrompt } from "../funcs/platform-settings-get-custom-system-prompt.js";
import { platformSettingsGetPlatformSettings } from "../funcs/platform-settings-get-platform-settings.js";
import { platformSettingsSetCustomSystemPrompt } from "../funcs/platform-settings-set-custom-system-prompt.js";
import { platformSettingsSetPlatformSettings } from "../funcs/platform-settings-set-platform-settings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PlatformSettings extends ClientSDK {
  /**
   * Update platform settings
   *
   * @remarks
   * Configure platform-wide settings including file upload limits and feature flags.
   *
   * **File Upload Limits:**
   * - Default: 30MB (31457280 bytes)
   * - Maximum: 1GB (1073741824 bytes)
   *
   * **Available Feature Flags:**
   * - ENABLE_BETA_CONNECTORS: Enable beta connector integrations (default: false)
   */
  async setPlatformSettings(
    request: operations.SetPlatformSettingsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(platformSettingsSetPlatformSettings(
      this,
      request,
      options,
    ));
  }

  /**
   * Get platform settings
   *
   * @remarks
   * Retrieve current platform settings including file upload limits and feature flag states.
   */
  async getPlatformSettings(
    options?: RequestOptions,
  ): Promise<models.PlatformSettings> {
    return unwrapAsync(platformSettingsGetPlatformSettings(
      this,
      options,
    ));
  }

  /**
   * Get available feature flags
   *
   * @remarks
   * List all available feature flags with their descriptions and default values.
   */
  async getAvailableFeatureFlags(
    options?: RequestOptions,
  ): Promise<operations.GetAvailableFeatureFlagsResponse> {
    return unwrapAsync(platformSettingsGetAvailableFeatureFlags(
      this,
      options,
    ));
  }

  /**
   * Update custom system prompt
   *
   * @remarks
   * Set a custom system prompt that will be used by AI models.
   */
  async setCustomSystemPrompt(
    request: models.CustomSystemPrompt,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(platformSettingsSetCustomSystemPrompt(
      this,
      request,
      options,
    ));
  }

  /**
   * Get custom system prompt
   *
   * @remarks
   * Get custom system prompt.
   */
  async getCustomSystemPrompt(
    options?: RequestOptions,
  ): Promise<models.CustomSystemPrompt> {
    return unwrapAsync(platformSettingsGetCustomSystemPrompt(
      this,
      options,
    ));
  }
}
