/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { AgentConversations } from "./agent-conversations.js";
import { AgentTemplates } from "./agent-templates.js";
import { Agents } from "./agents.js";
import { AiModelsConfiguration } from "./ai-models-configuration.js";
import { AiModelsProviders } from "./ai-models-providers.js";
import { AuthConfig } from "./auth-config.js";
import { AuthenticationConfiguration } from "./authentication-configuration.js";
import { AuthenticationConfigurations } from "./authentication-configurations.js";
import { ConnectorConfiguration } from "./connector-configuration.js";
import { ConnectorConfigurations } from "./connector-configurations.js";
import { ConnectorControl } from "./connector-control.js";
import { ConnectorFilters } from "./connector-filters.js";
import { ConnectorInstances } from "./connector-instances.js";
import { ConnectorOAuthConfiguration1 } from "./connector-o-auth-configuration-1.js";
import { ConnectorOAuthConfigurations } from "./connector-o-auth-configurations.js";
import { ConnectorOAuth } from "./connector-o-auth.js";
import { ConnectorOauthConfiguration2 } from "./connector-oauth-configuration-2.js";
import { ConnectorRegistry } from "./connector-registry.js";
import { ConnectorService } from "./connector-service.js";
import { ConnectorServices } from "./connector-services.js";
import { Connector } from "./connector.js";
import { Conversations } from "./conversations.js";
import { CrawlingJobs } from "./crawling-jobs.js";
import { DoclingService } from "./docling-service.js";
import { DocumentBuffer } from "./document-buffer.js";
import { DocumentManagement } from "./document-management.js";
import { DocumentUpload } from "./document-upload.js";
import { EmailOperations } from "./email-operations.js";
import { Folders } from "./folders.js";
import { IndexingService } from "./indexing-service.js";
import { KnowledgeBases } from "./knowledge-bases.js";
import { MailConfiguration } from "./mail-configuration.js";
import { MetricsCollection } from "./metrics-collection.js";
import { MetricsCollections } from "./metrics-collections.js";
import { OAuthConfiguration2 } from "./o-auth-configuration-2.js";
import { OauthApps } from "./oauth-apps.js";
import { OauthConfiguration1 } from "./oauth-configuration-1.js";
import { OauthConfigurations } from "./oauth-configurations.js";
import { OauthProvider } from "./oauth-provider.js";
import { Oauth } from "./oauth.js";
import { OpenIDConnect } from "./open-id-connect.js";
import { OrganizationAuthConfig } from "./organization-auth-config.js";
import { OrganizationAuthConfigs } from "./organization-auth-configs.js";
import { OrganizationAuthConfiguration } from "./organization-auth-configuration.js";
import { Organizations } from "./organizations.js";
import { Permissions } from "./permissions.js";
import { PlatformSettings } from "./platform-settings.js";
import { PublicUrls } from "./public-urls.js";
import { QueryService } from "./query-service.js";
import { QueryServices } from "./query-services.js";
import { QueueManagement } from "./queue-management.js";
import { Records } from "./records.js";
import { Saml } from "./saml.js";
import { SemanticSearch } from "./semantic-search.js";
import { SmtpConfiguration } from "./smtp-configuration.js";
import { StorageConfiguration } from "./storage-configuration.js";
import { Teams } from "./teams.js";
import { Upload } from "./upload.js";
import { UserAccount } from "./user-account.js";
import { UserGroups } from "./user-groups.js";
import { Users } from "./users.js";
import { VersionControl } from "./version-control.js";
import { Webhooks } from "./webhooks.js";

export class Pipeshub extends ClientSDK {
  private _userAccount?: UserAccount;
  get userAccount(): UserAccount {
    return (this._userAccount ??= new UserAccount(this._options));
  }

  private _oauth?: Oauth;
  get oauth(): Oauth {
    return (this._oauth ??= new Oauth(this._options));
  }

  private _oauthProvider?: OauthProvider;
  get oauthProvider(): OauthProvider {
    return (this._oauthProvider ??= new OauthProvider(this._options));
  }

  private _openIDConnect?: OpenIDConnect;
  get openIDConnect(): OpenIDConnect {
    return (this._openIDConnect ??= new OpenIDConnect(this._options));
  }

  private _oauthApps?: OauthApps;
  get oauthApps(): OauthApps {
    return (this._oauthApps ??= new OauthApps(this._options));
  }

  private _organizationAuthConfigs?: OrganizationAuthConfigs;
  get organizationAuthConfigs(): OrganizationAuthConfigs {
    return (this._organizationAuthConfigs ??= new OrganizationAuthConfigs(
      this._options,
    ));
  }

  private _organizationAuthConfig?: OrganizationAuthConfig;
  get organizationAuthConfig(): OrganizationAuthConfig {
    return (this._organizationAuthConfig ??= new OrganizationAuthConfig(
      this._options,
    ));
  }

  private _organizationAuthConfiguration?: OrganizationAuthConfiguration;
  get organizationAuthConfiguration(): OrganizationAuthConfiguration {
    return (this._organizationAuthConfiguration ??=
      new OrganizationAuthConfiguration(this._options));
  }

  private _saml?: Saml;
  get saml(): Saml {
    return (this._saml ??= new Saml(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }

  private _teams?: Teams;
  get teams(): Teams {
    return (this._teams ??= new Teams(this._options));
  }

  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }

  private _userGroups?: UserGroups;
  get userGroups(): UserGroups {
    return (this._userGroups ??= new UserGroups(this._options));
  }

  private _documentUpload?: DocumentUpload;
  get documentUpload(): DocumentUpload {
    return (this._documentUpload ??= new DocumentUpload(this._options));
  }

  private _documentManagement?: DocumentManagement;
  get documentManagement(): DocumentManagement {
    return (this._documentManagement ??= new DocumentManagement(this._options));
  }

  private _documentBuffer?: DocumentBuffer;
  get documentBuffer(): DocumentBuffer {
    return (this._documentBuffer ??= new DocumentBuffer(this._options));
  }

  private _versionControl?: VersionControl;
  get versionControl(): VersionControl {
    return (this._versionControl ??= new VersionControl(this._options));
  }

  private _knowledgeBases?: KnowledgeBases;
  get knowledgeBases(): KnowledgeBases {
    return (this._knowledgeBases ??= new KnowledgeBases(this._options));
  }

  private _records?: Records;
  get records(): Records {
    return (this._records ??= new Records(this._options));
  }

  private _folders?: Folders;
  get folders(): Folders {
    return (this._folders ??= new Folders(this._options));
  }

  private _upload?: Upload;
  get upload(): Upload {
    return (this._upload ??= new Upload(this._options));
  }

  private _connector?: Connector;
  get connector(): Connector {
    return (this._connector ??= new Connector(this._options));
  }

  private _permissions?: Permissions;
  get permissions(): Permissions {
    return (this._permissions ??= new Permissions(this._options));
  }

  private _conversations?: Conversations;
  get conversations(): Conversations {
    return (this._conversations ??= new Conversations(this._options));
  }

  private _semanticSearch?: SemanticSearch;
  get semanticSearch(): SemanticSearch {
    return (this._semanticSearch ??= new SemanticSearch(this._options));
  }

  private _agentTemplates?: AgentTemplates;
  get agentTemplates(): AgentTemplates {
    return (this._agentTemplates ??= new AgentTemplates(this._options));
  }

  private _agents?: Agents;
  get agents(): Agents {
    return (this._agents ??= new Agents(this._options));
  }

  private _agentConversations?: AgentConversations;
  get agentConversations(): AgentConversations {
    return (this._agentConversations ??= new AgentConversations(this._options));
  }

  private _connectorRegistry?: ConnectorRegistry;
  get connectorRegistry(): ConnectorRegistry {
    return (this._connectorRegistry ??= new ConnectorRegistry(this._options));
  }

  private _connectorInstances?: ConnectorInstances;
  get connectorInstances(): ConnectorInstances {
    return (this._connectorInstances ??= new ConnectorInstances(this._options));
  }

  private _connectorConfiguration?: ConnectorConfiguration;
  get connectorConfiguration(): ConnectorConfiguration {
    return (this._connectorConfiguration ??= new ConnectorConfiguration(
      this._options,
    ));
  }

  private _connectorConfigurations?: ConnectorConfigurations;
  get connectorConfigurations(): ConnectorConfigurations {
    return (this._connectorConfigurations ??= new ConnectorConfigurations(
      this._options,
    ));
  }

  private _connectorControl?: ConnectorControl;
  get connectorControl(): ConnectorControl {
    return (this._connectorControl ??= new ConnectorControl(this._options));
  }

  private _connectorOAuth?: ConnectorOAuth;
  get connectorOAuth(): ConnectorOAuth {
    return (this._connectorOAuth ??= new ConnectorOAuth(this._options));
  }

  private _connectorFilters?: ConnectorFilters;
  get connectorFilters(): ConnectorFilters {
    return (this._connectorFilters ??= new ConnectorFilters(this._options));
  }

  private _oauthConfiguration1?: OauthConfiguration1;
  get oauthConfiguration1(): OauthConfiguration1 {
    return (this._oauthConfiguration1 ??= new OauthConfiguration1(
      this._options,
    ));
  }

  private _oauthConfigurations?: OauthConfigurations;
  get oauthConfigurations(): OauthConfigurations {
    return (this._oauthConfigurations ??= new OauthConfigurations(
      this._options,
    ));
  }

  private _oAuthConfiguration2?: OAuthConfiguration2;
  get oAuthConfiguration2(): OAuthConfiguration2 {
    return (this._oAuthConfiguration2 ??= new OAuthConfiguration2(
      this._options,
    ));
  }

  private _storageConfiguration?: StorageConfiguration;
  get storageConfiguration(): StorageConfiguration {
    return (this._storageConfiguration ??= new StorageConfiguration(
      this._options,
    ));
  }

  private _smtpConfiguration?: SmtpConfiguration;
  get smtpConfiguration(): SmtpConfiguration {
    return (this._smtpConfiguration ??= new SmtpConfiguration(this._options));
  }

  private _authenticationConfiguration?: AuthenticationConfiguration;
  get authenticationConfiguration(): AuthenticationConfiguration {
    return (this._authenticationConfiguration ??=
      new AuthenticationConfiguration(this._options));
  }

  private _authenticationConfigurations?: AuthenticationConfigurations;
  get authenticationConfigurations(): AuthenticationConfigurations {
    return (this._authenticationConfigurations ??=
      new AuthenticationConfigurations(this._options));
  }

  private _authConfig?: AuthConfig;
  get authConfig(): AuthConfig {
    return (this._authConfig ??= new AuthConfig(this._options));
  }

  private _aiModelsConfiguration?: AiModelsConfiguration;
  get aiModelsConfiguration(): AiModelsConfiguration {
    return (this._aiModelsConfiguration ??= new AiModelsConfiguration(
      this._options,
    ));
  }

  private _aiModelsProviders?: AiModelsProviders;
  get aiModelsProviders(): AiModelsProviders {
    return (this._aiModelsProviders ??= new AiModelsProviders(this._options));
  }

  private _connectorOAuthConfiguration1?: ConnectorOAuthConfiguration1;
  get connectorOAuthConfiguration1(): ConnectorOAuthConfiguration1 {
    return (this._connectorOAuthConfiguration1 ??=
      new ConnectorOAuthConfiguration1(this._options));
  }

  private _connectorOAuthConfigurations?: ConnectorOAuthConfigurations;
  get connectorOAuthConfigurations(): ConnectorOAuthConfigurations {
    return (this._connectorOAuthConfigurations ??=
      new ConnectorOAuthConfigurations(this._options));
  }

  private _connectorOauthConfiguration2?: ConnectorOauthConfiguration2;
  get connectorOauthConfiguration2(): ConnectorOauthConfiguration2 {
    return (this._connectorOauthConfiguration2 ??=
      new ConnectorOauthConfiguration2(this._options));
  }

  private _publicUrls?: PublicUrls;
  get publicUrls(): PublicUrls {
    return (this._publicUrls ??= new PublicUrls(this._options));
  }

  private _platformSettings?: PlatformSettings;
  get platformSettings(): PlatformSettings {
    return (this._platformSettings ??= new PlatformSettings(this._options));
  }

  private _metricsCollection?: MetricsCollection;
  get metricsCollection(): MetricsCollection {
    return (this._metricsCollection ??= new MetricsCollection(this._options));
  }

  private _metricsCollections?: MetricsCollections;
  get metricsCollections(): MetricsCollections {
    return (this._metricsCollections ??= new MetricsCollections(this._options));
  }

  private _crawlingJobs?: CrawlingJobs;
  get crawlingJobs(): CrawlingJobs {
    return (this._crawlingJobs ??= new CrawlingJobs(this._options));
  }

  private _queueManagement?: QueueManagement;
  get queueManagement(): QueueManagement {
    return (this._queueManagement ??= new QueueManagement(this._options));
  }

  private _emailOperations?: EmailOperations;
  get emailOperations(): EmailOperations {
    return (this._emailOperations ??= new EmailOperations(this._options));
  }

  private _mailConfiguration?: MailConfiguration;
  get mailConfiguration(): MailConfiguration {
    return (this._mailConfiguration ??= new MailConfiguration(this._options));
  }

  private _queryServices?: QueryServices;
  get queryServices(): QueryServices {
    return (this._queryServices ??= new QueryServices(this._options));
  }

  private _queryService?: QueryService;
  get queryService(): QueryService {
    return (this._queryService ??= new QueryService(this._options));
  }

  private _indexingService?: IndexingService;
  get indexingService(): IndexingService {
    return (this._indexingService ??= new IndexingService(this._options));
  }

  private _connectorService?: ConnectorService;
  get connectorService(): ConnectorService {
    return (this._connectorService ??= new ConnectorService(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  private _connectorServices?: ConnectorServices;
  get connectorServices(): ConnectorServices {
    return (this._connectorServices ??= new ConnectorServices(this._options));
  }

  private _doclingService?: DoclingService;
  get doclingService(): DoclingService {
    return (this._doclingService ??= new DoclingService(this._options));
  }
}
