/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { semanticSearchDeleteAllSearchHistory } from "../funcs/semantic-search-delete-all-search-history.js";
import { semanticSearchSearchHistory } from "../funcs/semantic-search-search-history.js";
import { semanticSearchSearch } from "../funcs/semantic-search-search.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SemanticSearch extends ClientSDK {
  /**
   * Perform semantic search
   *
   * @remarks
   * Execute a semantic search across your organization's knowledge base.<br><br>
   * <b>Overview:</b><br>
   * Semantic search uses AI embeddings to find content based on meaning,
   * not just keyword matching. This enables finding relevant information
   * even when the exact words differ.<br><br>
   * <b>How It Works:</b><br>
   * <ol>
   * <li>Your query is converted to a vector embedding</li>
   * <li>The system finds documents with similar semantic meaning</li>
   * <li>Results are ranked by relevance score</li>
   * <li>Matching chunks are returned with metadata</li>
   * </ol>
   * <b>Filtering:</b><br>
   * Use filters to narrow your search:
   * <ul>
   * <li><code>filters.apps</code>: Limit to specific connector apps (Google Drive, Confluence, etc.)</li>
   * <li><code>filters.kb</code>: Limit to specific knowledge bases</li>
   * </ul>
   * <b>Results:</b><br>
   * Each result includes:
   * <ul>
   * <li>Matching content chunk</li>
   * <li>Relevance score (0-1, higher is better)</li>
   * <li>Source document metadata (name, URL, type)</li>
   * </ul>
   * <b>Search History:</b><br>
   * All searches are saved and can be retrieved via <code>GET /search</code>.
   */
  async search(
    request: models.SemanticSearchRequest,
    options?: RequestOptions,
  ): Promise<models.SearchResult> {
    return unwrapAsync(semanticSearchSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get search history
   *
   * @remarks
   * Retrieve your search history with pagination.<br><br>
   * <b>Overview:</b><br>
   * Returns a list of all searches performed by the authenticated user.
   * Each entry includes the original query, results, and metadata.<br><br>
   * <b>Pagination:</b><br>
   * Use <code>page</code> and <code>limit</code> to navigate through results.
   */
  async searchHistory(
    request?: operations.SearchHistoryRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.SearchHistoryResponse> {
    return unwrapAsync(semanticSearchSearchHistory(
      this,
      request,
      options,
    ));
  }

  /**
   * Clear all search history
   *
   * @remarks
   * Delete all search history for the authenticated user.<br><br>
   * <b>Warning:</b><br>
   * This action cannot be undone. All saved searches will be permanently removed.
   */
  async deleteAllSearchHistory(
    options?: RequestOptions,
  ): Promise<operations.DeleteAllSearchHistoryResponse> {
    return unwrapAsync(semanticSearchDeleteAllSearchHistory(
      this,
      options,
    ));
  }
}
