/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { smtpConfigurationCreateSMTPConfig } from "../funcs/smtp-configuration-create-smtp-config.js";
import { smtpConfigurationGetSMTPConfig } from "../funcs/smtp-configuration-get-smtp-config.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SMTPConfiguration extends ClientSDK {
  /**
   * Create or update SMTP configuration
   *
   * @remarks
   * Configure SMTP email server for sending system emails including user invitations, notifications, and password resets.
   *
   * Common SMTP providers and their settings:
   * - Gmail: host=smtp.gmail.com, port=587 (requires App Password)
   * - SendGrid: host=smtp.sendgrid.net, port=587
   * - Amazon SES: host=email-smtp.{region}.amazonaws.com, port=587
   * - Microsoft 365: host=smtp.office365.com, port=587
   *
   * Configuration is encrypted before storage.
   */
  async createSMTPConfig(
    request: models.SMTPConfig,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(smtpConfigurationCreateSMTPConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * Get SMTP configuration
   *
   * @remarks
   * Retrieve the current SMTP server configuration. Password is included in the response for admin users.
   */
  async getSMTPConfig(
    options?: RequestOptions,
  ): Promise<models.SMTPConfig> {
    return unwrapAsync(smtpConfigurationGetSMTPConfig(
      this,
      options,
    ));
  }
}
