/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageConfigurationGetStorageConfig } from "../funcs/storage-configuration-get-storage-config.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class StorageConfiguration extends ClientSDK {
  /**
   * Get current storage configuration
   *
   * @remarks
   * Retrieve the current storage backend configuration. Returns the configuration for whichever storage type is currently active (Local, S3, or Azure Blob).
   */
  async getStorageConfig(
    options?: RequestOptions,
  ): Promise<operations.GetStorageConfigResponse> {
    return unwrapAsync(storageConfigurationGetStorageConfig(
      this,
      options,
    ));
  }
}
