/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsAddUsersToGroup } from "../funcs/user-groups-add-users-to-group.js";
import { userGroupsCreateUserGroup } from "../funcs/user-groups-create-user-group.js";
import { userGroupsDeleteUserGroup } from "../funcs/user-groups-delete-user-group.js";
import { userGroupsGetAllUserGroups } from "../funcs/user-groups-get-all-user-groups.js";
import { userGroupsGetGroupsForUser } from "../funcs/user-groups-get-groups-for-user.js";
import { userGroupsGetUserGroupById } from "../funcs/user-groups-get-user-group-by-id.js";
import { userGroupsRemoveUsersFromGroup } from "../funcs/user-groups-remove-users-from-group.js";
import { userGroupsUpdateUserGroup } from "../funcs/user-groups-update-user-group.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserGroups extends ClientSDK {
  /**
   * Create user group
   *
   * @remarks
   * Create a new user group within the organization.<br><br>
   * <b>Group Types:</b><br>
   * <ul>
   * <li><code>admin</code> - Administrative group with elevated privileges</li>
   * <li><code>standard</code> - Regular user group</li>
   * <li><code>everyone</code> - Automatically includes all organization users</li>
   * <li><code>custom</code> - Custom group with manual membership management</li>
   * </ul>
   * <b>Validation Rules:</b><br>
   * <ul>
   * <li>Group name must be unique within the organization</li>
   * <li>Group name is required and cannot be empty</li>
   * <li>Type must be one of the allowed values</li>
   * </ul>
   * <b>Side Effects:</b><br>
   * <ul>
   * <li>Creates a unique slug from the group name</li>
   * <li>Sets createdBy to the authenticated user</li>
   * </ul>
   */
  async createUserGroup(
    request: operations.CreateUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroup> {
    return unwrapAsync(userGroupsCreateUserGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Get all user groups
   *
   * @remarks
   * Retrieve all user groups in the organization.<br><br>
   * <b>Response Details:</b><br>
   * <ul>
   * <li>Returns all groups including admin, standard, everyone, and custom types</li>
   * <li>Groups are returned with their member counts</li>
   * <li>Soft-deleted groups are excluded by default</li>
   * </ul>
   * <b>Use Cases:</b><br>
   * <ul>
   * <li>Populating group selection dropdowns</li>
   * <li>Managing group memberships</li>
   * <li>Access control configuration</li>
   * </ul>
   */
  async getAllUserGroups(
    options?: RequestOptions,
  ): Promise<operations.GetAllUserGroupsResponse> {
    return unwrapAsync(userGroupsGetAllUserGroups(
      this,
      options,
    ));
  }

  /**
   * Get user group by ID
   *
   * @remarks
   * Retrieve detailed information about a specific user group.<br><br>
   * <b>Response Includes:</b><br>
   * <ul>
   * <li>Group metadata (name, type, description)</li>
   * <li>Member count</li>
   * <li>Creation and modification timestamps</li>
   * <li>Creator information</li>
   * </ul>
   */
  async getUserGroupById(
    request: operations.GetUserGroupByIdRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroup> {
    return unwrapAsync(userGroupsGetUserGroupById(
      this,
      request,
      options,
    ));
  }

  /**
   * Update user group
   *
   * @remarks
   * Update an existing user group's information.<br><br>
   * <b>Updatable Fields:</b><br>
   * <ul>
   * <li><code>name</code> - Display name (must remain unique)</li>
   * <li><code>description</code> - Group description</li>
   * </ul>
   * <b>Note:</b> Group type cannot be changed after creation.
   */
  async updateUserGroup(
    request: operations.UpdateUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroup> {
    return unwrapAsync(userGroupsUpdateUserGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete user group
   *
   * @remarks
   * Soft delete a user group.<br><br>
   * <b>Behavior:</b><br>
   * <ul>
   * <li>Group is marked as deleted (isDeleted: true)</li>
   * <li>Group members are not affected</li>
   * <li>Group can be restored by admin if needed</li>
   * </ul>
   * <b>Restrictions:</b><br>
   * <ul>
   * <li>Cannot delete system groups (admin, everyone)</li>
   * <li>Requires admin privileges</li>
   * </ul>
   */
  async deleteUserGroup(
    request: operations.DeleteUserGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteUserGroupResponse> {
    return unwrapAsync(userGroupsDeleteUserGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Add users to group
   *
   * @remarks
   * Add one or more users to a user group.<br><br>
   * <b>Behavior:</b><br>
   * <ul>
   * <li>Users already in the group are silently skipped</li>
   * <li>Invalid user IDs are reported in the response</li>
   * <li>Operation is atomic - all valid users are added together</li>
   * </ul>
   * <b>Validation:</b><br>
   * <ul>
   * <li>All user IDs must be valid MongoDB ObjectIds</li>
   * <li>Users must belong to the same organization</li>
   * <li>Group must exist and not be deleted</li>
   * </ul>
   */
  async addUsersToGroup(
    request: operations.AddUsersToGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.AddUsersToGroupResponse> {
    return unwrapAsync(userGroupsAddUsersToGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove users from group
   *
   * @remarks
   * Remove one or more users from a user group.<br><br>
   * <b>Behavior:</b><br>
   * <ul>
   * <li>Users not in the group are silently skipped</li>
   * <li>Operation is atomic - all specified users are removed together</li>
   * </ul>
   * <b>Restrictions:</b><br>
   * <ul>
   * <li>Cannot remove users from "everyone" group type</li>
   * <li>Cannot remove the last admin from admin group</li>
   * </ul>
   */
  async removeUsersFromGroup(
    request: operations.RemoveUsersFromGroupRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveUsersFromGroupResponse> {
    return unwrapAsync(userGroupsRemoveUsersFromGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Get groups for a user
   *
   * @remarks
   * Retrieve all user groups that a specific user belongs to.<br><br>
   * <b>Response Details:</b><br>
   * <ul>
   * <li>Includes all group types (admin, standard, everyone, custom)</li>
   * <li>Returns group metadata for each membership</li>
   * </ul>
   * <b>Use Cases:</b><br>
   * <ul>
   * <li>Displaying user's group memberships in profile</li>
   * <li>Access control checks</li>
   * <li>Permission inheritance calculations</li>
   * </ul>
   */
  async getGroupsForUser(
    request: operations.GetGroupsForUserRequest,
    options?: RequestOptions,
  ): Promise<operations.GetGroupsForUserResponse> {
    return unwrapAsync(userGroupsGetGroupsForUser(
      this,
      request,
      options,
    ));
  }
}
