/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksHandle } from "../funcs/webhooks-handle.js";
import { webhooksPostGmail } from "../funcs/webhooks-post-gmail.js";
import { webhooksVerifyGmail } from "../funcs/webhooks-verify-gmail.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * [Connector Service] Gmail webhook verification
   *
   * @remarks
   * ⚠️ <b>INTERNAL SERVICE ENDPOINT</b><br><br>
   *
   * GET handler for Gmail Pub/Sub webhook verification.<br><br>
   *
   * <b>Service:</b> Connector Service<br>
   * <b>Port:</b> 8088<br>
   * <b>Base URL:</b> <code>http://localhost:8088</code><br><br>
   *
   * <b>Authentication:</b> None required - uses Google Pub/Sub verification<br><br>
   *
   * <b>Note:</b> Google Pub/Sub may send GET requests for subscription verification.
   */
  async verifyGmail(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksVerifyGmail(
      this,
      options,
    ));
  }

  /**
   * [Connector Service] Gmail webhook
   *
   * @remarks
   * ⚠️ <b>INTERNAL SERVICE ENDPOINT</b><br><br>
   *
   * Webhook endpoint for Gmail Pub/Sub notifications.<br><br>
   *
   * <b>Service:</b> Connector Service<br>
   * <b>Port:</b> 8088<br>
   * <b>Base URL:</b> <code>http://localhost:8088</code><br><br>
   *
   * <b>Authentication:</b> None required - uses Google Pub/Sub verification<br><br>
   *
   * <b>Note:</b> This endpoint receives notifications when new emails arrive
   * or email labels change.
   */
  async postGmail(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksPostGmail(
      this,
      options,
    ));
  }

  /**
   * [Connector Service] Google Workspace Admin webhook
   *
   * @remarks
   * ⚠️ <b>INTERNAL SERVICE ENDPOINT</b><br><br>
   *
   * Webhook endpoint for Google Workspace Admin push notifications.<br><br>
   *
   * <b>Service:</b> Connector Service<br>
   * <b>Port:</b> 8088<br>
   * <b>Base URL:</b> <code>http://localhost:8088</code><br><br>
   *
   * <b>Authentication:</b> Verified via Google Workspace webhook signature<br><br>
   *
   * <b>Note:</b> This endpoint receives notifications about user and group
   * changes from Google Workspace Admin directory (e.g., user created,
   * deleted, suspended, group membership changes).
   */
  async handle(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksHandle(
      this,
      options,
    ));
  }
}
