// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type AddAgentMessageRequest struct {
	AgentKey       string `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// Request payload
	Body components.AddMessageRequest `request:"mediaType=application/json"`
}

func (o *AddAgentMessageRequest) GetAgentKey() string {
	if o == nil {
		return ""
	}
	return o.AgentKey
}

func (o *AddAgentMessageRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

func (o *AddAgentMessageRequest) GetBody() components.AddMessageRequest {
	if o == nil {
		return components.AddMessageRequest{}
	}
	return o.Body
}

type AddAgentMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Message added
	AgentConversation *components.AgentConversation
}

func (o *AddAgentMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AddAgentMessageResponse) GetAgentConversation() *components.AgentConversation {
	if o == nil {
		return nil
	}
	return o.AgentConversation
}
