// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type AddAIModelProviderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// AI model provider added successfully
	AIModelProviderResponse *components.AIModelProviderResponse
}

func (o *AddAIModelProviderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AddAIModelProviderResponse) GetAIModelProviderResponse() *components.AIModelProviderResponse {
	if o == nil {
		return nil
	}
	return o.AIModelProviderResponse
}
