// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type ArchiveConversationRequest struct {
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
}

func (o *ArchiveConversationRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

type ArchiveConversationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Conversation archived successfully
	Conversation *components.Conversation
}

func (o *ArchiveConversationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ArchiveConversationResponse) GetConversation() *components.Conversation {
	if o == nil {
		return nil
	}
	return o.Conversation
}
