// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateTeamRequest - Request payload
type CreateTeamRequest struct {
	// Team display name (must be unique in org)
	Name string `json:"name"`
	// Team description and purpose
	Description *string `json:"description,omitempty"`
	// Optional initial members with roles
	UserRoles []components.UserRole `json:"userRoles,omitempty"`
}

func (o *CreateTeamRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateTeamRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateTeamRequest) GetUserRoles() []components.UserRole {
	if o == nil {
		return nil
	}
	return o.UserRoles
}

// CreateTeamResponseBody - Team created successfully
type CreateTeamResponseBody struct {
	Success *bool            `json:"success,omitempty"`
	Message *string          `json:"message,omitempty"`
	Data    *components.Team `json:"data,omitempty"`
}

func (o *CreateTeamResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *CreateTeamResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *CreateTeamResponseBody) GetData() *components.Team {
	if o == nil {
		return nil
	}
	return o.Data
}

type CreateTeamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Team created successfully
	Object *CreateTeamResponseBody
}

func (o *CreateTeamResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateTeamResponse) GetObject() *CreateTeamResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
