// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateConversationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Conversation created successfully
	Conversation *components.Conversation
}

func (o *CreateConversationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateConversationResponse) GetConversation() *components.Conversation {
	if o == nil {
		return nil
	}
	return o.Conversation
}
