// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateRootFolderRequestBody - Request payload
type CreateRootFolderRequestBody struct {
	// Name of the folder
	FolderName string `json:"folderName"`
}

func (o *CreateRootFolderRequestBody) GetFolderName() string {
	if o == nil {
		return ""
	}
	return o.FolderName
}

type CreateRootFolderRequest struct {
	// Knowledge base ID
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Request payload
	Body CreateRootFolderRequestBody `request:"mediaType=application/json"`
}

func (o *CreateRootFolderRequest) GetKbID() string {
	if o == nil {
		return ""
	}
	return o.KbID
}

func (o *CreateRootFolderRequest) GetBody() CreateRootFolderRequestBody {
	if o == nil {
		return CreateRootFolderRequestBody{}
	}
	return o.Body
}

type CreateRootFolderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Folder created successfully
	Folder *components.Folder
}

func (o *CreateRootFolderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateRootFolderResponse) GetFolder() *components.Folder {
	if o == nil {
		return nil
	}
	return o.Folder
}
