// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type CreateAgentModelConfig struct {
	ModelKey    *string  `json:"modelKey,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
	MaxTokens   *int64   `json:"maxTokens,omitempty"`
}

func (o *CreateAgentModelConfig) GetModelKey() *string {
	if o == nil {
		return nil
	}
	return o.ModelKey
}

func (o *CreateAgentModelConfig) GetTemperature() *float64 {
	if o == nil {
		return nil
	}
	return o.Temperature
}

func (o *CreateAgentModelConfig) GetMaxTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxTokens
}

// CreateAgentRequest - Request payload
type CreateAgentRequest struct {
	// Agent display name
	Name string `json:"name"`
	// What the agent does
	Description *string `json:"description,omitempty"`
	// System instructions for the agent
	SystemPrompt *string `json:"systemPrompt,omitempty"`
	// Tool keys the agent can use
	Tools []string `json:"tools,omitempty"`
	// Knowledge base IDs to access
	KnowledgeBases []string                `json:"knowledgeBases,omitempty"`
	ModelConfig    *CreateAgentModelConfig `json:"modelConfig,omitempty"`
	// Make agent available to all org users
	IsPublic *bool `default:"false" json:"isPublic"`
}

func (c CreateAgentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAgentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (o *CreateAgentRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateAgentRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateAgentRequest) GetSystemPrompt() *string {
	if o == nil {
		return nil
	}
	return o.SystemPrompt
}

func (o *CreateAgentRequest) GetTools() []string {
	if o == nil {
		return nil
	}
	return o.Tools
}

func (o *CreateAgentRequest) GetKnowledgeBases() []string {
	if o == nil {
		return nil
	}
	return o.KnowledgeBases
}

func (o *CreateAgentRequest) GetModelConfig() *CreateAgentModelConfig {
	if o == nil {
		return nil
	}
	return o.ModelConfig
}

func (o *CreateAgentRequest) GetIsPublic() *bool {
	if o == nil {
		return nil
	}
	return o.IsPublic
}

type CreateAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent created
	Agent *components.Agent
}

func (o *CreateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAgentResponse) GetAgent() *components.Agent {
	if o == nil {
		return nil
	}
	return o.Agent
}
