// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// CreateKnowledgeBaseRequest - Request payload
type CreateKnowledgeBaseRequest struct {
	// Name of the knowledge base
	KbName string `json:"kbName"`
}

func (o *CreateKnowledgeBaseRequest) GetKbName() string {
	if o == nil {
		return ""
	}
	return o.KbName
}

type CreateKnowledgeBaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Knowledge base created successfully
	KnowledgeBase *components.KnowledgeBase
}

func (o *CreateKnowledgeBaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateKnowledgeBaseResponse) GetKnowledgeBase() *components.KnowledgeBase {
	if o == nil {
		return nil
	}
	return o.KnowledgeBase
}
