// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type DeleteOAuthConfigRequest struct {
	ConnectorType string `pathParam:"style=simple,explode=false,name=connectorType"`
	ConfigID      string `pathParam:"style=simple,explode=false,name=configId"`
}

func (o *DeleteOAuthConfigRequest) GetConnectorType() string {
	if o == nil {
		return ""
	}
	return o.ConnectorType
}

func (o *DeleteOAuthConfigRequest) GetConfigID() string {
	if o == nil {
		return ""
	}
	return o.ConfigID
}

// DeleteOAuthConfigResponseBody - OAuth configuration deleted
type DeleteOAuthConfigResponseBody struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *DeleteOAuthConfigResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *DeleteOAuthConfigResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type DeleteOAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth configuration deleted
	Object *DeleteOAuthConfigResponseBody
}

func (o *DeleteOAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteOAuthConfigResponse) GetObject() *DeleteOAuthConfigResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
