// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// GenerateLoginOtpResponseBody - OTP generated and sent successfully
type GenerateLoginOtpResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *GenerateLoginOtpResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type GenerateLoginOtpResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OTP generated and sent successfully
	Object *GenerateLoginOtpResponseBody
}

func (o *GenerateLoginOtpResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GenerateLoginOtpResponse) GetObject() *GenerateLoginOtpResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
