// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAvailableModelsByTypeRequest struct {
	// Type of AI model
	ModelType components.ModelType `pathParam:"style=simple,explode=false,name=modelType"`
}

func (o *GetAvailableModelsByTypeRequest) GetModelType() components.ModelType {
	if o == nil {
		return components.ModelType("")
	}
	return o.ModelType
}

type Model struct {
	ModelKey  *string `json:"modelKey,omitempty"`
	Provider  *string `json:"provider,omitempty"`
	Model     *string `json:"model,omitempty"`
	IsDefault *bool   `json:"isDefault,omitempty"`
}

func (o *Model) GetModelKey() *string {
	if o == nil {
		return nil
	}
	return o.ModelKey
}

func (o *Model) GetProvider() *string {
	if o == nil {
		return nil
	}
	return o.Provider
}

func (o *Model) GetModel() *string {
	if o == nil {
		return nil
	}
	return o.Model
}

func (o *Model) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

// GetAvailableModelsByTypeResponseBody - Available models retrieved
type GetAvailableModelsByTypeResponseBody struct {
	Status  *string `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
	Models  []Model `json:"models,omitempty"`
}

func (o *GetAvailableModelsByTypeResponseBody) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *GetAvailableModelsByTypeResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetAvailableModelsByTypeResponseBody) GetModels() []Model {
	if o == nil {
		return nil
	}
	return o.Models
}

type GetAvailableModelsByTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Available models retrieved
	Object *GetAvailableModelsByTypeResponseBody
}

func (o *GetAvailableModelsByTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAvailableModelsByTypeResponse) GetObject() *GetAvailableModelsByTypeResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
