// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAzureAdAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Azure AD configuration retrieved
	AzureAdAuthConfig *components.AzureAdAuthConfig
}

func (o *GetAzureAdAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAzureAdAuthConfigResponse) GetAzureAdAuthConfig() *components.AzureAdAuthConfig {
	if o == nil {
		return nil
	}
	return o.AzureAdAuthConfig
}
