// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAgentTemplateRequest struct {
	// Template identifier
	TemplateID string `pathParam:"style=simple,explode=false,name=templateId"`
}

func (o *GetAgentTemplateRequest) GetTemplateID() string {
	if o == nil {
		return ""
	}
	return o.TemplateID
}

type GetAgentTemplateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Template details
	AgentTemplate *components.AgentTemplate
}

func (o *GetAgentTemplateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAgentTemplateResponse) GetAgentTemplate() *components.AgentTemplate {
	if o == nil {
		return nil
	}
	return o.AgentTemplate
}
