// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
	"time"
)

type GetAllConversationsPagination struct {
	Page        *int64 `json:"page,omitempty"`
	Limit       *int64 `json:"limit,omitempty"`
	TotalCount  *int64 `json:"totalCount,omitempty"`
	TotalPages  *int64 `json:"totalPages,omitempty"`
	HasNextPage *bool  `json:"hasNextPage,omitempty"`
	HasPrevPage *bool  `json:"hasPrevPage,omitempty"`
}

func (o *GetAllConversationsPagination) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetAllConversationsPagination) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetAllConversationsPagination) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *GetAllConversationsPagination) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

func (o *GetAllConversationsPagination) GetHasNextPage() *bool {
	if o == nil {
		return nil
	}
	return o.HasNextPage
}

func (o *GetAllConversationsPagination) GetHasPrevPage() *bool {
	if o == nil {
		return nil
	}
	return o.HasPrevPage
}

// GetAllConversationsFilters - Applied and available filters
type GetAllConversationsFilters struct {
}

type GetAllConversationsMeta struct {
	RequestID *string    `json:"requestId,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Duration  *int64     `json:"duration,omitempty"`
}

func (g GetAllConversationsMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllConversationsMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetAllConversationsMeta) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *GetAllConversationsMeta) GetTimestamp() *time.Time {
	if o == nil {
		return nil
	}
	return o.Timestamp
}

func (o *GetAllConversationsMeta) GetDuration() *int64 {
	if o == nil {
		return nil
	}
	return o.Duration
}

// GetAllConversationsResponseBody - List of conversations
type GetAllConversationsResponseBody struct {
	Conversations             []components.Conversation      `json:"conversations,omitempty"`
	SharedWithMeConversations []components.Conversation      `json:"sharedWithMeConversations,omitempty"`
	Pagination                *GetAllConversationsPagination `json:"pagination,omitempty"`
	// Applied and available filters
	Filters *GetAllConversationsFilters `json:"filters,omitempty"`
	Meta    *GetAllConversationsMeta    `json:"meta,omitempty"`
}

func (o *GetAllConversationsResponseBody) GetConversations() []components.Conversation {
	if o == nil {
		return nil
	}
	return o.Conversations
}

func (o *GetAllConversationsResponseBody) GetSharedWithMeConversations() []components.Conversation {
	if o == nil {
		return nil
	}
	return o.SharedWithMeConversations
}

func (o *GetAllConversationsResponseBody) GetPagination() *GetAllConversationsPagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}

func (o *GetAllConversationsResponseBody) GetFilters() *GetAllConversationsFilters {
	if o == nil {
		return nil
	}
	return o.Filters
}

func (o *GetAllConversationsResponseBody) GetMeta() *GetAllConversationsMeta {
	if o == nil {
		return nil
	}
	return o.Meta
}

type GetAllConversationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of conversations
	Object *GetAllConversationsResponseBody
}

func (o *GetAllConversationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAllConversationsResponse) GetObject() *GetAllConversationsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
