// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAgentConversationRequest struct {
	AgentKey       string `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
}

func (o *GetAgentConversationRequest) GetAgentKey() string {
	if o == nil {
		return ""
	}
	return o.AgentKey
}

func (o *GetAgentConversationRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

type GetAgentConversationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent conversation details
	AgentConversation *components.AgentConversation
}

func (o *GetAgentConversationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAgentConversationResponse) GetAgentConversation() *components.AgentConversation {
	if o == nil {
		return nil
	}
	return o.AgentConversation
}
