// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetFolderChildrenSortOrder string

const (
	GetFolderChildrenSortOrderAsc  GetFolderChildrenSortOrder = "asc"
	GetFolderChildrenSortOrderDesc GetFolderChildrenSortOrder = "desc"
)

func (e GetFolderChildrenSortOrder) ToPointer() *GetFolderChildrenSortOrder {
	return &e
}
func (e *GetFolderChildrenSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = GetFolderChildrenSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetFolderChildrenSortOrder: %v", v)
	}
}

type GetFolderChildrenRequest struct {
	// Knowledge base ID
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Folder ID
	FolderID  string                      `pathParam:"style=simple,explode=false,name=folderId"`
	Page      *int64                      `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit     *int64                      `default:"20" queryParam:"style=form,explode=true,name=limit"`
	Search    *string                     `queryParam:"style=form,explode=true,name=search"`
	SortBy    *string                     `default:"createdAtTimestamp" queryParam:"style=form,explode=true,name=sortBy"`
	SortOrder *GetFolderChildrenSortOrder `default:"desc" queryParam:"style=form,explode=true,name=sortOrder"`
}

func (g GetFolderChildrenRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFolderChildrenRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"kbId", "folderId"}); err != nil {
		return err
	}
	return nil
}

func (o *GetFolderChildrenRequest) GetKbID() string {
	if o == nil {
		return ""
	}
	return o.KbID
}

func (o *GetFolderChildrenRequest) GetFolderID() string {
	if o == nil {
		return ""
	}
	return o.FolderID
}

func (o *GetFolderChildrenRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetFolderChildrenRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetFolderChildrenRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *GetFolderChildrenRequest) GetSortBy() *string {
	if o == nil {
		return nil
	}
	return o.SortBy
}

func (o *GetFolderChildrenRequest) GetSortOrder() *GetFolderChildrenSortOrder {
	if o == nil {
		return nil
	}
	return o.SortOrder
}

type GetFolderChildrenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Folder children retrieved
	RecordsResponse *components.RecordsResponse
}

func (o *GetFolderChildrenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetFolderChildrenResponse) GetRecordsResponse() *components.RecordsResponse {
	if o == nil {
		return nil
	}
	return o.RecordsResponse
}
