// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetGenericOAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth configuration retrieved
	GenericOAuthConfig *components.GenericOAuthConfig
}

func (o *GetGenericOAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetGenericOAuthConfigResponse) GetGenericOAuthConfig() *components.GenericOAuthConfig {
	if o == nil {
		return nil
	}
	return o.GenericOAuthConfig
}
