// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetOAuthConfigRequest struct {
	ConnectorType string `pathParam:"style=simple,explode=false,name=connectorType"`
	ConfigID      string `pathParam:"style=simple,explode=false,name=configId"`
}

func (o *GetOAuthConfigRequest) GetConnectorType() string {
	if o == nil {
		return ""
	}
	return o.ConnectorType
}

func (o *GetOAuthConfigRequest) GetConfigID() string {
	if o == nil {
		return ""
	}
	return o.ConfigID
}

// GetOAuthConfigResponseBody - OAuth configuration retrieved
type GetOAuthConfigResponseBody struct {
	Success *bool `json:"success,omitempty"`
	// OAuth configuration for a connector type. Created by admins to enable
	// OAuth authentication for connectors.
	//
	OauthConfig *components.OAuthConfig `json:"oauthConfig,omitempty"`
}

func (o *GetOAuthConfigResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *GetOAuthConfigResponseBody) GetOauthConfig() *components.OAuthConfig {
	if o == nil {
		return nil
	}
	return o.OauthConfig
}

type GetOAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth configuration retrieved
	Object *GetOAuthConfigResponseBody
}

func (o *GetOAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOAuthConfigResponse) GetObject() *GetOAuthConfigResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
