// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type GetOAuthRegistryRequest struct {
	Page   *int64  `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit  *int64  `default:"20" queryParam:"style=form,explode=true,name=limit"`
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (g GetOAuthRegistryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOAuthRegistryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *GetOAuthRegistryRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *GetOAuthRegistryRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetOAuthRegistryRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

// GetOAuthRegistryResponseBody - OAuth connector types retrieved
type GetOAuthRegistryResponseBody struct {
	Success    *bool                      `json:"success,omitempty"`
	Connectors []components.ConnectorType `json:"connectors,omitempty"`
	// Pagination information for connector lists
	Pagination *components.ConnectorPagination `json:"pagination,omitempty"`
}

func (o *GetOAuthRegistryResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *GetOAuthRegistryResponseBody) GetConnectors() []components.ConnectorType {
	if o == nil {
		return nil
	}
	return o.Connectors
}

func (o *GetOAuthRegistryResponseBody) GetPagination() *components.ConnectorPagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}

type GetOAuthRegistryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth connector types retrieved
	Object *GetOAuthRegistryResponseBody
}

func (o *GetOAuthRegistryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetOAuthRegistryResponse) GetObject() *GetOAuthRegistryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
