// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetSsoAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSO configuration retrieved
	SSOAuthConfig *components.SSOAuthConfig
}

func (o *GetSsoAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetSsoAuthConfigResponse) GetSSOAuthConfig() *components.SSOAuthConfig {
	if o == nil {
		return nil
	}
	return o.SSOAuthConfig
}
