// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetToolsetConfigRequest struct {
	ToolsetID string `pathParam:"style=simple,explode=false,name=toolsetId"`
}

func (o *GetToolsetConfigRequest) GetToolsetID() string {
	if o == nil {
		return ""
	}
	return o.ToolsetID
}

type GetToolsetConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *GetToolsetConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
