// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type HandleOAuthCallbackRequest struct {
	// Authorization code from provider
	Code *string `queryParam:"style=form,explode=true,name=code"`
	// State parameter (contains connector ID)
	State *string `queryParam:"style=form,explode=true,name=state"`
	// Error code if authorization failed
	Error *string `queryParam:"style=form,explode=true,name=error"`
	// Base URL for redirect
	BaseURL *string `queryParam:"style=form,explode=true,name=baseUrl"`
}

func (o *HandleOAuthCallbackRequest) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *HandleOAuthCallbackRequest) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *HandleOAuthCallbackRequest) GetError() *string {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *HandleOAuthCallbackRequest) GetBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseURL
}

type HandleOAuthCallbackResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (o *HandleOAuthCallbackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *HandleOAuthCallbackResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
