// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ListToolsetRegistryRequest struct {
	Page         *int64  `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit        *int64  `default:"50" queryParam:"style=form,explode=true,name=limit"`
	Search       *string `queryParam:"style=form,explode=true,name=search"`
	IncludeTools *bool   `queryParam:"style=form,explode=true,name=include_tools"`
}

func (l ListToolsetRegistryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListToolsetRegistryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ListToolsetRegistryRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListToolsetRegistryRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListToolsetRegistryRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListToolsetRegistryRequest) GetIncludeTools() *bool {
	if o == nil {
		return nil
	}
	return o.IncludeTools
}

type ListToolsetRegistryToolset struct {
}

// ListToolsetRegistryResponseBody - Toolsets retrieved successfully
type ListToolsetRegistryResponseBody struct {
	Toolsets []ListToolsetRegistryToolset `json:"toolsets,omitempty"`
	Total    *int64                       `json:"total,omitempty"`
	Page     *int64                       `json:"page,omitempty"`
	Limit    *int64                       `json:"limit,omitempty"`
}

func (o *ListToolsetRegistryResponseBody) GetToolsets() []ListToolsetRegistryToolset {
	if o == nil {
		return nil
	}
	return o.Toolsets
}

func (o *ListToolsetRegistryResponseBody) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *ListToolsetRegistryResponseBody) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListToolsetRegistryResponseBody) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

type ListToolsetRegistryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Toolsets retrieved successfully
	Object *ListToolsetRegistryResponseBody
}

func (o *ListToolsetRegistryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListToolsetRegistryResponse) GetObject() *ListToolsetRegistryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
