// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ListTeamsRequest struct {
	// Search teams by name or description
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Number of results per page
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Page number (1-based)
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
}

func (l ListTeamsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListTeamsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ListTeamsRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListTeamsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListTeamsRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

type ListTeamsPagination struct {
	Page       *int64 `json:"page,omitempty"`
	Limit      *int64 `json:"limit,omitempty"`
	Total      *int64 `json:"total,omitempty"`
	TotalPages *int64 `json:"totalPages,omitempty"`
}

func (o *ListTeamsPagination) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListTeamsPagination) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListTeamsPagination) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *ListTeamsPagination) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

// ListTeamsResponseBody - Teams retrieved successfully
type ListTeamsResponseBody struct {
	Success    *bool                `json:"success,omitempty"`
	Data       []components.Team    `json:"data,omitempty"`
	Pagination *ListTeamsPagination `json:"pagination,omitempty"`
}

func (o *ListTeamsResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *ListTeamsResponseBody) GetData() []components.Team {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *ListTeamsResponseBody) GetPagination() *ListTeamsPagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}

type ListTeamsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Teams retrieved successfully
	Object *ListTeamsResponseBody
}

func (o *ListTeamsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListTeamsResponse) GetObject() *ListTeamsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
