// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type ListConfiguredToolsetsToolset struct {
}

// ListConfiguredToolsetsResponseBody - Configured toolsets retrieved successfully
type ListConfiguredToolsetsResponseBody struct {
	Toolsets []ListConfiguredToolsetsToolset `json:"toolsets,omitempty"`
}

func (o *ListConfiguredToolsetsResponseBody) GetToolsets() []ListConfiguredToolsetsToolset {
	if o == nil {
		return nil
	}
	return o.Toolsets
}

type ListConfiguredToolsetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Configured toolsets retrieved successfully
	Object *ListConfiguredToolsetsResponseBody
}

func (o *ListConfiguredToolsetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListConfiguredToolsetsResponse) GetObject() *ListConfiguredToolsetsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
