// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

// ListUsersGraphSortBy - Field to sort by
type ListUsersGraphSortBy string

const (
	ListUsersGraphSortByFullName  ListUsersGraphSortBy = "fullName"
	ListUsersGraphSortByEmail     ListUsersGraphSortBy = "email"
	ListUsersGraphSortByCreatedAt ListUsersGraphSortBy = "createdAt"
)

func (e ListUsersGraphSortBy) ToPointer() *ListUsersGraphSortBy {
	return &e
}
func (e *ListUsersGraphSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fullName":
		fallthrough
	case "email":
		fallthrough
	case "createdAt":
		*e = ListUsersGraphSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListUsersGraphSortBy: %v", v)
	}
}

// ListUsersGraphSortOrder - Sort direction
type ListUsersGraphSortOrder string

const (
	ListUsersGraphSortOrderAsc  ListUsersGraphSortOrder = "asc"
	ListUsersGraphSortOrderDesc ListUsersGraphSortOrder = "desc"
)

func (e ListUsersGraphSortOrder) ToPointer() *ListUsersGraphSortOrder {
	return &e
}
func (e *ListUsersGraphSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListUsersGraphSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListUsersGraphSortOrder: %v", v)
	}
}

type ListUsersGraphRequest struct {
	// Page number (1-based)
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of results per page
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Search query (searches name and email)
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Field to sort by
	SortBy *ListUsersGraphSortBy `default:"fullName" queryParam:"style=form,explode=true,name=sortBy"`
	// Sort direction
	SortOrder *ListUsersGraphSortOrder `default:"asc" queryParam:"style=form,explode=true,name=sortOrder"`
}

func (l ListUsersGraphRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListUsersGraphRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ListUsersGraphRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListUsersGraphRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListUsersGraphRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

func (o *ListUsersGraphRequest) GetSortBy() *ListUsersGraphSortBy {
	if o == nil {
		return nil
	}
	return o.SortBy
}

func (o *ListUsersGraphRequest) GetSortOrder() *ListUsersGraphSortOrder {
	if o == nil {
		return nil
	}
	return o.SortOrder
}

type ListUsersGraphPagination struct {
	Page       *int64 `json:"page,omitempty"`
	Limit      *int64 `json:"limit,omitempty"`
	Total      *int64 `json:"total,omitempty"`
	TotalPages *int64 `json:"totalPages,omitempty"`
}

func (o *ListUsersGraphPagination) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListUsersGraphPagination) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListUsersGraphPagination) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *ListUsersGraphPagination) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}

// ListUsersGraphResponseBody - Paginated list of users
type ListUsersGraphResponseBody struct {
	Success    *bool                     `json:"success,omitempty"`
	Data       []components.User         `json:"data,omitempty"`
	Pagination *ListUsersGraphPagination `json:"pagination,omitempty"`
	Total      *int64                    `json:"total,omitempty"`
	Page       *int64                    `json:"page,omitempty"`
	Limit      *int64                    `json:"limit,omitempty"`
}

func (o *ListUsersGraphResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *ListUsersGraphResponseBody) GetData() []components.User {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *ListUsersGraphResponseBody) GetPagination() *ListUsersGraphPagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}

func (o *ListUsersGraphResponseBody) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *ListUsersGraphResponseBody) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListUsersGraphResponseBody) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

type ListUsersGraphResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of users
	Object *ListUsersGraphResponseBody
}

func (o *ListUsersGraphResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListUsersGraphResponse) GetObject() *ListUsersGraphResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
