// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type ListConnectorInstancesRequest struct {
	// Filter by scope (team or personal)
	Scope components.ConnectorScope `queryParam:"style=form,explode=true,name=scope"`
	Page  *int64                    `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit *int64                    `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Search by instance name
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (l ListConnectorInstancesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConnectorInstancesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"scope"}); err != nil {
		return err
	}
	return nil
}

func (o *ListConnectorInstancesRequest) GetScope() components.ConnectorScope {
	if o == nil {
		return components.ConnectorScope("")
	}
	return o.Scope
}

func (o *ListConnectorInstancesRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ListConnectorInstancesRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListConnectorInstancesRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}

// ListConnectorInstancesResponseBody - Instances retrieved
type ListConnectorInstancesResponseBody struct {
	Success    *bool                          `json:"success,omitempty"`
	Connectors []components.ConnectorInstance `json:"connectors,omitempty"`
	// Pagination information for connector lists
	Pagination *components.ConnectorPagination `json:"pagination,omitempty"`
}

func (o *ListConnectorInstancesResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *ListConnectorInstancesResponseBody) GetConnectors() []components.ConnectorInstance {
	if o == nil {
		return nil
	}
	return o.Connectors
}

func (o *ListConnectorInstancesResponseBody) GetPagination() *components.ConnectorPagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}

type ListConnectorInstancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instances retrieved
	Object *ListConnectorInstancesResponseBody
}

func (o *ListConnectorInstancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListConnectorInstancesResponse) GetObject() *ListConnectorInstancesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
