// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type Scope struct {
	Name                *string `json:"name,omitempty"`
	Description         *string `json:"description,omitempty"`
	Category            *string `json:"category,omitempty"`
	RequiresUserConsent *bool   `json:"requiresUserConsent,omitempty"`
}

func (o *Scope) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Scope) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Scope) GetCategory() *string {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *Scope) GetRequiresUserConsent() *bool {
	if o == nil {
		return nil
	}
	return o.RequiresUserConsent
}

// ListOAuthScopesResponseBody - List of available scopes
type ListOAuthScopesResponseBody struct {
	// Scopes grouped by category
	Scopes map[string][]Scope `json:"scopes,omitempty"`
}

func (o *ListOAuthScopesResponseBody) GetScopes() map[string][]Scope {
	if o == nil {
		return nil
	}
	return o.Scopes
}

type ListOAuthScopesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of available scopes
	Object *ListOAuthScopesResponseBody
}

func (o *ListOAuthScopesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListOAuthScopesResponse) GetObject() *ListOAuthScopesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
