// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

// ReindexRecordGroupRequestBody - Request payload
type ReindexRecordGroupRequestBody struct {
	Depth *int64 `default:"-1" json:"depth"`
}

func (r ReindexRecordGroupRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReindexRecordGroupRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ReindexRecordGroupRequestBody) GetDepth() *int64 {
	if o == nil {
		return nil
	}
	return o.Depth
}

type ReindexRecordGroupRequest struct {
	// Folder ID or KB ID
	RecordGroupID string `pathParam:"style=simple,explode=false,name=recordGroupId"`
	// Request payload
	Body *ReindexRecordGroupRequestBody `request:"mediaType=application/json"`
}

func (o *ReindexRecordGroupRequest) GetRecordGroupID() string {
	if o == nil {
		return ""
	}
	return o.RecordGroupID
}

func (o *ReindexRecordGroupRequest) GetBody() *ReindexRecordGroupRequestBody {
	if o == nil {
		return nil
	}
	return o.Body
}

type ReindexRecordGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *ReindexRecordGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
