// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// RemoveUserDisplayPictureResponseBody - Display picture removed successfully
type RemoveUserDisplayPictureResponseBody struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *RemoveUserDisplayPictureResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *RemoveUserDisplayPictureResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type RemoveUserDisplayPictureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Display picture removed successfully
	Object *RemoveUserDisplayPictureResponseBody
}

func (o *RemoveUserDisplayPictureResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RemoveUserDisplayPictureResponse) GetObject() *RemoveUserDisplayPictureResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
