// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type SaveConnectorFiltersRequest struct {
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
	// Request payload
	Body components.SaveConnectorFiltersRequest `request:"mediaType=application/json"`
}

func (o *SaveConnectorFiltersRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *SaveConnectorFiltersRequest) GetBody() components.SaveConnectorFiltersRequest {
	if o == nil {
		return components.SaveConnectorFiltersRequest{}
	}
	return o.Body
}

// SaveConnectorFiltersResponseBody - Filters saved
type SaveConnectorFiltersResponseBody struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *SaveConnectorFiltersResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *SaveConnectorFiltersResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type SaveConnectorFiltersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Filters saved
	Object *SaveConnectorFiltersResponseBody
}

func (o *SaveConnectorFiltersResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SaveConnectorFiltersResponse) GetObject() *SaveConnectorFiltersResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
