// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types/stream"
)

type StreamChatResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE stream established
	SSEEvent *stream.EventStream[components.SSEEvent]
}

func (o *StreamChatResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StreamChatResponse) GetSSEEvent() *stream.EventStream[components.SSEEvent] {
	if o == nil {
		return nil
	}
	return o.SSEEvent
}
