// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type StreamRecordBufferRequest struct {
	// Record ID
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
	// Target format for conversion
	ConvertTo *string `queryParam:"style=form,explode=true,name=convertTo"`
}

func (o *StreamRecordBufferRequest) GetRecordID() string {
	if o == nil {
		return ""
	}
	return o.RecordID
}

func (o *StreamRecordBufferRequest) GetConvertTo() *string {
	if o == nil {
		return nil
	}
	return o.ConvertTo
}

type StreamRecordBufferResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// File content stream
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (o *StreamRecordBufferResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StreamRecordBufferResponse) GetResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.ResponseStream
}
