// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UnblockUserRequest struct {
	// User ID to unblock
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *UnblockUserRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

// UnblockUserResponseBody - User unblocked successfully
type UnblockUserResponseBody struct {
	Message *string `json:"message,omitempty"`
}

func (o *UnblockUserResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type UnblockUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User unblocked successfully
	Object *UnblockUserResponseBody
}

func (o *UnblockUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UnblockUserResponse) GetObject() *UnblockUserResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
