// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type UpdateRecordFile struct {
	FileName string    `multipartForm:"name=fileName"`
	Content  io.Reader `multipartForm:"content"`
}

func (o *UpdateRecordFile) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *UpdateRecordFile) GetContent() io.Reader {
	if o == nil {
		return nil
	}
	return o.Content
}

// UpdateRecordRequestBody - Request payload
type UpdateRecordRequestBody struct {
	// New name for the record
	RecordName *string `multipartForm:"name=recordName"`
	// Replacement file content
	File *UpdateRecordFile `multipartForm:"file,name=file"`
}

func (o *UpdateRecordRequestBody) GetRecordName() *string {
	if o == nil {
		return nil
	}
	return o.RecordName
}

func (o *UpdateRecordRequestBody) GetFile() *UpdateRecordFile {
	if o == nil {
		return nil
	}
	return o.File
}

type UpdateRecordRequest struct {
	// Record ID
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
	// Request payload
	Body *UpdateRecordRequestBody `request:"mediaType=multipart/form-data"`
}

func (o *UpdateRecordRequest) GetRecordID() string {
	if o == nil {
		return ""
	}
	return o.RecordID
}

func (o *UpdateRecordRequest) GetBody() *UpdateRecordRequestBody {
	if o == nil {
		return nil
	}
	return o.Body
}

// UpdateRecordResponseBody - Record updated successfully
type UpdateRecordResponseBody struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
	// A record represents a single document, file, or content item within a knowledge base.
	// Records can originate from file uploads or external connectors (Google Drive, OneDrive, etc.).
	//
	Record *components.Record `json:"record,omitempty"`
}

func (o *UpdateRecordResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *UpdateRecordResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *UpdateRecordResponseBody) GetRecord() *components.Record {
	if o == nil {
		return nil
	}
	return o.Record
}

type UpdateRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Record updated successfully
	Object *UpdateRecordResponseBody
}

func (o *UpdateRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateRecordResponse) GetObject() *UpdateRecordResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
