// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// UpdateConversationTitleRequestBody - Request payload
type UpdateConversationTitleRequestBody struct {
	// New conversation title
	Title string `json:"title"`
}

func (o *UpdateConversationTitleRequestBody) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

type UpdateConversationTitleRequest struct {
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// Request payload
	Body UpdateConversationTitleRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateConversationTitleRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

func (o *UpdateConversationTitleRequest) GetBody() UpdateConversationTitleRequestBody {
	if o == nil {
		return UpdateConversationTitleRequestBody{}
	}
	return o.Body
}

type UpdateConversationTitleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Title updated successfully
	Conversation *components.Conversation
}

func (o *UpdateConversationTitleResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateConversationTitleResponse) GetConversation() *components.Conversation {
	if o == nil {
		return nil
	}
	return o.Conversation
}
