// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateConnectorConfigRequest struct {
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
	// Request payload
	Body components.UpdateConnectorConfigRequest `request:"mediaType=application/json"`
}

func (o *UpdateConnectorConfigRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *UpdateConnectorConfigRequest) GetBody() components.UpdateConnectorConfigRequest {
	if o == nil {
		return components.UpdateConnectorConfigRequest{}
	}
	return o.Body
}

// UpdateConnectorConfigResponseBody - Configuration updated
type UpdateConnectorConfigResponseBody struct {
	Success *bool `json:"success,omitempty"`
	// Configuration for a connector instance including auth, sync, and filter settings
	Config *components.ConnectorConfig `json:"config,omitempty"`
}

func (o *UpdateConnectorConfigResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *UpdateConnectorConfigResponseBody) GetConfig() *components.ConnectorConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

type UpdateConnectorConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Configuration updated
	Object *UpdateConnectorConfigResponseBody
}

func (o *UpdateConnectorConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateConnectorConfigResponse) GetObject() *UpdateConnectorConfigResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
