// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateConnectorNameRequest struct {
	// Unique connector instance ID
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
	// Request body for Update connector instance name
	Body components.UpdateConnectorNameRequest `request:"mediaType=application/json"`
}

func (o *UpdateConnectorNameRequest) GetConnectorID() string {
	if o == nil {
		return ""
	}
	return o.ConnectorID
}

func (o *UpdateConnectorNameRequest) GetBody() components.UpdateConnectorNameRequest {
	if o == nil {
		return components.UpdateConnectorNameRequest{}
	}
	return o.Body
}

// UpdateConnectorNameResponseBody - Name updated
type UpdateConnectorNameResponseBody struct {
	Success *bool `json:"success,omitempty"`
	// A configured connector instance. Represents an active or configured
	// connection to an external service.
	//
	Connector *components.ConnectorInstance `json:"connector,omitempty"`
}

func (o *UpdateConnectorNameResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *UpdateConnectorNameResponseBody) GetConnector() *components.ConnectorInstance {
	if o == nil {
		return nil
	}
	return o.Connector
}

type UpdateConnectorNameResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Name updated
	Object *UpdateConnectorNameResponseBody
}

func (o *UpdateConnectorNameResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateConnectorNameResponse) GetObject() *UpdateConnectorNameResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
