// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// UpdateUserRequestBody - Request payload
type UpdateUserRequestBody struct {
	// Full display name
	FullName *string `json:"fullName,omitempty"`
	// First name only
	FirstName *string `json:"firstName,omitempty"`
	// Last name only
	LastName *string `json:"lastName,omitempty"`
	// Email address (admin only)
	Email *string `json:"email,omitempty"`
	// Mobile phone with country code
	Mobile *string `json:"mobile,omitempty"`
	// Job title or role
	Designation *string             `json:"designation,omitempty"`
	Address     *components.Address `json:"address,omitempty"`
}

func (o *UpdateUserRequestBody) GetFullName() *string {
	if o == nil {
		return nil
	}
	return o.FullName
}

func (o *UpdateUserRequestBody) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *UpdateUserRequestBody) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *UpdateUserRequestBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateUserRequestBody) GetMobile() *string {
	if o == nil {
		return nil
	}
	return o.Mobile
}

func (o *UpdateUserRequestBody) GetDesignation() *string {
	if o == nil {
		return nil
	}
	return o.Designation
}

func (o *UpdateUserRequestBody) GetAddress() *components.Address {
	if o == nil {
		return nil
	}
	return o.Address
}

type UpdateUserRequest struct {
	// User ID (24-character MongoDB ObjectId)
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Request payload
	Body UpdateUserRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateUserRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateUserRequest) GetBody() UpdateUserRequestBody {
	if o == nil {
		return UpdateUserRequestBody{}
	}
	return o.Body
}

// UpdateUserResponseBody - User updated successfully
type UpdateUserResponseBody struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
	// User account in an organization
	Data *components.User `json:"data,omitempty"`
}

func (o *UpdateUserResponseBody) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *UpdateUserResponseBody) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *UpdateUserResponseBody) GetData() *components.User {
	if o == nil {
		return nil
	}
	return o.Data
}

type UpdateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User updated successfully
	Object *UpdateUserResponseBody
}

func (o *UpdateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateUserResponse) GetObject() *UpdateUserResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
