// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type UploadUserDisplayPictureFile struct {
	FileName string    `multipartForm:"name=fileName"`
	Content  io.Reader `multipartForm:"content"`
}

func (o *UploadUserDisplayPictureFile) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *UploadUserDisplayPictureFile) GetContent() io.Reader {
	if o == nil {
		return nil
	}
	return o.Content
}

// UploadUserDisplayPictureRequest - Request payload
type UploadUserDisplayPictureRequest struct {
	// Image file (PNG, JPEG, WebP, or GIF, max 1MB)
	File UploadUserDisplayPictureFile `multipartForm:"file,name=file"`
}

func (o *UploadUserDisplayPictureRequest) GetFile() UploadUserDisplayPictureFile {
	if o == nil {
		return UploadUserDisplayPictureFile{}
	}
	return o.File
}

type UploadUserDisplayPictureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Display picture uploaded
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (o *UploadUserDisplayPictureResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UploadUserDisplayPictureResponse) GetResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.ResponseStream
}
