// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type UploadRecordsToFolderFile struct {
	FileName string    `multipartForm:"name=fileName"`
	Content  io.Reader `multipartForm:"content"`
}

func (o *UploadRecordsToFolderFile) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}

func (o *UploadRecordsToFolderFile) GetContent() io.Reader {
	if o == nil {
		return nil
	}
	return o.Content
}

// UploadRecordsToFolderRequestBody - Request payload
type UploadRecordsToFolderRequestBody struct {
	Files []UploadRecordsToFolderFile `multipartForm:"file,name=files"`
	// JSON array with file metadata
	FilesMetadata *string `multipartForm:"name=files_metadata"`
	IsVersioned   *bool   `default:"true" multipartForm:"name=isVersioned"`
}

func (u UploadRecordsToFolderRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadRecordsToFolderRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"files"}); err != nil {
		return err
	}
	return nil
}

func (o *UploadRecordsToFolderRequestBody) GetFiles() []UploadRecordsToFolderFile {
	if o == nil {
		return []UploadRecordsToFolderFile{}
	}
	return o.Files
}

func (o *UploadRecordsToFolderRequestBody) GetFilesMetadata() *string {
	if o == nil {
		return nil
	}
	return o.FilesMetadata
}

func (o *UploadRecordsToFolderRequestBody) GetIsVersioned() *bool {
	if o == nil {
		return nil
	}
	return o.IsVersioned
}

type UploadRecordsToFolderRequest struct {
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Target folder ID
	FolderID string `pathParam:"style=simple,explode=false,name=folderId"`
	// Request payload
	Body UploadRecordsToFolderRequestBody `request:"mediaType=multipart/form-data"`
}

func (o *UploadRecordsToFolderRequest) GetKbID() string {
	if o == nil {
		return ""
	}
	return o.KbID
}

func (o *UploadRecordsToFolderRequest) GetFolderID() string {
	if o == nil {
		return ""
	}
	return o.FolderID
}

func (o *UploadRecordsToFolderRequest) GetBody() UploadRecordsToFolderRequestBody {
	if o == nil {
		return UploadRecordsToFolderRequestBody{}
	}
	return o.Body
}

type UploadRecordsToFolderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Files uploaded successfully
	UploadResult *components.UploadResult
}

func (o *UploadRecordsToFolderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UploadRecordsToFolderResponse) GetUploadResult() *components.UploadResult {
	if o == nil {
		return nil
	}
	return o.UploadResult
}
