/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ArchiveConversationRequest = {
  conversationId: string;
};

/** @internal */
export type ArchiveConversationRequest$Outbound = {
  conversationId: string;
};

/** @internal */
export const ArchiveConversationRequest$outboundSchema: z.ZodMiniType<
  ArchiveConversationRequest$Outbound,
  ArchiveConversationRequest
> = z.object({
  conversationId: z.string(),
});

export function archiveConversationRequestToJSON(
  archiveConversationRequest: ArchiveConversationRequest,
): string {
  return JSON.stringify(
    ArchiveConversationRequest$outboundSchema.parse(archiveConversationRequest),
  );
}
