/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Organization existence check completed
 */
export type CheckOrgExistsResponse = {
  /**
   * Whether an organization has been created
   */
  exists?: boolean | undefined;
};

/** @internal */
export const CheckOrgExistsResponse$inboundSchema: z.ZodMiniType<
  CheckOrgExistsResponse,
  unknown
> = z.object({
  exists: types.optional(types.boolean()),
});

export function checkOrgExistsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CheckOrgExistsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CheckOrgExistsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CheckOrgExistsResponse' from JSON`,
  );
}
