/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Type of organization account
 */
export const AccountType = {
  Individual: "individual",
  Business: "business",
} as const;
/**
 * Type of organization account
 */
export type AccountType = ClosedEnum<typeof AccountType>;

/**
 * Request payload
 */
export type CreateOrganizationRequest = {
  /**
   * Type of organization account
   */
  accountType: AccountType;
  /**
   * Short display name for the organization
   */
  shortName?: string | undefined;
  /**
   * Official registered name (for business accounts)
   */
  registeredName?: string | undefined;
  /**
   * Primary contact email (also used as admin email)
   */
  contactEmail: string;
  /**
   * Full name of the first admin user
   */
  adminFullName: string;
  /**
   * Password for the admin account (min 8 chars)
   */
  password: string;
};

export type CreateOrganizationData = {
  organization?: models.Organization | undefined;
  /**
   * User account in an organization
   */
  adminUser?: models.User | undefined;
  /**
   * JWT token for immediate login
   */
  accessToken?: string | undefined;
};

/**
 * Organization created successfully
 */
export type CreateOrganizationResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  data?: CreateOrganizationData | undefined;
};

/** @internal */
export const AccountType$outboundSchema: z.ZodMiniEnum<typeof AccountType> = z
  .enum(AccountType);

/** @internal */
export type CreateOrganizationRequest$Outbound = {
  accountType: string;
  shortName?: string | undefined;
  registeredName?: string | undefined;
  contactEmail: string;
  adminFullName: string;
  password: string;
};

/** @internal */
export const CreateOrganizationRequest$outboundSchema: z.ZodMiniType<
  CreateOrganizationRequest$Outbound,
  CreateOrganizationRequest
> = z.object({
  accountType: AccountType$outboundSchema,
  shortName: z.optional(z.string()),
  registeredName: z.optional(z.string()),
  contactEmail: z.string(),
  adminFullName: z.string(),
  password: z.string(),
});

export function createOrganizationRequestToJSON(
  createOrganizationRequest: CreateOrganizationRequest,
): string {
  return JSON.stringify(
    CreateOrganizationRequest$outboundSchema.parse(createOrganizationRequest),
  );
}

/** @internal */
export const CreateOrganizationData$inboundSchema: z.ZodMiniType<
  CreateOrganizationData,
  unknown
> = z.object({
  organization: types.optional(models.Organization$inboundSchema),
  adminUser: types.optional(models.User$inboundSchema),
  accessToken: types.optional(types.string()),
});

export function createOrganizationDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrganizationData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrganizationData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrganizationData' from JSON`,
  );
}

/** @internal */
export const CreateOrganizationResponse$inboundSchema: z.ZodMiniType<
  CreateOrganizationResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
  data: types.optional(z.lazy(() => CreateOrganizationData$inboundSchema)),
});

export function createOrganizationResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrganizationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrganizationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrganizationResponse' from JSON`,
  );
}
