/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Storage type identifier
 */
export const CreateAzureBlobStorageConfigStorageType = {
  AzureBlob: "azureBlob",
} as const;
/**
 * Storage type identifier
 */
export type CreateAzureBlobStorageConfigStorageType = ClosedEnum<
  typeof CreateAzureBlobStorageConfigStorageType
>;

/**
 * Request body for Configure Azure Blob Storage
 */
export type CreateAzureBlobStorageConfigRequest = {
  /**
   * Storage type identifier
   */
  storageType: CreateAzureBlobStorageConfigStorageType;
  /**
   * Azure Blob container name for storing files
   */
  containerName: string;
  /**
   * Full Azure Blob connection string. If provided, accountName and accountKey are not required.
   */
  azureBlobConnectionString?: string | undefined;
  /**
   * Azure storage account name. Required if not using connection string.
   */
  accountName?: string | undefined;
  /**
   * Azure storage account access key. Required if not using connection string.
   */
  accountKey?: string | undefined;
  /**
   * Protocol for Azure Blob endpoint
   */
  endpointProtocol?: string | undefined;
  /**
   * Azure endpoint suffix
   */
  endpointSuffix?: string | undefined;
};

/** @internal */
export const CreateAzureBlobStorageConfigStorageType$outboundSchema:
  z.ZodMiniEnum<typeof CreateAzureBlobStorageConfigStorageType> = z.enum(
    CreateAzureBlobStorageConfigStorageType,
  );

/** @internal */
export type CreateAzureBlobStorageConfigRequest$Outbound = {
  storageType: string;
  containerName: string;
  azureBlobConnectionString?: string | undefined;
  accountName?: string | undefined;
  accountKey?: string | undefined;
  endpointProtocol: string;
  endpointSuffix: string;
};

/** @internal */
export const CreateAzureBlobStorageConfigRequest$outboundSchema: z.ZodMiniType<
  CreateAzureBlobStorageConfigRequest$Outbound,
  CreateAzureBlobStorageConfigRequest
> = z.object({
  storageType: CreateAzureBlobStorageConfigStorageType$outboundSchema,
  containerName: z.string(),
  azureBlobConnectionString: z.optional(z.string()),
  accountName: z.optional(z.string()),
  accountKey: z.optional(z.string()),
  endpointProtocol: z._default(z.string(), "https"),
  endpointSuffix: z._default(z.string(), "core.windows.net"),
});

export function createAzureBlobStorageConfigRequestToJSON(
  createAzureBlobStorageConfigRequest: CreateAzureBlobStorageConfigRequest,
): string {
  return JSON.stringify(
    CreateAzureBlobStorageConfigRequest$outboundSchema.parse(
      createAzureBlobStorageConfigRequest,
    ),
  );
}
