/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Instance created
 */
export type CreateConnectorInstanceResponse = {
  success?: boolean | undefined;
  /**
   * A configured connector instance. Represents an active or configured
   *
   * @remarks
   * connection to an external service.
   */
  connector?: models.ConnectorInstance | undefined;
};

/** @internal */
export const CreateConnectorInstanceResponse$inboundSchema: z.ZodMiniType<
  CreateConnectorInstanceResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  connector: types.optional(models.ConnectorInstance$inboundSchema),
});

export function createConnectorInstanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateConnectorInstanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateConnectorInstanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateConnectorInstanceResponse' from JSON`,
  );
}
