/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request payload
 */
export type CreateKnowledgeBaseRequest = {
  /**
   * Name of the knowledge base
   */
  kbName: string;
};

/** @internal */
export type CreateKnowledgeBaseRequest$Outbound = {
  kbName: string;
};

/** @internal */
export const CreateKnowledgeBaseRequest$outboundSchema: z.ZodMiniType<
  CreateKnowledgeBaseRequest$Outbound,
  CreateKnowledgeBaseRequest
> = z.object({
  kbName: z.string(),
});

export function createKnowledgeBaseRequestToJSON(
  createKnowledgeBaseRequest: CreateKnowledgeBaseRequest,
): string {
  return JSON.stringify(
    CreateKnowledgeBaseRequest$outboundSchema.parse(createKnowledgeBaseRequest),
  );
}
