/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Organization auth configuration created successfully
 */
export type CreateOrgAuthConfigResponse = {
  message?: string | undefined;
  /**
   * Created organization ID
   */
  orgId?: string | undefined;
  /**
   * Created admin user ID
   */
  userId?: string | undefined;
};

/** @internal */
export const CreateOrgAuthConfigResponse$inboundSchema: z.ZodMiniType<
  CreateOrgAuthConfigResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  orgId: types.optional(types.string()),
  userId: types.optional(types.string()),
});

export function createOrgAuthConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateOrgAuthConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateOrgAuthConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateOrgAuthConfigResponse' from JSON`,
  );
}
