/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Request payload
 */
export type CreateTeamRequest = {
  /**
   * Team display name (must be unique in org)
   */
  name: string;
  /**
   * Team description and purpose
   */
  description?: string | undefined;
  /**
   * Optional initial members with roles
   */
  userRoles?: Array<models.UserRole> | undefined;
};

/**
 * Team created successfully
 */
export type CreateTeamResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  data?: models.Team | undefined;
};

/** @internal */
export type CreateTeamRequest$Outbound = {
  name: string;
  description?: string | undefined;
  userRoles?: Array<models.UserRole$Outbound> | undefined;
};

/** @internal */
export const CreateTeamRequest$outboundSchema: z.ZodMiniType<
  CreateTeamRequest$Outbound,
  CreateTeamRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  userRoles: z.optional(z.array(models.UserRole$outboundSchema)),
});

export function createTeamRequestToJSON(
  createTeamRequest: CreateTeamRequest,
): string {
  return JSON.stringify(
    CreateTeamRequest$outboundSchema.parse(createTeamRequest),
  );
}

/** @internal */
export const CreateTeamResponse$inboundSchema: z.ZodMiniType<
  CreateTeamResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
  data: types.optional(models.Team$inboundSchema),
});

export function createTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTeamResponse' from JSON`,
  );
}
