/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const CreateDocumentPlaceholderPermissions = {
  Owner: "owner",
  Editor: "editor",
  Commentator: "commentator",
  Readonly: "readonly",
} as const;
export type CreateDocumentPlaceholderPermissions = ClosedEnum<
  typeof CreateDocumentPlaceholderPermissions
>;

/**
 * Custom metadata key-value pairs
 */
export type MetaData = {};

/**
 * Request payload
 */
export type CreateDocumentPlaceholderRequest = {
  /**
   * Display name for the document
   */
  documentName: string;
  /**
   * Alternative name for search/display
   */
  alternateDocumentName?: string | undefined;
  /**
   * Virtual folder path
   */
  documentPath: string;
  permissions?: CreateDocumentPlaceholderPermissions | undefined;
  /**
   * Custom metadata key-value pairs
   */
  metaData?: MetaData | undefined;
  /**
   * Enable version control
   */
  isVersionedFile?: boolean | undefined;
  /**
   * File extension WITHOUT dot
   */
  extension: string;
};

/** @internal */
export const CreateDocumentPlaceholderPermissions$outboundSchema: z.ZodMiniEnum<
  typeof CreateDocumentPlaceholderPermissions
> = z.enum(CreateDocumentPlaceholderPermissions);

/** @internal */
export type MetaData$Outbound = {};

/** @internal */
export const MetaData$outboundSchema: z.ZodMiniType<
  MetaData$Outbound,
  MetaData
> = z.object({});

export function metaDataToJSON(metaData: MetaData): string {
  return JSON.stringify(MetaData$outboundSchema.parse(metaData));
}

/** @internal */
export type CreateDocumentPlaceholderRequest$Outbound = {
  documentName: string;
  alternateDocumentName?: string | undefined;
  documentPath: string;
  permissions: string;
  metaData?: MetaData$Outbound | undefined;
  isVersionedFile: boolean;
  extension: string;
};

/** @internal */
export const CreateDocumentPlaceholderRequest$outboundSchema: z.ZodMiniType<
  CreateDocumentPlaceholderRequest$Outbound,
  CreateDocumentPlaceholderRequest
> = z.object({
  documentName: z.string(),
  alternateDocumentName: z.optional(z.string()),
  documentPath: z.string(),
  permissions: z._default(
    CreateDocumentPlaceholderPermissions$outboundSchema,
    "owner",
  ),
  metaData: z.optional(z.lazy(() => MetaData$outboundSchema)),
  isVersionedFile: z._default(z.boolean(), false),
  extension: z.string(),
});

export function createDocumentPlaceholderRequestToJSON(
  createDocumentPlaceholderRequest: CreateDocumentPlaceholderRequest,
): string {
  return JSON.stringify(
    CreateDocumentPlaceholderRequest$outboundSchema.parse(
      createDocumentPlaceholderRequest,
    ),
  );
}
