/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request payload
 */
export type CreateRootFolderRequestBody = {
  /**
   * Name of the folder
   */
  folderName: string;
};

export type CreateRootFolderRequest = {
  /**
   * Knowledge base ID
   */
  kbId: string;
  /**
   * Request payload
   */
  body: CreateRootFolderRequestBody;
};

/** @internal */
export type CreateRootFolderRequestBody$Outbound = {
  folderName: string;
};

/** @internal */
export const CreateRootFolderRequestBody$outboundSchema: z.ZodMiniType<
  CreateRootFolderRequestBody$Outbound,
  CreateRootFolderRequestBody
> = z.object({
  folderName: z.string(),
});

export function createRootFolderRequestBodyToJSON(
  createRootFolderRequestBody: CreateRootFolderRequestBody,
): string {
  return JSON.stringify(
    CreateRootFolderRequestBody$outboundSchema.parse(
      createRootFolderRequestBody,
    ),
  );
}

/** @internal */
export type CreateRootFolderRequest$Outbound = {
  kbId: string;
  body: CreateRootFolderRequestBody$Outbound;
};

/** @internal */
export const CreateRootFolderRequest$outboundSchema: z.ZodMiniType<
  CreateRootFolderRequest$Outbound,
  CreateRootFolderRequest
> = z.object({
  kbId: z.string(),
  body: z.lazy(() => CreateRootFolderRequestBody$outboundSchema),
});

export function createRootFolderRequestToJSON(
  createRootFolderRequest: CreateRootFolderRequest,
): string {
  return JSON.stringify(
    CreateRootFolderRequest$outboundSchema.parse(createRootFolderRequest),
  );
}
