/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Group type determining behavior and privileges
 */
export const CreateUserGroupType = {
  Admin: "admin",
  Standard: "standard",
  Everyone: "everyone",
  Custom: "custom",
} as const;
/**
 * Group type determining behavior and privileges
 */
export type CreateUserGroupType = ClosedEnum<typeof CreateUserGroupType>;

/**
 * Request payload
 */
export type CreateUserGroupRequest = {
  /**
   * Display name for the group
   */
  name: string;
  /**
   * Group type determining behavior and privileges
   */
  type: CreateUserGroupType;
  /**
   * Optional description of the group's purpose
   */
  description?: string | undefined;
};

/** @internal */
export const CreateUserGroupType$outboundSchema: z.ZodMiniEnum<
  typeof CreateUserGroupType
> = z.enum(CreateUserGroupType);

/** @internal */
export type CreateUserGroupRequest$Outbound = {
  name: string;
  type: string;
  description?: string | undefined;
};

/** @internal */
export const CreateUserGroupRequest$outboundSchema: z.ZodMiniType<
  CreateUserGroupRequest$Outbound,
  CreateUserGroupRequest
> = z.object({
  name: z.string(),
  type: CreateUserGroupType$outboundSchema,
  description: z.optional(z.string()),
});

export function createUserGroupRequestToJSON(
  createUserGroupRequest: CreateUserGroupRequest,
): string {
  return JSON.stringify(
    CreateUserGroupRequest$outboundSchema.parse(createUserGroupRequest),
  );
}
