/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * JSON Schema for customization
 */
export type CreateAgentTemplateConfigSchema = {};

/**
 * Request payload
 */
export type CreateAgentTemplateRequest = {
  /**
   * Template name
   */
  name: string;
  /**
   * What agents from this template do
   */
  description?: string | undefined;
  /**
   * Template category
   */
  category?: string | undefined;
  /**
   * Default system instructions
   */
  defaultSystemPrompt?: string | undefined;
  /**
   * Suggested tool keys
   */
  recommendedTools?: Array<string> | undefined;
  /**
   * JSON Schema for customization
   */
  configSchema?: CreateAgentTemplateConfigSchema | undefined;
  /**
   * Make template available organization-wide
   */
  isPublic?: boolean | undefined;
};

/** @internal */
export type CreateAgentTemplateConfigSchema$Outbound = {};

/** @internal */
export const CreateAgentTemplateConfigSchema$outboundSchema: z.ZodMiniType<
  CreateAgentTemplateConfigSchema$Outbound,
  CreateAgentTemplateConfigSchema
> = z.object({});

export function createAgentTemplateConfigSchemaToJSON(
  createAgentTemplateConfigSchema: CreateAgentTemplateConfigSchema,
): string {
  return JSON.stringify(
    CreateAgentTemplateConfigSchema$outboundSchema.parse(
      createAgentTemplateConfigSchema,
    ),
  );
}

/** @internal */
export type CreateAgentTemplateRequest$Outbound = {
  name: string;
  description?: string | undefined;
  category?: string | undefined;
  defaultSystemPrompt?: string | undefined;
  recommendedTools?: Array<string> | undefined;
  configSchema?: CreateAgentTemplateConfigSchema$Outbound | undefined;
  isPublic: boolean;
};

/** @internal */
export const CreateAgentTemplateRequest$outboundSchema: z.ZodMiniType<
  CreateAgentTemplateRequest$Outbound,
  CreateAgentTemplateRequest
> = z.object({
  name: z.string(),
  description: z.optional(z.string()),
  category: z.optional(z.string()),
  defaultSystemPrompt: z.optional(z.string()),
  recommendedTools: z.optional(z.array(z.string())),
  configSchema: z.optional(
    z.lazy(() => CreateAgentTemplateConfigSchema$outboundSchema),
  ),
  isPublic: z._default(z.boolean(), false),
});

export function createAgentTemplateRequestToJSON(
  createAgentTemplateRequest: CreateAgentTemplateRequest,
): string {
  return JSON.stringify(
    CreateAgentTemplateRequest$outboundSchema.parse(createAgentTemplateRequest),
  );
}
