/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteUserRequest = {
  /**
   * User ID (24-character MongoDB ObjectId)
   */
  id: string;
};

export type DeletedUser = {
  id?: string | undefined;
  fullName?: string | undefined;
  email?: string | undefined;
};

/**
 * User deleted successfully
 */
export type DeleteUserResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  deletedUser?: DeletedUser | undefined;
};

/** @internal */
export type DeleteUserRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteUserRequest$outboundSchema: z.ZodMiniType<
  DeleteUserRequest$Outbound,
  DeleteUserRequest
> = z.object({
  id: z.string(),
});

export function deleteUserRequestToJSON(
  deleteUserRequest: DeleteUserRequest,
): string {
  return JSON.stringify(
    DeleteUserRequest$outboundSchema.parse(deleteUserRequest),
  );
}

/** @internal */
export const DeletedUser$inboundSchema: z.ZodMiniType<DeletedUser, unknown> = z
  .pipe(
    z.object({
      _id: types.optional(types.string()),
      fullName: types.optional(types.string()),
      email: types.optional(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "_id": "id",
      });
    }),
  );

export function deletedUserFromJSON(
  jsonString: string,
): SafeParseResult<DeletedUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletedUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletedUser' from JSON`,
  );
}

/** @internal */
export const DeleteUserResponse$inboundSchema: z.ZodMiniType<
  DeleteUserResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
  deletedUser: types.optional(z.lazy(() => DeletedUser$inboundSchema)),
});

export function deleteUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteUserResponse' from JSON`,
  );
}
