/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteConversationByIdRequest = {
  /**
   * Unique conversation identifier
   */
  conversationId: string;
};

/**
 * Conversation deleted successfully
 */
export type DeleteConversationByIdResponse = {
  message?: string | undefined;
};

/** @internal */
export type DeleteConversationByIdRequest$Outbound = {
  conversationId: string;
};

/** @internal */
export const DeleteConversationByIdRequest$outboundSchema: z.ZodMiniType<
  DeleteConversationByIdRequest$Outbound,
  DeleteConversationByIdRequest
> = z.object({
  conversationId: z.string(),
});

export function deleteConversationByIdRequestToJSON(
  deleteConversationByIdRequest: DeleteConversationByIdRequest,
): string {
  return JSON.stringify(
    DeleteConversationByIdRequest$outboundSchema.parse(
      deleteConversationByIdRequest,
    ),
  );
}

/** @internal */
export const DeleteConversationByIdResponse$inboundSchema: z.ZodMiniType<
  DeleteConversationByIdResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function deleteConversationByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteConversationByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteConversationByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteConversationByIdResponse' from JSON`,
  );
}
