/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const DoclingCreateBlocksServerList = [
  /**
   * Docling Service (Internal)
   */
  "http://localhost:8081",
] as const;

/**
 * Request payload
 */
export type DoclingCreateBlocksRequest = {
  /**
   * JSON-encoded DoclingDocument from /parse-pdf
   */
  parseResult: string;
  /**
   * Optional - process specific page only
   */
  pageNumber?: number | undefined;
};

/**
 * Extracted content blocks
 */
export type DoclingCreateBlocksBlockContainers = {};

/**
 * Blocks created successfully
 */
export type DoclingCreateBlocksResponse = {
  success?: boolean | undefined;
  /**
   * Extracted content blocks
   */
  blockContainers?: DoclingCreateBlocksBlockContainers | undefined;
};

/** @internal */
export type DoclingCreateBlocksRequest$Outbound = {
  parse_result: string;
  page_number?: number | undefined;
};

/** @internal */
export const DoclingCreateBlocksRequest$outboundSchema: z.ZodMiniType<
  DoclingCreateBlocksRequest$Outbound,
  DoclingCreateBlocksRequest
> = z.pipe(
  z.object({
    parseResult: z.string(),
    pageNumber: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      parseResult: "parse_result",
      pageNumber: "page_number",
    });
  }),
);

export function doclingCreateBlocksRequestToJSON(
  doclingCreateBlocksRequest: DoclingCreateBlocksRequest,
): string {
  return JSON.stringify(
    DoclingCreateBlocksRequest$outboundSchema.parse(doclingCreateBlocksRequest),
  );
}

/** @internal */
export const DoclingCreateBlocksBlockContainers$inboundSchema: z.ZodMiniType<
  DoclingCreateBlocksBlockContainers,
  unknown
> = z.object({});

export function doclingCreateBlocksBlockContainersFromJSON(
  jsonString: string,
): SafeParseResult<DoclingCreateBlocksBlockContainers, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DoclingCreateBlocksBlockContainers$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DoclingCreateBlocksBlockContainers' from JSON`,
  );
}

/** @internal */
export const DoclingCreateBlocksResponse$inboundSchema: z.ZodMiniType<
  DoclingCreateBlocksResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    block_containers: types.optional(
      z.lazy(() => DoclingCreateBlocksBlockContainers$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "block_containers": "blockContainers",
    });
  }),
);

export function doclingCreateBlocksResponseFromJSON(
  jsonString: string,
): SafeParseResult<DoclingCreateBlocksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DoclingCreateBlocksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DoclingCreateBlocksResponse' from JSON`,
  );
}
