/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export const DriveWebhookServerList = [
  /**
   * Connector Service (Internal)
   */
  "http://localhost:8088",
] as const;
