/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCurrentUserTeamsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
};

/** @internal */
export type GetCurrentUserTeamsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
};

/** @internal */
export const GetCurrentUserTeamsRequest$outboundSchema: z.ZodMiniType<
  GetCurrentUserTeamsRequest$Outbound,
  GetCurrentUserTeamsRequest
> = z.object({
  page: z.optional(z.int()),
  limit: z.optional(z.int()),
  search: z.optional(z.string()),
});

export function getCurrentUserTeamsRequestToJSON(
  getCurrentUserTeamsRequest: GetCurrentUserTeamsRequest,
): string {
  return JSON.stringify(
    GetCurrentUserTeamsRequest$outboundSchema.parse(getCurrentUserTeamsRequest),
  );
}
