/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetConnectorStatsRequest = {
  /**
   * Connector ID
   */
  connectorId: string;
};

/** @internal */
export type GetConnectorStatsRequest$Outbound = {
  connectorId: string;
};

/** @internal */
export const GetConnectorStatsRequest$outboundSchema: z.ZodMiniType<
  GetConnectorStatsRequest$Outbound,
  GetConnectorStatsRequest
> = z.object({
  connectorId: z.string(),
});

export function getConnectorStatsRequestToJSON(
  getConnectorStatsRequest: GetConnectorStatsRequest,
): string {
  return JSON.stringify(
    GetConnectorStatsRequest$outboundSchema.parse(getConnectorStatsRequest),
  );
}
