/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Upload limits retrieved
 */
export type GetUploadLimitsResponse = {
  /**
   * Maximum number of files per upload request
   */
  maxFilesPerRequest?: number | undefined;
  /**
   * Maximum file size in bytes (default 30MB)
   */
  maxFileSizeBytes?: number | undefined;
};

/** @internal */
export const GetUploadLimitsResponse$inboundSchema: z.ZodMiniType<
  GetUploadLimitsResponse,
  unknown
> = z.object({
  maxFilesPerRequest: types.optional(types.number()),
  maxFileSizeBytes: types.optional(types.number()),
});

export function getUploadLimitsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUploadLimitsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUploadLimitsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUploadLimitsResponse' from JSON`,
  );
}
