/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetDocumentBufferRequest = {
  /**
   * Document ID (24-character MongoDB ObjectId)
   */
  documentId: string;
  /**
   * Version number to retrieve (0-indexed)
   */
  version?: number | undefined;
};

/** @internal */
export type GetDocumentBufferRequest$Outbound = {
  documentId: string;
  version?: number | undefined;
};

/** @internal */
export const GetDocumentBufferRequest$outboundSchema: z.ZodMiniType<
  GetDocumentBufferRequest$Outbound,
  GetDocumentBufferRequest
> = z.object({
  documentId: z.string(),
  version: z.optional(z.int()),
});

export function getDocumentBufferRequestToJSON(
  getDocumentBufferRequest: GetDocumentBufferRequest,
): string {
  return JSON.stringify(
    GetDocumentBufferRequest$outboundSchema.parse(getDocumentBufferRequest),
  );
}
