/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetConnectorInstanceRequest = {
  /**
   * Connector instance ID
   */
  connectorId: string;
};

/**
 * Instance retrieved
 */
export type GetConnectorInstanceResponse = {
  success?: boolean | undefined;
  /**
   * A configured connector instance. Represents an active or configured
   *
   * @remarks
   * connection to an external service.
   */
  connector?: models.ConnectorInstance | undefined;
};

/** @internal */
export type GetConnectorInstanceRequest$Outbound = {
  connectorId: string;
};

/** @internal */
export const GetConnectorInstanceRequest$outboundSchema: z.ZodMiniType<
  GetConnectorInstanceRequest$Outbound,
  GetConnectorInstanceRequest
> = z.object({
  connectorId: z.string(),
});

export function getConnectorInstanceRequestToJSON(
  getConnectorInstanceRequest: GetConnectorInstanceRequest,
): string {
  return JSON.stringify(
    GetConnectorInstanceRequest$outboundSchema.parse(
      getConnectorInstanceRequest,
    ),
  );
}

/** @internal */
export const GetConnectorInstanceResponse$inboundSchema: z.ZodMiniType<
  GetConnectorInstanceResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  connector: types.optional(models.ConnectorInstance$inboundSchema),
});

export function getConnectorInstanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetConnectorInstanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetConnectorInstanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetConnectorInstanceResponse' from JSON`,
  );
}
