/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetInternalUserSecurity = {
  scopedToken: string;
};

export type GetInternalUserRequest = {
  /**
   * User ID (24-character MongoDB ObjectId)
   */
  id: string;
};

/**
 * User retrieved successfully
 */
export type GetInternalUserResponse = {
  success?: boolean | undefined;
  /**
   * User account in an organization
   */
  data?: models.User | undefined;
};

/** @internal */
export type GetInternalUserSecurity$Outbound = {
  scopedToken: string;
};

/** @internal */
export const GetInternalUserSecurity$outboundSchema: z.ZodMiniType<
  GetInternalUserSecurity$Outbound,
  GetInternalUserSecurity
> = z.object({
  scopedToken: z.string(),
});

export function getInternalUserSecurityToJSON(
  getInternalUserSecurity: GetInternalUserSecurity,
): string {
  return JSON.stringify(
    GetInternalUserSecurity$outboundSchema.parse(getInternalUserSecurity),
  );
}

/** @internal */
export type GetInternalUserRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetInternalUserRequest$outboundSchema: z.ZodMiniType<
  GetInternalUserRequest$Outbound,
  GetInternalUserRequest
> = z.object({
  id: z.string(),
});

export function getInternalUserRequestToJSON(
  getInternalUserRequest: GetInternalUserRequest,
): string {
  return JSON.stringify(
    GetInternalUserRequest$outboundSchema.parse(getInternalUserRequest),
  );
}

/** @internal */
export const GetInternalUserResponse$inboundSchema: z.ZodMiniType<
  GetInternalUserResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.User$inboundSchema),
});

export function getInternalUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetInternalUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInternalUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInternalUserResponse' from JSON`,
  );
}
