/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetDocumentByIdRequest = {
  /**
   * Document ID (24-character MongoDB ObjectId)
   */
  documentId: string;
};

/**
 * Document details retrieved successfully
 */
export type GetDocumentByIdResponse = {
  success?: boolean | undefined;
  /**
   * Represents a document stored in PipesHub storage system. Documents can be versioned to maintain complete history of changes. Supports multiple storage backends (S3, Azure Blob, Local).
   *
   * @remarks
   */
  data?: models.Document | undefined;
};

/** @internal */
export type GetDocumentByIdRequest$Outbound = {
  documentId: string;
};

/** @internal */
export const GetDocumentByIdRequest$outboundSchema: z.ZodMiniType<
  GetDocumentByIdRequest$Outbound,
  GetDocumentByIdRequest
> = z.object({
  documentId: z.string(),
});

export function getDocumentByIdRequestToJSON(
  getDocumentByIdRequest: GetDocumentByIdRequest,
): string {
  return JSON.stringify(
    GetDocumentByIdRequest$outboundSchema.parse(getDocumentByIdRequest),
  );
}

/** @internal */
export const GetDocumentByIdResponse$inboundSchema: z.ZodMiniType<
  GetDocumentByIdResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(models.Document$inboundSchema),
});

export function getDocumentByIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDocumentByIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDocumentByIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDocumentByIdResponse' from JSON`,
  );
}
