/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetDirectUploadUrlRequest = {
  /**
   * Document ID from placeholder creation
   */
  documentId: string;
};

/**
 * Direct upload URL generated successfully
 */
export type GetDirectUploadUrlResponse = {
  success?: boolean | undefined;
  /**
   * Presigned URL for direct PUT upload
   */
  signedUrl?: string | undefined;
  /**
   * Document ID for reference
   */
  documentId?: string | undefined;
};

/** @internal */
export type GetDirectUploadUrlRequest$Outbound = {
  documentId: string;
};

/** @internal */
export const GetDirectUploadUrlRequest$outboundSchema: z.ZodMiniType<
  GetDirectUploadUrlRequest$Outbound,
  GetDirectUploadUrlRequest
> = z.object({
  documentId: z.string(),
});

export function getDirectUploadUrlRequestToJSON(
  getDirectUploadUrlRequest: GetDirectUploadUrlRequest,
): string {
  return JSON.stringify(
    GetDirectUploadUrlRequest$outboundSchema.parse(getDirectUploadUrlRequest),
  );
}

/** @internal */
export const GetDirectUploadUrlResponse$inboundSchema: z.ZodMiniType<
  GetDirectUploadUrlResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  signedUrl: types.optional(types.string()),
  documentId: types.optional(types.string()),
});

export function getDirectUploadUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDirectUploadUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDirectUploadUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDirectUploadUrlResponse' from JSON`,
  );
}
