/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetUsersInGroupRequest = {
  /**
   * Unique identifier of the user group
   */
  groupId: string;
  /**
   * Page number for pagination (1-based)
   */
  page?: number | undefined;
  /**
   * Number of users per page
   */
  limit?: number | undefined;
};

export type GetUsersInGroupPagination = {
  page?: number | undefined;
  limit?: number | undefined;
  total?: number | undefined;
  totalPages?: number | undefined;
};

/**
 * Users in group retrieved successfully
 */
export type GetUsersInGroupResponse = {
  success?: boolean | undefined;
  data?: Array<models.User> | undefined;
  pagination?: GetUsersInGroupPagination | undefined;
};

/** @internal */
export type GetUsersInGroupRequest$Outbound = {
  groupId: string;
  page: number;
  limit: number;
};

/** @internal */
export const GetUsersInGroupRequest$outboundSchema: z.ZodMiniType<
  GetUsersInGroupRequest$Outbound,
  GetUsersInGroupRequest
> = z.object({
  groupId: z.string(),
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 20),
});

export function getUsersInGroupRequestToJSON(
  getUsersInGroupRequest: GetUsersInGroupRequest,
): string {
  return JSON.stringify(
    GetUsersInGroupRequest$outboundSchema.parse(getUsersInGroupRequest),
  );
}

/** @internal */
export const GetUsersInGroupPagination$inboundSchema: z.ZodMiniType<
  GetUsersInGroupPagination,
  unknown
> = z.object({
  page: types.optional(types.number()),
  limit: types.optional(types.number()),
  total: types.optional(types.number()),
  totalPages: types.optional(types.number()),
});

export function getUsersInGroupPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetUsersInGroupPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsersInGroupPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsersInGroupPagination' from JSON`,
  );
}

/** @internal */
export const GetUsersInGroupResponse$inboundSchema: z.ZodMiniType<
  GetUsersInGroupResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  data: types.optional(z.array(models.User$inboundSchema)),
  pagination: types.optional(
    z.lazy(() => GetUsersInGroupPagination$inboundSchema),
  ),
});

export function getUsersInGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUsersInGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsersInGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsersInGroupResponse' from JSON`,
  );
}
