/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListConfiguredConnectorsRequest = {
  /**
   * Scope determines visibility and access control for connectors:<br>
   *
   * @remarks
   * <ul>
   * <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
   * <li><code>personal</code> - Private to the creating user only</li>
   * </ul>
   */
  scope?: models.ConnectorScope | undefined;
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
};

/**
 * Configured connectors retrieved
 */
export type ListConfiguredConnectorsResponse = {
  success?: boolean | undefined;
  connectors?: Array<models.ConnectorInstance> | undefined;
  /**
   * Pagination information for connector lists
   */
  pagination?: models.ConnectorPagination | undefined;
};

/** @internal */
export type ListConfiguredConnectorsRequest$Outbound = {
  scope?: string | undefined;
  page: number;
  limit: number;
  search?: string | undefined;
};

/** @internal */
export const ListConfiguredConnectorsRequest$outboundSchema: z.ZodMiniType<
  ListConfiguredConnectorsRequest$Outbound,
  ListConfiguredConnectorsRequest
> = z.object({
  scope: z.optional(models.ConnectorScope$outboundSchema),
  page: z._default(z.int(), 1),
  limit: z._default(z.int(), 20),
  search: z.optional(z.string()),
});

export function listConfiguredConnectorsRequestToJSON(
  listConfiguredConnectorsRequest: ListConfiguredConnectorsRequest,
): string {
  return JSON.stringify(
    ListConfiguredConnectorsRequest$outboundSchema.parse(
      listConfiguredConnectorsRequest,
    ),
  );
}

/** @internal */
export const ListConfiguredConnectorsResponse$inboundSchema: z.ZodMiniType<
  ListConfiguredConnectorsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  connectors: types.optional(z.array(models.ConnectorInstance$inboundSchema)),
  pagination: types.optional(models.ConnectorPagination$inboundSchema),
});

export function listConfiguredConnectorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListConfiguredConnectorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListConfiguredConnectorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListConfiguredConnectorsResponse' from JSON`,
  );
}
