/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Scope = {
  name?: string | undefined;
  description?: string | undefined;
  category?: string | undefined;
  requiresUserConsent?: boolean | undefined;
};

/**
 * List of available scopes
 */
export type ListOAuthScopesResponse = {
  /**
   * Scopes grouped by category
   */
  scopes?: { [k: string]: Array<Scope> } | undefined;
};

/** @internal */
export const Scope$inboundSchema: z.ZodMiniType<Scope, unknown> = z.object({
  name: types.optional(types.string()),
  description: types.optional(types.string()),
  category: types.optional(types.string()),
  requiresUserConsent: types.optional(types.boolean()),
});

export function scopeFromJSON(
  jsonString: string,
): SafeParseResult<Scope, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Scope$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Scope' from JSON`,
  );
}

/** @internal */
export const ListOAuthScopesResponse$inboundSchema: z.ZodMiniType<
  ListOAuthScopesResponse,
  unknown
> = z.object({
  scopes: types.optional(
    z.record(z.string(), z.array(z.lazy(() => Scope$inboundSchema))),
  ),
});

export function listOAuthScopesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListOAuthScopesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListOAuthScopesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListOAuthScopesResponse' from JSON`,
  );
}
