/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export const QueryServiceChatStreamServerList = [
  /**
   * Query Service (Internal)
   */
  "http://localhost:8000",
] as const;
