/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

/**
 * Request payload
 */
export type RegenerateAgentAnswerRequestBody = {
  filters?: models.Filters | undefined;
  modelKey?: string | undefined;
  chatMode?: string | undefined;
};

export type RegenerateAgentAnswerRequest = {
  agentKey: string;
  conversationId: string;
  messageId: string;
  /**
   * Request payload
   */
  body?: RegenerateAgentAnswerRequestBody | undefined;
};

/** @internal */
export type RegenerateAgentAnswerRequestBody$Outbound = {
  filters?: models.Filters$Outbound | undefined;
  modelKey?: string | undefined;
  chatMode?: string | undefined;
};

/** @internal */
export const RegenerateAgentAnswerRequestBody$outboundSchema: z.ZodMiniType<
  RegenerateAgentAnswerRequestBody$Outbound,
  RegenerateAgentAnswerRequestBody
> = z.object({
  filters: z.optional(models.Filters$outboundSchema),
  modelKey: z.optional(z.string()),
  chatMode: z.optional(z.string()),
});

export function regenerateAgentAnswerRequestBodyToJSON(
  regenerateAgentAnswerRequestBody: RegenerateAgentAnswerRequestBody,
): string {
  return JSON.stringify(
    RegenerateAgentAnswerRequestBody$outboundSchema.parse(
      regenerateAgentAnswerRequestBody,
    ),
  );
}

/** @internal */
export type RegenerateAgentAnswerRequest$Outbound = {
  agentKey: string;
  conversationId: string;
  messageId: string;
  body?: RegenerateAgentAnswerRequestBody$Outbound | undefined;
};

/** @internal */
export const RegenerateAgentAnswerRequest$outboundSchema: z.ZodMiniType<
  RegenerateAgentAnswerRequest$Outbound,
  RegenerateAgentAnswerRequest
> = z.object({
  agentKey: z.string(),
  conversationId: z.string(),
  messageId: z.string(),
  body: z.optional(
    z.lazy(() => RegenerateAgentAnswerRequestBody$outboundSchema),
  ),
});

export function regenerateAgentAnswerRequestToJSON(
  regenerateAgentAnswerRequest: RegenerateAgentAnswerRequest,
): string {
  return JSON.stringify(
    RegenerateAgentAnswerRequest$outboundSchema.parse(
      regenerateAgentAnswerRequest,
    ),
  );
}
