/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RegenerateOAuthAppSecretRequest = {
  /**
   * OAuth app ID
   */
  appId: string;
};

/** @internal */
export type RegenerateOAuthAppSecretRequest$Outbound = {
  appId: string;
};

/** @internal */
export const RegenerateOAuthAppSecretRequest$outboundSchema: z.ZodMiniType<
  RegenerateOAuthAppSecretRequest$Outbound,
  RegenerateOAuthAppSecretRequest
> = z.object({
  appId: z.string(),
});

export function regenerateOAuthAppSecretRequestToJSON(
  regenerateOAuthAppSecretRequest: RegenerateOAuthAppSecretRequest,
): string {
  return JSON.stringify(
    RegenerateOAuthAppSecretRequest$outboundSchema.parse(
      regenerateOAuthAppSecretRequest,
    ),
  );
}
