/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request body for Reindex failed connector records
 */
export type ReindexFailedConnectorRecordsRequest = {
  /**
   * Connector app name
   */
  app: string;
  /**
   * Connector instance ID
   */
  connectorId: string;
};

/** @internal */
export type ReindexFailedConnectorRecordsRequest$Outbound = {
  app: string;
  connectorId: string;
};

/** @internal */
export const ReindexFailedConnectorRecordsRequest$outboundSchema: z.ZodMiniType<
  ReindexFailedConnectorRecordsRequest$Outbound,
  ReindexFailedConnectorRecordsRequest
> = z.object({
  app: z.string(),
  connectorId: z.string(),
});

export function reindexFailedConnectorRecordsRequestToJSON(
  reindexFailedConnectorRecordsRequest: ReindexFailedConnectorRecordsRequest,
): string {
  return JSON.stringify(
    ReindexFailedConnectorRecordsRequest$outboundSchema.parse(
      reindexFailedConnectorRecordsRequest,
    ),
  );
}
