/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ResumeCrawlingJobRequest = {
  /**
   * Connector type identifier
   */
  connector: string;
  /**
   * Unique identifier of the connector instance
   */
  connectorId: string;
};

export type ResumeCrawlingJobData = {
  connector?: string | undefined;
  orgId?: string | undefined;
  resumedAt?: Date | undefined;
};

/**
 * Crawling job resumed successfully
 */
export type ResumeCrawlingJobResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  data?: ResumeCrawlingJobData | undefined;
};

/** @internal */
export type ResumeCrawlingJobRequest$Outbound = {
  connector: string;
  connectorId: string;
};

/** @internal */
export const ResumeCrawlingJobRequest$outboundSchema: z.ZodMiniType<
  ResumeCrawlingJobRequest$Outbound,
  ResumeCrawlingJobRequest
> = z.object({
  connector: z.string(),
  connectorId: z.string(),
});

export function resumeCrawlingJobRequestToJSON(
  resumeCrawlingJobRequest: ResumeCrawlingJobRequest,
): string {
  return JSON.stringify(
    ResumeCrawlingJobRequest$outboundSchema.parse(resumeCrawlingJobRequest),
  );
}

/** @internal */
export const ResumeCrawlingJobData$inboundSchema: z.ZodMiniType<
  ResumeCrawlingJobData,
  unknown
> = z.object({
  connector: types.optional(types.string()),
  orgId: types.optional(types.string()),
  resumedAt: types.optional(types.date()),
});

export function resumeCrawlingJobDataFromJSON(
  jsonString: string,
): SafeParseResult<ResumeCrawlingJobData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResumeCrawlingJobData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResumeCrawlingJobData' from JSON`,
  );
}

/** @internal */
export const ResumeCrawlingJobResponse$inboundSchema: z.ZodMiniType<
  ResumeCrawlingJobResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
  data: types.optional(z.lazy(() => ResumeCrawlingJobData$inboundSchema)),
});

export function resumeCrawlingJobResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResumeCrawlingJobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResumeCrawlingJobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResumeCrawlingJobResponse' from JSON`,
  );
}
