/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request body for Resync connector
 */
export type ResyncConnectorRequest = {
  /**
   * Connector type name
   */
  connectorName: string;
  /**
   * Connector instance ID
   */
  connectorId: string;
};

/** @internal */
export type ResyncConnectorRequest$Outbound = {
  connectorName: string;
  connectorId: string;
};

/** @internal */
export const ResyncConnectorRequest$outboundSchema: z.ZodMiniType<
  ResyncConnectorRequest$Outbound,
  ResyncConnectorRequest
> = z.object({
  connectorName: z.string(),
  connectorId: z.string(),
});

export function resyncConnectorRequestToJSON(
  resyncConnectorRequest: ResyncConnectorRequest,
): string {
  return JSON.stringify(
    ResyncConnectorRequest$outboundSchema.parse(resyncConnectorRequest),
  );
}
