/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RevokeAllOAuthAppTokensRequest = {
  /**
   * OAuth app ID
   */
  appId: string;
};

/**
 * All tokens revoked
 */
export type RevokeAllOAuthAppTokensResponse = {
  message?: string | undefined;
  /**
   * Number of tokens revoked
   */
  count?: number | undefined;
};

/** @internal */
export type RevokeAllOAuthAppTokensRequest$Outbound = {
  appId: string;
};

/** @internal */
export const RevokeAllOAuthAppTokensRequest$outboundSchema: z.ZodMiniType<
  RevokeAllOAuthAppTokensRequest$Outbound,
  RevokeAllOAuthAppTokensRequest
> = z.object({
  appId: z.string(),
});

export function revokeAllOAuthAppTokensRequestToJSON(
  revokeAllOAuthAppTokensRequest: RevokeAllOAuthAppTokensRequest,
): string {
  return JSON.stringify(
    RevokeAllOAuthAppTokensRequest$outboundSchema.parse(
      revokeAllOAuthAppTokensRequest,
    ),
  );
}

/** @internal */
export const RevokeAllOAuthAppTokensResponse$inboundSchema: z.ZodMiniType<
  RevokeAllOAuthAppTokensResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
  count: types.optional(types.number()),
});

export function revokeAllOAuthAppTokensResponseFromJSON(
  jsonString: string,
): SafeParseResult<RevokeAllOAuthAppTokensResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RevokeAllOAuthAppTokensResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RevokeAllOAuthAppTokensResponse' from JSON`,
  );
}
