/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Request payload
 */
export type RollBackToPreviousVersionRequestBody = {
  /**
   * Version number to rollback to (0-indexed)
   */
  version: string;
  /**
   * Reason for rollback (required for audit trail)
   */
  note: string;
};

export type RollBackToPreviousVersionRequest = {
  /**
   * Document ID (24-character MongoDB ObjectId)
   */
  documentId: string;
  /**
   * Request payload
   */
  body: RollBackToPreviousVersionRequestBody;
};

/**
 * Document rolled back successfully
 */
export type RollBackToPreviousVersionResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  /**
   * Represents a document stored in PipesHub storage system. Documents can be versioned to maintain complete history of changes. Supports multiple storage backends (S3, Azure Blob, Local).
   *
   * @remarks
   */
  data?: models.Document | undefined;
};

/** @internal */
export type RollBackToPreviousVersionRequestBody$Outbound = {
  version: string;
  note: string;
};

/** @internal */
export const RollBackToPreviousVersionRequestBody$outboundSchema: z.ZodMiniType<
  RollBackToPreviousVersionRequestBody$Outbound,
  RollBackToPreviousVersionRequestBody
> = z.object({
  version: z.string(),
  note: z.string(),
});

export function rollBackToPreviousVersionRequestBodyToJSON(
  rollBackToPreviousVersionRequestBody: RollBackToPreviousVersionRequestBody,
): string {
  return JSON.stringify(
    RollBackToPreviousVersionRequestBody$outboundSchema.parse(
      rollBackToPreviousVersionRequestBody,
    ),
  );
}

/** @internal */
export type RollBackToPreviousVersionRequest$Outbound = {
  documentId: string;
  body: RollBackToPreviousVersionRequestBody$Outbound;
};

/** @internal */
export const RollBackToPreviousVersionRequest$outboundSchema: z.ZodMiniType<
  RollBackToPreviousVersionRequest$Outbound,
  RollBackToPreviousVersionRequest
> = z.object({
  documentId: z.string(),
  body: z.lazy(() => RollBackToPreviousVersionRequestBody$outboundSchema),
});

export function rollBackToPreviousVersionRequestToJSON(
  rollBackToPreviousVersionRequest: RollBackToPreviousVersionRequest,
): string {
  return JSON.stringify(
    RollBackToPreviousVersionRequest$outboundSchema.parse(
      rollBackToPreviousVersionRequest,
    ),
  );
}

/** @internal */
export const RollBackToPreviousVersionResponse$inboundSchema: z.ZodMiniType<
  RollBackToPreviousVersionResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
  data: types.optional(models.Document$inboundSchema),
});

export function rollBackToPreviousVersionResponseFromJSON(
  jsonString: string,
): SafeParseResult<RollBackToPreviousVersionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RollBackToPreviousVersionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RollBackToPreviousVersionResponse' from JSON`,
  );
}
