/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SaveConnectorFiltersRequest = {
  connectorId: string;
  /**
   * Request payload
   */
  body: models.SaveConnectorFiltersRequest;
};

/**
 * Filters saved
 */
export type SaveConnectorFiltersResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
};

/** @internal */
export type SaveConnectorFiltersRequest$Outbound = {
  connectorId: string;
  body: models.SaveConnectorFiltersRequest$Outbound;
};

/** @internal */
export const SaveConnectorFiltersRequest$outboundSchema: z.ZodMiniType<
  SaveConnectorFiltersRequest$Outbound,
  SaveConnectorFiltersRequest
> = z.object({
  connectorId: z.string(),
  body: models.SaveConnectorFiltersRequest$outboundSchema,
});

export function saveConnectorFiltersRequestToJSON(
  saveConnectorFiltersRequest: SaveConnectorFiltersRequest,
): string {
  return JSON.stringify(
    SaveConnectorFiltersRequest$outboundSchema.parse(
      saveConnectorFiltersRequest,
    ),
  );
}

/** @internal */
export const SaveConnectorFiltersResponse$inboundSchema: z.ZodMiniType<
  SaveConnectorFiltersResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
});

export function saveConnectorFiltersResponseFromJSON(
  jsonString: string,
): SafeParseResult<SaveConnectorFiltersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveConnectorFiltersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveConnectorFiltersResponse' from JSON`,
  );
}
