/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SearchHistoryRequest = {
  /**
   * Number of results per page
   */
  limit?: number | undefined;
  /**
   * Page number
   */
  page?: number | undefined;
};

/**
 * Search history with pagination
 */
export type SearchHistoryResponse = {
  results?: Array<models.SearchResult> | undefined;
  /**
   * Total number of searches
   */
  total?: number | undefined;
  page?: number | undefined;
  limit?: number | undefined;
};

/** @internal */
export type SearchHistoryRequest$Outbound = {
  limit: number;
  page: number;
};

/** @internal */
export const SearchHistoryRequest$outboundSchema: z.ZodMiniType<
  SearchHistoryRequest$Outbound,
  SearchHistoryRequest
> = z.object({
  limit: z._default(z.int(), 10),
  page: z._default(z.int(), 1),
});

export function searchHistoryRequestToJSON(
  searchHistoryRequest: SearchHistoryRequest,
): string {
  return JSON.stringify(
    SearchHistoryRequest$outboundSchema.parse(searchHistoryRequest),
  );
}

/** @internal */
export const SearchHistoryResponse$inboundSchema: z.ZodMiniType<
  SearchHistoryResponse,
  unknown
> = z.object({
  results: types.optional(z.array(models.SearchResult$inboundSchema)),
  total: types.optional(types.number()),
  page: types.optional(types.number()),
  limit: types.optional(types.number()),
});

export function searchHistoryResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchHistoryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchHistoryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchHistoryResponse' from JSON`,
  );
}
