/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SendEmailSecurity = {
  scopedToken: string;
};

export type SendEmailData = {
  /**
   * Whether the email was sent successfully
   */
  status?: boolean | undefined;
  /**
   * Success message
   */
  data?: string | undefined;
};

/**
 * Email sent successfully and logged to database
 */
export type SendEmailResponse = {
  data?: SendEmailData | undefined;
};

/** @internal */
export type SendEmailSecurity$Outbound = {
  scopedToken: string;
};

/** @internal */
export const SendEmailSecurity$outboundSchema: z.ZodMiniType<
  SendEmailSecurity$Outbound,
  SendEmailSecurity
> = z.object({
  scopedToken: z.string(),
});

export function sendEmailSecurityToJSON(
  sendEmailSecurity: SendEmailSecurity,
): string {
  return JSON.stringify(
    SendEmailSecurity$outboundSchema.parse(sendEmailSecurity),
  );
}

/** @internal */
export const SendEmailData$inboundSchema: z.ZodMiniType<
  SendEmailData,
  unknown
> = z.object({
  status: types.optional(types.boolean()),
  data: types.optional(types.string()),
});

export function sendEmailDataFromJSON(
  jsonString: string,
): SafeParseResult<SendEmailData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendEmailData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendEmailData' from JSON`,
  );
}

/** @internal */
export const SendEmailResponse$inboundSchema: z.ZodMiniType<
  SendEmailResponse,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => SendEmailData$inboundSchema)),
});

export function sendEmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendEmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendEmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendEmailResponse' from JSON`,
  );
}
