/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Request payload
 */
export type SetMetricsPushIntervalRequest = {
  /**
   * Push interval in milliseconds (minimum 1000ms)
   */
  pushIntervalMs: number;
};

/**
 * Push interval updated successfully
 */
export type SetMetricsPushIntervalResponse = {
  message?: string | undefined;
};

/** @internal */
export type SetMetricsPushIntervalRequest$Outbound = {
  pushIntervalMs: number;
};

/** @internal */
export const SetMetricsPushIntervalRequest$outboundSchema: z.ZodMiniType<
  SetMetricsPushIntervalRequest$Outbound,
  SetMetricsPushIntervalRequest
> = z.object({
  pushIntervalMs: z.int(),
});

export function setMetricsPushIntervalRequestToJSON(
  setMetricsPushIntervalRequest: SetMetricsPushIntervalRequest,
): string {
  return JSON.stringify(
    SetMetricsPushIntervalRequest$outboundSchema.parse(
      setMetricsPushIntervalRequest,
    ),
  );
}

/** @internal */
export const SetMetricsPushIntervalResponse$inboundSchema: z.ZodMiniType<
  SetMetricsPushIntervalResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function setMetricsPushIntervalResponseFromJSON(
  jsonString: string,
): SafeParseResult<SetMetricsPushIntervalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SetMetricsPushIntervalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SetMetricsPushIntervalResponse' from JSON`,
  );
}
