/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request body for Update platform settings
 */
export type SetPlatformSettingsRequest = {
  /**
   * Maximum file upload size in bytes
   */
  fileUploadMaxSizeBytes: number;
  /**
   * Key-value map of feature flags. Set to true to enable, false to disable.
   */
  featureFlags: { [k: string]: boolean };
};

/** @internal */
export type SetPlatformSettingsRequest$Outbound = {
  fileUploadMaxSizeBytes: number;
  featureFlags: { [k: string]: boolean };
};

/** @internal */
export const SetPlatformSettingsRequest$outboundSchema: z.ZodMiniType<
  SetPlatformSettingsRequest$Outbound,
  SetPlatformSettingsRequest
> = z.object({
  fileUploadMaxSizeBytes: z.int(),
  featureFlags: z.record(z.string(), z.boolean()),
});

export function setPlatformSettingsRequestToJSON(
  setPlatformSettingsRequest: SetPlatformSettingsRequest,
): string {
  return JSON.stringify(
    SetPlatformSettingsRequest$outboundSchema.parse(setPlatformSettingsRequest),
  );
}
