/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SuspendOAuthAppRequest = {
  /**
   * OAuth app ID
   */
  appId: string;
};

/** @internal */
export type SuspendOAuthAppRequest$Outbound = {
  appId: string;
};

/** @internal */
export const SuspendOAuthAppRequest$outboundSchema: z.ZodMiniType<
  SuspendOAuthAppRequest$Outbound,
  SuspendOAuthAppRequest
> = z.object({
  appId: z.string(),
});

export function suspendOAuthAppRequestToJSON(
  suspendOAuthAppRequest: SuspendOAuthAppRequest,
): string {
  return JSON.stringify(
    SuspendOAuthAppRequest$outboundSchema.parse(suspendOAuthAppRequest),
  );
}
