/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request payload
 */
export type UnshareConversationRequestBody = {
  /**
   * User IDs to remove access from
   */
  userIds: Array<string>;
};

export type UnshareConversationRequest = {
  conversationId: string;
  /**
   * Request payload
   */
  body: UnshareConversationRequestBody;
};

/** @internal */
export type UnshareConversationRequestBody$Outbound = {
  userIds: Array<string>;
};

/** @internal */
export const UnshareConversationRequestBody$outboundSchema: z.ZodMiniType<
  UnshareConversationRequestBody$Outbound,
  UnshareConversationRequestBody
> = z.object({
  userIds: z.array(z.string()),
});

export function unshareConversationRequestBodyToJSON(
  unshareConversationRequestBody: UnshareConversationRequestBody,
): string {
  return JSON.stringify(
    UnshareConversationRequestBody$outboundSchema.parse(
      unshareConversationRequestBody,
    ),
  );
}

/** @internal */
export type UnshareConversationRequest$Outbound = {
  conversationId: string;
  body: UnshareConversationRequestBody$Outbound;
};

/** @internal */
export const UnshareConversationRequest$outboundSchema: z.ZodMiniType<
  UnshareConversationRequest$Outbound,
  UnshareConversationRequest
> = z.object({
  conversationId: z.string(),
  body: z.lazy(() => UnshareConversationRequestBody$outboundSchema),
});

export function unshareConversationRequestToJSON(
  unshareConversationRequest: UnshareConversationRequest,
): string {
  return JSON.stringify(
    UnshareConversationRequest$outboundSchema.parse(unshareConversationRequest),
  );
}
