/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateOAuthAppRequest = {
  /**
   * OAuth app ID
   */
  appId: string;
  /**
   * Request payload
   */
  body: models.UpdateOAuthAppRequest;
};

/** @internal */
export type UpdateOAuthAppRequest$Outbound = {
  appId: string;
  body: models.UpdateOAuthAppRequest$Outbound;
};

/** @internal */
export const UpdateOAuthAppRequest$outboundSchema: z.ZodMiniType<
  UpdateOAuthAppRequest$Outbound,
  UpdateOAuthAppRequest
> = z.object({
  appId: z.string(),
  body: models.UpdateOAuthAppRequest$outboundSchema,
});

export function updateOAuthAppRequestToJSON(
  updateOAuthAppRequest: UpdateOAuthAppRequest,
): string {
  return JSON.stringify(
    UpdateOAuthAppRequest$outboundSchema.parse(updateOAuthAppRequest),
  );
}
