/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request payload
 */
export type UpdateFolderRequestBody = {
  folderName: string;
};

export type UpdateFolderRequest = {
  kbId: string;
  folderId: string;
  /**
   * Request payload
   */
  body: UpdateFolderRequestBody;
};

/** @internal */
export type UpdateFolderRequestBody$Outbound = {
  folderName: string;
};

/** @internal */
export const UpdateFolderRequestBody$outboundSchema: z.ZodMiniType<
  UpdateFolderRequestBody$Outbound,
  UpdateFolderRequestBody
> = z.object({
  folderName: z.string(),
});

export function updateFolderRequestBodyToJSON(
  updateFolderRequestBody: UpdateFolderRequestBody,
): string {
  return JSON.stringify(
    UpdateFolderRequestBody$outboundSchema.parse(updateFolderRequestBody),
  );
}

/** @internal */
export type UpdateFolderRequest$Outbound = {
  kbId: string;
  folderId: string;
  body: UpdateFolderRequestBody$Outbound;
};

/** @internal */
export const UpdateFolderRequest$outboundSchema: z.ZodMiniType<
  UpdateFolderRequest$Outbound,
  UpdateFolderRequest
> = z.object({
  kbId: z.string(),
  folderId: z.string(),
  body: z.lazy(() => UpdateFolderRequestBody$outboundSchema),
});

export function updateFolderRequestToJSON(
  updateFolderRequest: UpdateFolderRequest,
): string {
  return JSON.stringify(
    UpdateFolderRequest$outboundSchema.parse(updateFolderRequest),
  );
}
