/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * New role to assign to the user
 */
export const UpdateTeamUserPermissionsRole = {
  Owner: "owner",
  Admin: "admin",
  Member: "member",
  Viewer: "viewer",
} as const;
/**
 * New role to assign to the user
 */
export type UpdateTeamUserPermissionsRole = ClosedEnum<
  typeof UpdateTeamUserPermissionsRole
>;

/**
 * Request payload
 */
export type UpdateTeamUserPermissionsRequestBody = {
  /**
   * ID of the user whose role to update
   */
  userId: string;
  /**
   * New role to assign to the user
   */
  role: UpdateTeamUserPermissionsRole;
};

export type UpdateTeamUserPermissionsRequest = {
  /**
   * Unique identifier of the team
   */
  teamId: string;
  /**
   * Request payload
   */
  body: UpdateTeamUserPermissionsRequestBody;
};

/**
 * User role updated successfully
 */
export type UpdateTeamUserPermissionsResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  previousRole?: string | undefined;
  newRole?: string | undefined;
};

/** @internal */
export const UpdateTeamUserPermissionsRole$outboundSchema: z.ZodMiniEnum<
  typeof UpdateTeamUserPermissionsRole
> = z.enum(UpdateTeamUserPermissionsRole);

/** @internal */
export type UpdateTeamUserPermissionsRequestBody$Outbound = {
  userId: string;
  role: string;
};

/** @internal */
export const UpdateTeamUserPermissionsRequestBody$outboundSchema: z.ZodMiniType<
  UpdateTeamUserPermissionsRequestBody$Outbound,
  UpdateTeamUserPermissionsRequestBody
> = z.object({
  userId: z.string(),
  role: UpdateTeamUserPermissionsRole$outboundSchema,
});

export function updateTeamUserPermissionsRequestBodyToJSON(
  updateTeamUserPermissionsRequestBody: UpdateTeamUserPermissionsRequestBody,
): string {
  return JSON.stringify(
    UpdateTeamUserPermissionsRequestBody$outboundSchema.parse(
      updateTeamUserPermissionsRequestBody,
    ),
  );
}

/** @internal */
export type UpdateTeamUserPermissionsRequest$Outbound = {
  teamId: string;
  body: UpdateTeamUserPermissionsRequestBody$Outbound;
};

/** @internal */
export const UpdateTeamUserPermissionsRequest$outboundSchema: z.ZodMiniType<
  UpdateTeamUserPermissionsRequest$Outbound,
  UpdateTeamUserPermissionsRequest
> = z.object({
  teamId: z.string(),
  body: z.lazy(() => UpdateTeamUserPermissionsRequestBody$outboundSchema),
});

export function updateTeamUserPermissionsRequestToJSON(
  updateTeamUserPermissionsRequest: UpdateTeamUserPermissionsRequest,
): string {
  return JSON.stringify(
    UpdateTeamUserPermissionsRequest$outboundSchema.parse(
      updateTeamUserPermissionsRequest,
    ),
  );
}

/** @internal */
export const UpdateTeamUserPermissionsResponse$inboundSchema: z.ZodMiniType<
  UpdateTeamUserPermissionsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
  previousRole: types.optional(types.string()),
  newRole: types.optional(types.string()),
});

export function updateTeamUserPermissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTeamUserPermissionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTeamUserPermissionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTeamUserPermissionsResponse' from JSON`,
  );
}
