/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

export const UpdateKBPermissionsRole = {
  Owner: "OWNER",
  Organizer: "ORGANIZER",
  Fileorganizer: "FILEORGANIZER",
  Writer: "WRITER",
  Commenter: "COMMENTER",
  Reader: "READER",
} as const;
export type UpdateKBPermissionsRole = ClosedEnum<
  typeof UpdateKBPermissionsRole
>;

/**
 * Request body for Update permissions
 */
export type UpdateKBPermissionsRequestBody = {
  userIds?: Array<string> | undefined;
  teamIds?: Array<string> | undefined;
  role: UpdateKBPermissionsRole;
};

export type UpdateKBPermissionsRequest = {
  kbId: string;
  /**
   * Request body for Update permissions
   */
  body: UpdateKBPermissionsRequestBody;
};

/** @internal */
export const UpdateKBPermissionsRole$outboundSchema: z.ZodMiniEnum<
  typeof UpdateKBPermissionsRole
> = z.enum(UpdateKBPermissionsRole);

/** @internal */
export type UpdateKBPermissionsRequestBody$Outbound = {
  userIds?: Array<string> | undefined;
  teamIds?: Array<string> | undefined;
  role: string;
};

/** @internal */
export const UpdateKBPermissionsRequestBody$outboundSchema: z.ZodMiniType<
  UpdateKBPermissionsRequestBody$Outbound,
  UpdateKBPermissionsRequestBody
> = z.object({
  userIds: z.optional(z.array(z.string())),
  teamIds: z.optional(z.array(z.string())),
  role: UpdateKBPermissionsRole$outboundSchema,
});

export function updateKBPermissionsRequestBodyToJSON(
  updateKBPermissionsRequestBody: UpdateKBPermissionsRequestBody,
): string {
  return JSON.stringify(
    UpdateKBPermissionsRequestBody$outboundSchema.parse(
      updateKBPermissionsRequestBody,
    ),
  );
}

/** @internal */
export type UpdateKBPermissionsRequest$Outbound = {
  kbId: string;
  body: UpdateKBPermissionsRequestBody$Outbound;
};

/** @internal */
export const UpdateKBPermissionsRequest$outboundSchema: z.ZodMiniType<
  UpdateKBPermissionsRequest$Outbound,
  UpdateKBPermissionsRequest
> = z.object({
  kbId: z.string(),
  body: z.lazy(() => UpdateKBPermissionsRequestBody$outboundSchema),
});

export function updateKBPermissionsRequestToJSON(
  updateKBPermissionsRequest: UpdateKBPermissionsRequest,
): string {
  return JSON.stringify(
    UpdateKBPermissionsRequest$outboundSchema.parse(updateKBPermissionsRequest),
  );
}
