/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateConnectorConfigRequest = {
  connectorId: string;
  /**
   * Request payload
   */
  body: models.UpdateConnectorConfigRequest;
};

/**
 * Configuration updated
 */
export type UpdateConnectorConfigResponse = {
  success?: boolean | undefined;
  /**
   * Configuration for a connector instance including auth, sync, and filter settings
   */
  config?: models.ConnectorConfig | undefined;
};

/** @internal */
export type UpdateConnectorConfigRequest$Outbound = {
  connectorId: string;
  body: models.UpdateConnectorConfigRequest$Outbound;
};

/** @internal */
export const UpdateConnectorConfigRequest$outboundSchema: z.ZodMiniType<
  UpdateConnectorConfigRequest$Outbound,
  UpdateConnectorConfigRequest
> = z.object({
  connectorId: z.string(),
  body: models.UpdateConnectorConfigRequest$outboundSchema,
});

export function updateConnectorConfigRequestToJSON(
  updateConnectorConfigRequest: UpdateConnectorConfigRequest,
): string {
  return JSON.stringify(
    UpdateConnectorConfigRequest$outboundSchema.parse(
      updateConnectorConfigRequest,
    ),
  );
}

/** @internal */
export const UpdateConnectorConfigResponse$inboundSchema: z.ZodMiniType<
  UpdateConnectorConfigResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  config: types.optional(models.ConnectorConfig$inboundSchema),
});

export function updateConnectorConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateConnectorConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateConnectorConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateConnectorConfigResponse' from JSON`,
  );
}
