// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthStep - A single step in multi-factor authentication flow
type AuthStep struct {
	// Order of the authentication step (1-3, must be unique across steps)
	Order int64 `json:"order"`
	// List of allowed authentication methods for this step. User can choose any one method from this list.
	AllowedMethods []AuthMethod `json:"allowedMethods"`
}

func (o *AuthStep) GetOrder() int64 {
	if o == nil {
		return 0
	}
	return o.Order
}

func (o *AuthStep) GetAllowedMethods() []AuthMethod {
	if o == nil {
		return []AuthMethod{}
	}
	return o.AllowedMethods
}
