// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

// Method - Authentication method to use
type Method string

const (
	MethodSamlSso   Method = "samlSso"
	MethodOtp       Method = "otp"
	MethodPassword  Method = "password"
	MethodGoogle    Method = "google"
	MethodMicrosoft Method = "microsoft"
	MethodAzureAd   Method = "azureAd"
	MethodOauth     Method = "oauth"
)

func (e Method) ToPointer() *Method {
	return &e
}
func (e *Method) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "samlSso":
		fallthrough
	case "otp":
		fallthrough
	case "password":
		fallthrough
	case "google":
		fallthrough
	case "microsoft":
		fallthrough
	case "azureAd":
		fallthrough
	case "oauth":
		*e = Method(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Method: %v", v)
	}
}

type CredentialsType string

const (
	CredentialsTypePasswordCredentials CredentialsType = "PasswordCredentials"
	CredentialsTypeOtpCredentials      CredentialsType = "OtpCredentials"
	CredentialsTypeOAuthCredentials    CredentialsType = "OAuthCredentials"
	CredentialsTypeStr                 CredentialsType = "str"
)

// Credentials based on the authentication method
type Credentials struct {
	PasswordCredentials *PasswordCredentials `queryParam:"inline"`
	OtpCredentials      *OtpCredentials      `queryParam:"inline"`
	OAuthCredentials    *OAuthCredentials    `queryParam:"inline"`
	Str                 *string              `queryParam:"inline"`

	Type CredentialsType
}

func CreateCredentialsPasswordCredentials(passwordCredentials PasswordCredentials) Credentials {
	typ := CredentialsTypePasswordCredentials

	return Credentials{
		PasswordCredentials: &passwordCredentials,
		Type:                typ,
	}
}

func CreateCredentialsOtpCredentials(otpCredentials OtpCredentials) Credentials {
	typ := CredentialsTypeOtpCredentials

	return Credentials{
		OtpCredentials: &otpCredentials,
		Type:           typ,
	}
}

func CreateCredentialsOAuthCredentials(oAuthCredentials OAuthCredentials) Credentials {
	typ := CredentialsTypeOAuthCredentials

	return Credentials{
		OAuthCredentials: &oAuthCredentials,
		Type:             typ,
	}
}

func CreateCredentialsStr(str string) Credentials {
	typ := CredentialsTypeStr

	return Credentials{
		Str:  &str,
		Type: typ,
	}
}

func (u *Credentials) UnmarshalJSON(data []byte) error {

	var passwordCredentials PasswordCredentials = PasswordCredentials{}
	if err := utils.UnmarshalJSON(data, &passwordCredentials, "", true, nil); err == nil {
		u.PasswordCredentials = &passwordCredentials
		u.Type = CredentialsTypePasswordCredentials
		return nil
	}

	var otpCredentials OtpCredentials = OtpCredentials{}
	if err := utils.UnmarshalJSON(data, &otpCredentials, "", true, nil); err == nil {
		u.OtpCredentials = &otpCredentials
		u.Type = CredentialsTypeOtpCredentials
		return nil
	}

	var oAuthCredentials OAuthCredentials = OAuthCredentials{}
	if err := utils.UnmarshalJSON(data, &oAuthCredentials, "", true, nil); err == nil {
		u.OAuthCredentials = &oAuthCredentials
		u.Type = CredentialsTypeOAuthCredentials
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = CredentialsTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Credentials", string(data))
}

func (u Credentials) MarshalJSON() ([]byte, error) {
	if u.PasswordCredentials != nil {
		return utils.MarshalJSON(u.PasswordCredentials, "", true)
	}

	if u.OtpCredentials != nil {
		return utils.MarshalJSON(u.OtpCredentials, "", true)
	}

	if u.OAuthCredentials != nil {
		return utils.MarshalJSON(u.OAuthCredentials, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type Credentials: all fields are null")
}

// AuthenticateRequest - Request to authenticate using specified method.
// **Credential format varies by method:**
// - `password`: `{ password: "string" }`
// - `otp`: `{ otp: "123456" }` (6-digit code)
// - `google`: `"google-id-token-string"`
// - `microsoft`: `{ accessToken: "...", idToken: "..." }`
// - `azureAd`: `{ accessToken: "...", idToken: "..." }`
// - `oauth`: `{ accessToken: "...", idToken: "..." }`
// - `samlSso`: handled via redirect flow
type AuthenticateRequest struct {
	// Authentication method to use
	Method Method `json:"method"`
	// Credentials based on the authentication method
	Credentials Credentials `json:"credentials"`
	// Optional email for verification (used with some OAuth methods)
	Email *string `json:"email,omitempty"`
	// Cloudflare Turnstile CAPTCHA token (optional, if CAPTCHA is enabled)
	CfTurnstileResponse *string `json:"cf-turnstile-response,omitempty"`
}

func (o *AuthenticateRequest) GetMethod() Method {
	if o == nil {
		return Method("")
	}
	return o.Method
}

func (o *AuthenticateRequest) GetCredentials() Credentials {
	if o == nil {
		return Credentials{}
	}
	return o.Credentials
}

func (o *AuthenticateRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *AuthenticateRequest) GetCfTurnstileResponse() *string {
	if o == nil {
		return nil
	}
	return o.CfTurnstileResponse
}
