// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

// AzureAdAuthConfig - Azure Active Directory authentication configuration
type AzureAdAuthConfig struct {
	// Azure AD application client ID
	ClientID *string `json:"clientId,omitempty"`
	// Azure AD tenant ID (use 'common' for multi-tenant)
	TenantID *string `default:"common" json:"tenantId"`
}

func (a AzureAdAuthConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AzureAdAuthConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *AzureAdAuthConfig) GetClientID() *string {
	if o == nil {
		return nil
	}
	return o.ClientID
}

func (o *AzureAdAuthConfig) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}
