// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CitationReference - Reference to a source document cited in a response
type CitationReference struct {
	// ID of the citation record
	CitationID *string `json:"citationId,omitempty"`
	// How relevant this citation is to the query (0-1)
	RelevanceScore *float64 `json:"relevanceScore,omitempty"`
	// Relevant excerpt from the source document
	Excerpt *string `json:"excerpt,omitempty"`
	// Additional context around the citation
	Context *string `json:"context,omitempty"`
}

func (o *CitationReference) GetCitationID() *string {
	if o == nil {
		return nil
	}
	return o.CitationID
}

func (o *CitationReference) GetRelevanceScore() *float64 {
	if o == nil {
		return nil
	}
	return o.RelevanceScore
}

func (o *CitationReference) GetExcerpt() *string {
	if o == nil {
		return nil
	}
	return o.Excerpt
}

func (o *CitationReference) GetContext() *string {
	if o == nil {
		return nil
	}
	return o.Context
}
