// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConnectorPagination - Pagination information for connector lists
type ConnectorPagination struct {
	// Current page number
	Page *int64 `json:"page,omitempty"`
	// Items per page
	Limit *int64 `json:"limit,omitempty"`
	// Total number of items
	Total *int64 `json:"total,omitempty"`
	// Whether more pages exist
	HasMore *bool `json:"hasMore,omitempty"`
}

func (o *ConnectorPagination) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ConnectorPagination) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ConnectorPagination) GetTotal() *int64 {
	if o == nil {
		return nil
	}
	return o.Total
}

func (o *ConnectorPagination) GetHasMore() *bool {
	if o == nil {
		return nil
	}
	return o.HasMore
}
