// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// AuthType - Authentication type (required if connector supports multiple auth methods)
type AuthType string

const (
	AuthTypeOauth             AuthType = "OAUTH"
	AuthTypeOauthAdminConsent AuthType = "OAUTH_ADMIN_CONSENT"
	AuthTypeAPIToken          AuthType = "API_TOKEN"
	AuthTypeUsernamePassword  AuthType = "USERNAME_PASSWORD"
	AuthTypeServiceAccount    AuthType = "SERVICE_ACCOUNT"
)

func (e AuthType) ToPointer() *AuthType {
	return &e
}
func (e *AuthType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OAUTH":
		fallthrough
	case "OAUTH_ADMIN_CONSENT":
		fallthrough
	case "API_TOKEN":
		fallthrough
	case "USERNAME_PASSWORD":
		fallthrough
	case "SERVICE_ACCOUNT":
		*e = AuthType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthType: %v", v)
	}
}

// CreateConnectorRequestConfig - Initial configuration (can also be set after creation)
type CreateConnectorRequestConfig struct {
	// Authentication configuration for a connector instance
	Auth *ConnectorAuthConfig `json:"auth,omitempty"`
	// Synchronization configuration for a connector instance
	Sync *ConnectorSyncConfig `json:"sync,omitempty"`
	// Filter configuration to control what data is synced (sync filters and indexing filters)
	Filters *ConnectorFiltersConfig `json:"filters,omitempty"`
}

func (o *CreateConnectorRequestConfig) GetAuth() *ConnectorAuthConfig {
	if o == nil {
		return nil
	}
	return o.Auth
}

func (o *CreateConnectorRequestConfig) GetSync() *ConnectorSyncConfig {
	if o == nil {
		return nil
	}
	return o.Sync
}

func (o *CreateConnectorRequestConfig) GetFilters() *ConnectorFiltersConfig {
	if o == nil {
		return nil
	}
	return o.Filters
}

// CreateConnectorRequest - Request to create a new connector instance
type CreateConnectorRequest struct {
	// Connector type from registry (e.g., google-drive, confluence, slack)
	ConnectorType string `json:"connectorType"`
	// Display name for this connector instance
	InstanceName string `json:"instanceName"`
	// Scope determines visibility and access control for connectors:<br>
	// <ul>
	// <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
	// <li><code>personal</code> - Private to the creating user only</li>
	// </ul>
	//
	Scope ConnectorScope `json:"scope"`
	// Authentication type (required if connector supports multiple auth methods)
	AuthType *AuthType `json:"authType,omitempty"`
	// Initial configuration (can also be set after creation)
	Config *CreateConnectorRequestConfig `json:"config,omitempty"`
	// Base URL for self-hosted instances (e.g., Confluence Server, GitLab Self-Managed)
	BaseURL *string `json:"baseUrl,omitempty"`
}

func (o *CreateConnectorRequest) GetConnectorType() string {
	if o == nil {
		return ""
	}
	return o.ConnectorType
}

func (o *CreateConnectorRequest) GetInstanceName() string {
	if o == nil {
		return ""
	}
	return o.InstanceName
}

func (o *CreateConnectorRequest) GetScope() ConnectorScope {
	if o == nil {
		return ConnectorScope("")
	}
	return o.Scope
}

func (o *CreateConnectorRequest) GetAuthType() *AuthType {
	if o == nil {
		return nil
	}
	return o.AuthType
}

func (o *CreateConnectorRequest) GetConfig() *CreateConnectorRequestConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *CreateConnectorRequest) GetBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseURL
}
