// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GoogleAuthConfig - Google authentication configuration
type GoogleAuthConfig struct {
	// Google OAuth client ID
	ClientID *string `json:"clientId,omitempty"`
}

func (o *GoogleAuthConfig) GetClientID() *string {
	if o == nil {
		return nil
	}
	return o.ClientID
}
