// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type KBPermissionRole string

const (
	KBPermissionRoleOwner         KBPermissionRole = "OWNER"
	KBPermissionRoleOrganizer     KBPermissionRole = "ORGANIZER"
	KBPermissionRoleFileorganizer KBPermissionRole = "FILEORGANIZER"
	KBPermissionRoleWriter        KBPermissionRole = "WRITER"
	KBPermissionRoleCommenter     KBPermissionRole = "COMMENTER"
	KBPermissionRoleReader        KBPermissionRole = "READER"
)

func (e KBPermissionRole) ToPointer() *KBPermissionRole {
	return &e
}
func (e *KBPermissionRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OWNER":
		fallthrough
	case "ORGANIZER":
		fallthrough
	case "FILEORGANIZER":
		fallthrough
	case "WRITER":
		fallthrough
	case "COMMENTER":
		fallthrough
	case "READER":
		*e = KBPermissionRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KBPermissionRole: %v", v)
	}
}

// KBPermissionType - Whether permission is for a user or team
type KBPermissionType string

const (
	KBPermissionTypeUser KBPermissionType = "USER"
	KBPermissionTypeTeam KBPermissionType = "TEAM"
)

func (e KBPermissionType) ToPointer() *KBPermissionType {
	return &e
}
func (e *KBPermissionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "USER":
		fallthrough
	case "TEAM":
		*e = KBPermissionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KBPermissionType: %v", v)
	}
}

type KBPermission struct {
	// Permission entry ID
	ID *string `json:"id,omitempty"`
	// User ID
	UserID *string `json:"userId,omitempty"`
	// User email
	Email *string `json:"email,omitempty"`
	// User display name
	Name *string           `json:"name,omitempty"`
	Role *KBPermissionRole `json:"role,omitempty"`
	// Whether permission is for a user or team
	Type               *KBPermissionType `json:"type,omitempty"`
	CreatedAtTimestamp *int64            `json:"createdAtTimestamp,omitempty"`
	UpdatedAtTimestamp *int64            `json:"updatedAtTimestamp,omitempty"`
}

func (o *KBPermission) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *KBPermission) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *KBPermission) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *KBPermission) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *KBPermission) GetRole() *KBPermissionRole {
	if o == nil {
		return nil
	}
	return o.Role
}

func (o *KBPermission) GetType() *KBPermissionType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *KBPermission) GetCreatedAtTimestamp() *int64 {
	if o == nil {
		return nil
	}
	return o.CreatedAtTimestamp
}

func (o *KBPermission) GetUpdatedAtTimestamp() *int64 {
	if o == nil {
		return nil
	}
	return o.UpdatedAtTimestamp
}
