// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Error code. Common values:
// - `invalid_request` - Missing or invalid parameter
// - `invalid_client` - Client authentication failed
// - `invalid_grant` - Invalid authorization code or refresh token
// - `unauthorized_client` - Client not authorized for this grant type
// - `unsupported_grant_type` - Grant type not supported
// - `invalid_scope` - Requested scope is invalid or exceeds allowed
// - `access_denied` - User denied authorization
type Error string

const (
	ErrorInvalidRequest       Error = "invalid_request"
	ErrorInvalidClient        Error = "invalid_client"
	ErrorInvalidGrant         Error = "invalid_grant"
	ErrorUnauthorizedClient   Error = "unauthorized_client"
	ErrorUnsupportedGrantType Error = "unsupported_grant_type"
	ErrorInvalidScope         Error = "invalid_scope"
	ErrorAccessDenied         Error = "access_denied"
	ErrorServerError          Error = "server_error"
)

func (e Error) ToPointer() *Error {
	return &e
}
func (e *Error) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invalid_request":
		fallthrough
	case "invalid_client":
		fallthrough
	case "invalid_grant":
		fallthrough
	case "unauthorized_client":
		fallthrough
	case "unsupported_grant_type":
		fallthrough
	case "invalid_scope":
		fallthrough
	case "access_denied":
		fallthrough
	case "server_error":
		*e = Error(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Error: %v", v)
	}
}
