// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/utils"
	"time"
)

// OrganizationAccountType - Type of account
type OrganizationAccountType string

const (
	OrganizationAccountTypeIndividual OrganizationAccountType = "individual"
	OrganizationAccountTypeBusiness   OrganizationAccountType = "business"
)

func (e OrganizationAccountType) ToPointer() *OrganizationAccountType {
	return &e
}
func (e *OrganizationAccountType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "individual":
		fallthrough
	case "business":
		*e = OrganizationAccountType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrganizationAccountType: %v", v)
	}
}

// OnBoardingStatus - Onboarding status
type OnBoardingStatus string

const (
	OnBoardingStatusConfigured    OnBoardingStatus = "configured"
	OnBoardingStatusNotConfigured OnBoardingStatus = "notConfigured"
	OnBoardingStatusSkipped       OnBoardingStatus = "skipped"
)

func (e OnBoardingStatus) ToPointer() *OnBoardingStatus {
	return &e
}
func (e *OnBoardingStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "configured":
		fallthrough
	case "notConfigured":
		fallthrough
	case "skipped":
		*e = OnBoardingStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OnBoardingStatus: %v", v)
	}
}

type Organization struct {
	// Unique organization identifier
	ID *string `json:"_id,omitempty"`
	// Unique slug for the organization
	Slug *string `json:"slug,omitempty"`
	// Registered name
	RegisteredName *string `json:"registeredName,omitempty"`
	// Short name or display name
	ShortName *string `json:"shortName,omitempty"`
	// Organization domain
	Domain string `json:"domain"`
	// Contact email address
	ContactEmail string `json:"contactEmail"`
	// Type of account
	AccountType      OrganizationAccountType `json:"accountType"`
	PermanentAddress *Address                `json:"permanentAddress,omitempty"`
	// Onboarding status
	OnBoardingStatus *OnBoardingStatus `json:"onBoardingStatus,omitempty"`
	// Soft delete flag
	IsDeleted *bool `default:"false" json:"isDeleted"`
	// Document version (MongoDB)
	V *int64 `json:"__v,omitempty"`
	// Creation timestamp (ISO 8601)
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Last update timestamp (ISO 8601)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (o Organization) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *Organization) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, []string{"domain", "contactEmail", "accountType"}); err != nil {
		return err
	}
	return nil
}

func (o *Organization) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Organization) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *Organization) GetRegisteredName() *string {
	if o == nil {
		return nil
	}
	return o.RegisteredName
}

func (o *Organization) GetShortName() *string {
	if o == nil {
		return nil
	}
	return o.ShortName
}

func (o *Organization) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *Organization) GetContactEmail() string {
	if o == nil {
		return ""
	}
	return o.ContactEmail
}

func (o *Organization) GetAccountType() OrganizationAccountType {
	if o == nil {
		return OrganizationAccountType("")
	}
	return o.AccountType
}

func (o *Organization) GetPermanentAddress() *Address {
	if o == nil {
		return nil
	}
	return o.PermanentAddress
}

func (o *Organization) GetOnBoardingStatus() *OnBoardingStatus {
	if o == nil {
		return nil
	}
	return o.OnBoardingStatus
}

func (o *Organization) GetIsDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.IsDeleted
}

func (o *Organization) GetV() *int64 {
	if o == nil {
		return nil
	}
	return o.V
}

func (o *Organization) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Organization) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
