// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PaginationInfo struct {
	// Current page number
	Page *int64 `json:"page,omitempty"`
	// Items per page
	Limit *int64 `json:"limit,omitempty"`
	// Total number of items
	TotalCount *int64 `json:"totalCount,omitempty"`
	// Total number of pages
	TotalPages *int64 `json:"totalPages,omitempty"`
}

func (o *PaginationInfo) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *PaginationInfo) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *PaginationInfo) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *PaginationInfo) GetTotalPages() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalPages
}
