// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Applied - Currently applied filters
type Applied struct {
}

// Available filter options with counts
type Available struct {
}

type RecordsResponseFilters struct {
	// Currently applied filters
	Applied *Applied `json:"applied,omitempty"`
	// Available filter options with counts
	Available *Available `json:"available,omitempty"`
}

func (o *RecordsResponseFilters) GetApplied() *Applied {
	if o == nil {
		return nil
	}
	return o.Applied
}

func (o *RecordsResponseFilters) GetAvailable() *Available {
	if o == nil {
		return nil
	}
	return o.Available
}

// RecordsResponse - Paginated response for records listing
type RecordsResponse struct {
	Records    []Record                `json:"records,omitempty"`
	Pagination *PaginationInfo         `json:"pagination,omitempty"`
	Filters    *RecordsResponseFilters `json:"filters,omitempty"`
}

func (o *RecordsResponse) GetRecords() []Record {
	if o == nil {
		return nil
	}
	return o.Records
}

func (o *RecordsResponse) GetPagination() *PaginationInfo {
	if o == nil {
		return nil
	}
	return o.Pagination
}

func (o *RecordsResponse) GetFilters() *RecordsResponseFilters {
	if o == nil {
		return nil
	}
	return o.Filters
}
