// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RefreshTokenResponse - Response with new access token
type RefreshTokenResponse struct {
	// Basic user information
	User *UserBasic `json:"user,omitempty"`
	// New JWT access token (1 hour expiry)
	AccessToken *string `json:"accessToken,omitempty"`
}

func (o *RefreshTokenResponse) GetUser() *UserBasic {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *RefreshTokenResponse) GetAccessToken() *string {
	if o == nil {
		return nil
	}
	return o.AccessToken
}
