// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type ScheduleConfigType string

const (
	ScheduleConfigTypeHourly  ScheduleConfigType = "hourly"
	ScheduleConfigTypeDaily   ScheduleConfigType = "daily"
	ScheduleConfigTypeWeekly  ScheduleConfigType = "weekly"
	ScheduleConfigTypeMonthly ScheduleConfigType = "monthly"
	ScheduleConfigTypeCustom  ScheduleConfigType = "custom"
	ScheduleConfigTypeOnce    ScheduleConfigType = "once"
)

// ScheduleConfig - Schedule configuration for crawling jobs. The structure varies based on <code>scheduleType</code>.<br><br>
// <b>Schedule Type Configurations:</b><br>
// <ul>
// <li><b>hourly:</b> <code>minute</code>, <code>interval</code> (optional)</li>
// <li><b>daily:</b> <code>hour</code>, <code>minute</code></li>
// <li><b>weekly:</b> <code>daysOfWeek</code>, <code>hour</code>, <code>minute</code></li>
// <li><b>monthly:</b> <code>dayOfMonth</code>, <code>hour</code>, <code>minute</code></li>
// <li><b>custom:</b> <code>cronExpression</code>, <code>description</code> (optional)</li>
// <li><b>once:</b> <code>scheduledTime</code></li>
// </ul>
type ScheduleConfig struct {
	HourlyScheduleConfig  *HourlyScheduleConfig  `queryParam:"inline"`
	DailyScheduleConfig   *DailyScheduleConfig   `queryParam:"inline"`
	WeeklyScheduleConfig  *WeeklyScheduleConfig  `queryParam:"inline"`
	MonthlyScheduleConfig *MonthlyScheduleConfig `queryParam:"inline"`
	CustomScheduleConfig  *CustomScheduleConfig  `queryParam:"inline"`
	OnceScheduleConfig    *OnceScheduleConfig    `queryParam:"inline"`

	Type ScheduleConfigType
}

func CreateScheduleConfigHourly(hourly HourlyScheduleConfig) ScheduleConfig {
	typ := ScheduleConfigTypeHourly

	typStr := HourlyScheduleConfigScheduleType(typ)
	hourly.ScheduleType = typStr

	return ScheduleConfig{
		HourlyScheduleConfig: &hourly,
		Type:                 typ,
	}
}

func CreateScheduleConfigDaily(daily DailyScheduleConfig) ScheduleConfig {
	typ := ScheduleConfigTypeDaily

	typStr := DailyScheduleConfigScheduleType(typ)
	daily.ScheduleType = typStr

	return ScheduleConfig{
		DailyScheduleConfig: &daily,
		Type:                typ,
	}
}

func CreateScheduleConfigWeekly(weekly WeeklyScheduleConfig) ScheduleConfig {
	typ := ScheduleConfigTypeWeekly

	typStr := WeeklyScheduleConfigScheduleType(typ)
	weekly.ScheduleType = typStr

	return ScheduleConfig{
		WeeklyScheduleConfig: &weekly,
		Type:                 typ,
	}
}

func CreateScheduleConfigMonthly(monthly MonthlyScheduleConfig) ScheduleConfig {
	typ := ScheduleConfigTypeMonthly

	typStr := MonthlyScheduleConfigScheduleType(typ)
	monthly.ScheduleType = typStr

	return ScheduleConfig{
		MonthlyScheduleConfig: &monthly,
		Type:                  typ,
	}
}

func CreateScheduleConfigCustom(custom CustomScheduleConfig) ScheduleConfig {
	typ := ScheduleConfigTypeCustom

	typStr := CustomScheduleConfigScheduleType(typ)
	custom.ScheduleType = typStr

	return ScheduleConfig{
		CustomScheduleConfig: &custom,
		Type:                 typ,
	}
}

func CreateScheduleConfigOnce(once OnceScheduleConfig) ScheduleConfig {
	typ := ScheduleConfigTypeOnce

	typStr := OnceScheduleConfigScheduleType(typ)
	once.ScheduleType = typStr

	return ScheduleConfig{
		OnceScheduleConfig: &once,
		Type:               typ,
	}
}

func (u *ScheduleConfig) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		ScheduleType string `json:"scheduleType"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.ScheduleType {
	case "hourly":
		hourlyScheduleConfig := new(HourlyScheduleConfig)
		if err := utils.UnmarshalJSON(data, &hourlyScheduleConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ScheduleType == hourly) type HourlyScheduleConfig within ScheduleConfig: %w", string(data), err)
		}

		u.HourlyScheduleConfig = hourlyScheduleConfig
		u.Type = ScheduleConfigTypeHourly
		return nil
	case "daily":
		dailyScheduleConfig := new(DailyScheduleConfig)
		if err := utils.UnmarshalJSON(data, &dailyScheduleConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ScheduleType == daily) type DailyScheduleConfig within ScheduleConfig: %w", string(data), err)
		}

		u.DailyScheduleConfig = dailyScheduleConfig
		u.Type = ScheduleConfigTypeDaily
		return nil
	case "weekly":
		weeklyScheduleConfig := new(WeeklyScheduleConfig)
		if err := utils.UnmarshalJSON(data, &weeklyScheduleConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ScheduleType == weekly) type WeeklyScheduleConfig within ScheduleConfig: %w", string(data), err)
		}

		u.WeeklyScheduleConfig = weeklyScheduleConfig
		u.Type = ScheduleConfigTypeWeekly
		return nil
	case "monthly":
		monthlyScheduleConfig := new(MonthlyScheduleConfig)
		if err := utils.UnmarshalJSON(data, &monthlyScheduleConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ScheduleType == monthly) type MonthlyScheduleConfig within ScheduleConfig: %w", string(data), err)
		}

		u.MonthlyScheduleConfig = monthlyScheduleConfig
		u.Type = ScheduleConfigTypeMonthly
		return nil
	case "custom":
		customScheduleConfig := new(CustomScheduleConfig)
		if err := utils.UnmarshalJSON(data, &customScheduleConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ScheduleType == custom) type CustomScheduleConfig within ScheduleConfig: %w", string(data), err)
		}

		u.CustomScheduleConfig = customScheduleConfig
		u.Type = ScheduleConfigTypeCustom
		return nil
	case "once":
		onceScheduleConfig := new(OnceScheduleConfig)
		if err := utils.UnmarshalJSON(data, &onceScheduleConfig, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (ScheduleType == once) type OnceScheduleConfig within ScheduleConfig: %w", string(data), err)
		}

		u.OnceScheduleConfig = onceScheduleConfig
		u.Type = ScheduleConfigTypeOnce
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ScheduleConfig", string(data))
}

func (u ScheduleConfig) MarshalJSON() ([]byte, error) {
	if u.HourlyScheduleConfig != nil {
		return utils.MarshalJSON(u.HourlyScheduleConfig, "", true)
	}

	if u.DailyScheduleConfig != nil {
		return utils.MarshalJSON(u.DailyScheduleConfig, "", true)
	}

	if u.WeeklyScheduleConfig != nil {
		return utils.MarshalJSON(u.WeeklyScheduleConfig, "", true)
	}

	if u.MonthlyScheduleConfig != nil {
		return utils.MarshalJSON(u.MonthlyScheduleConfig, "", true)
	}

	if u.CustomScheduleConfig != nil {
		return utils.MarshalJSON(u.CustomScheduleConfig, "", true)
	}

	if u.OnceScheduleConfig != nil {
		return utils.MarshalJSON(u.OnceScheduleConfig, "", true)
	}

	return nil, errors.New("could not marshal union type ScheduleConfig: all fields are null")
}
