// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SMTPConfig - SMTP email server configuration for sending system emails (invitations, notifications, password resets)
type SMTPConfig struct {
	// SMTP server hostname or IP address
	Host string `json:"host"`
	// SMTP server port. Common ports are 25 (unencrypted), 465 (SSL), 587 (TLS/STARTTLS)
	Port int64 `json:"port"`
	// SMTP authentication username. Usually an email address for services like Gmail, SendGrid, etc.
	Username *string `json:"username,omitempty"`
	// SMTP authentication password or app-specific password. For Gmail, use an App Password instead of your account password.
	Password *string `json:"password,omitempty"`
	// Default sender email address that appears in the "From" field of outgoing emails
	FromEmail string `json:"fromEmail"`
}

func (o *SMTPConfig) GetHost() string {
	if o == nil {
		return ""
	}
	return o.Host
}

func (o *SMTPConfig) GetPort() int64 {
	if o == nil {
		return 0
	}
	return o.Port
}

func (o *SMTPConfig) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}

func (o *SMTPConfig) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *SMTPConfig) GetFromEmail() string {
	if o == nil {
		return ""
	}
	return o.FromEmail
}
