// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/optionalnullable"
)

// UpdateAIModelProviderRequestConfiguration - Updated provider configuration
type UpdateAIModelProviderRequestConfiguration struct {
}

// UpdateAIModelProviderRequest - Request to update an existing AI model provider
type UpdateAIModelProviderRequest struct {
	// Provider name
	Provider string `json:"provider"`
	// Updated provider configuration
	Configuration UpdateAIModelProviderRequestConfiguration `json:"configuration"`
	IsMultimodal  *bool                                     `json:"isMultimodal,omitempty"`
	IsReasoning   *bool                                     `json:"isReasoning,omitempty"`
	IsDefault     *bool                                     `json:"isDefault,omitempty"`
	ContextLength optionalnullable.OptionalNullable[int64]  `json:"contextLength,omitempty"`
}

func (o *UpdateAIModelProviderRequest) GetProvider() string {
	if o == nil {
		return ""
	}
	return o.Provider
}

func (o *UpdateAIModelProviderRequest) GetConfiguration() UpdateAIModelProviderRequestConfiguration {
	if o == nil {
		return UpdateAIModelProviderRequestConfiguration{}
	}
	return o.Configuration
}

func (o *UpdateAIModelProviderRequest) GetIsMultimodal() *bool {
	if o == nil {
		return nil
	}
	return o.IsMultimodal
}

func (o *UpdateAIModelProviderRequest) GetIsReasoning() *bool {
	if o == nil {
		return nil
	}
	return o.IsReasoning
}

func (o *UpdateAIModelProviderRequest) GetIsDefault() *bool {
	if o == nil {
		return nil
	}
	return o.IsDefault
}

func (o *UpdateAIModelProviderRequest) GetContextLength() optionalnullable.OptionalNullable[int64] {
	if o == nil {
		return nil
	}
	return o.ContextLength
}
