// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateConnectorConfigRequest - Request to update connector configuration (partial updates supported)
type UpdateConnectorConfigRequest struct {
	// Authentication configuration for a connector instance
	Auth *ConnectorAuthConfig `json:"auth,omitempty"`
	// Synchronization configuration for a connector instance
	Sync *ConnectorSyncConfig `json:"sync,omitempty"`
	// Filter configuration to control what data is synced (sync filters and indexing filters)
	Filters *ConnectorFiltersConfig `json:"filters,omitempty"`
	// Base URL for self-hosted instances
	BaseURL *string `json:"baseUrl,omitempty"`
}

func (o *UpdateConnectorConfigRequest) GetAuth() *ConnectorAuthConfig {
	if o == nil {
		return nil
	}
	return o.Auth
}

func (o *UpdateConnectorConfigRequest) GetSync() *ConnectorSyncConfig {
	if o == nil {
		return nil
	}
	return o.Sync
}

func (o *UpdateConnectorConfigRequest) GetFilters() *ConnectorFiltersConfig {
	if o == nil {
		return nil
	}
	return o.Filters
}

func (o *UpdateConnectorConfigRequest) GetBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseURL
}
