// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
	"time"
)

// User account in an organization
type User struct {
	// Unique user identifier (MongoDB ObjectId)
	ID *string `json:"_id,omitempty"`
	// Unique slug for the user
	Slug *string `json:"slug,omitempty"`
	// Organization ID the user belongs to
	OrgID string `json:"orgId"`
	// Full name of the user
	FullName *string `json:"fullName,omitempty"`
	// First name
	FirstName *string `json:"firstName,omitempty"`
	// Last name
	LastName *string `json:"lastName,omitempty"`
	// Middle name
	MiddleName *string `json:"middleName,omitempty"`
	// Email address (unique, lowercase)
	Email string `json:"email"`
	// Mobile number (10-15 digits with optional +)
	Mobile *string `json:"mobile,omitempty"`
	// Whether user has logged in at least once
	HasLoggedIn *bool `default:"false" json:"hasLoggedIn"`
	// Job title/designation
	Designation *string  `json:"designation,omitempty"`
	Address     *Address `json:"address,omitempty"`
	// Whether user has consented to data collection
	DataCollectionConsent *bool `json:"dataCollectionConsent,omitempty"`
	// Soft delete flag
	IsDeleted *bool `default:"false" json:"isDeleted"`
	// ID of user who deleted this user
	DeletedBy *string `json:"deletedBy,omitempty"`
	// Document version (MongoDB)
	V *int64 `json:"__v,omitempty"`
	// Creation timestamp (ISO 8601)
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Last update timestamp (ISO 8601)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

func (u User) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *User) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, []string{"orgId", "email"}); err != nil {
		return err
	}
	return nil
}

func (o *User) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *User) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *User) GetOrgID() string {
	if o == nil {
		return ""
	}
	return o.OrgID
}

func (o *User) GetFullName() *string {
	if o == nil {
		return nil
	}
	return o.FullName
}

func (o *User) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *User) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *User) GetMiddleName() *string {
	if o == nil {
		return nil
	}
	return o.MiddleName
}

func (o *User) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *User) GetMobile() *string {
	if o == nil {
		return nil
	}
	return o.Mobile
}

func (o *User) GetHasLoggedIn() *bool {
	if o == nil {
		return nil
	}
	return o.HasLoggedIn
}

func (o *User) GetDesignation() *string {
	if o == nil {
		return nil
	}
	return o.Designation
}

func (o *User) GetAddress() *Address {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *User) GetDataCollectionConsent() *bool {
	if o == nil {
		return nil
	}
	return o.DataCollectionConsent
}

func (o *User) GetIsDeleted() *bool {
	if o == nil {
		return nil
	}
	return o.IsDeleted
}

func (o *User) GetDeletedBy() *string {
	if o == nil {
		return nil
	}
	return o.DeletedBy
}

func (o *User) GetV() *int64 {
	if o == nil {
		return nil
	}
	return o.V
}

func (o *User) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *User) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
