// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type UserBasicAccountType string

const (
	UserBasicAccountTypeIndividual UserBasicAccountType = "individual"
	UserBasicAccountTypeBusiness   UserBasicAccountType = "business"
)

func (e UserBasicAccountType) ToPointer() *UserBasicAccountType {
	return &e
}
func (e *UserBasicAccountType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "individual":
		fallthrough
	case "business":
		*e = UserBasicAccountType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserBasicAccountType: %v", v)
	}
}

// UserBasic - Basic user information
type UserBasic struct {
	// User ID
	ID       *string `json:"_id,omitempty"`
	Email    *string `json:"email,omitempty"`
	FullName *string `json:"fullName,omitempty"`
	// Organization ID
	OrgID       *string               `json:"orgId,omitempty"`
	AccountType *UserBasicAccountType `json:"accountType,omitempty"`
}

func (o *UserBasic) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UserBasic) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UserBasic) GetFullName() *string {
	if o == nil {
		return nil
	}
	return o.FullName
}

func (o *UserBasic) GetOrgID() *string {
	if o == nil {
		return nil
	}
	return o.OrgID
}

func (o *UserBasic) GetAccountType() *UserBasicAccountType {
	if o == nil {
		return nil
	}
	return o.AccountType
}
