/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * JSON Schema for tool inputs
 */
export type InputSchema = {};

/**
 * A tool that agents can use to perform actions
 */
export type AgentTool = {
  /**
   * Unique tool identifier
   */
  key?: string | undefined;
  /**
   * Display name
   */
  name?: string | undefined;
  /**
   * What the tool does
   */
  description?: string | undefined;
  /**
   * JSON Schema for tool inputs
   */
  inputSchema?: InputSchema | undefined;
  /**
   * Whether tool is currently available
   */
  isEnabled?: boolean | undefined;
};

/** @internal */
export const InputSchema$inboundSchema: z.ZodMiniType<InputSchema, unknown> = z
  .object({});

export function inputSchemaFromJSON(
  jsonString: string,
): SafeParseResult<InputSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InputSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InputSchema' from JSON`,
  );
}

/** @internal */
export const AgentTool$inboundSchema: z.ZodMiniType<AgentTool, unknown> = z
  .object({
    key: types.optional(types.string()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
    inputSchema: types.optional(z.lazy(() => InputSchema$inboundSchema)),
    isEnabled: types.optional(types.boolean()),
  });

export function agentToolFromJSON(
  jsonString: string,
): SafeParseResult<AgentTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentTool' from JSON`,
  );
}
