/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Azure Active Directory authentication configuration
 */
export type AzureAdAuthConfig = {
  /**
   * Azure AD application client ID
   */
  clientId?: string | undefined;
  /**
   * Azure AD tenant ID (use 'common' for multi-tenant)
   */
  tenantId?: string | undefined;
};

/** @internal */
export const AzureAdAuthConfig$inboundSchema: z.ZodMiniType<
  AzureAdAuthConfig,
  unknown
> = z.object({
  clientId: types.optional(types.string()),
  tenantId: z._default(types.string(), "common"),
});
/** @internal */
export type AzureAdAuthConfig$Outbound = {
  clientId?: string | undefined;
  tenantId: string;
};

/** @internal */
export const AzureAdAuthConfig$outboundSchema: z.ZodMiniType<
  AzureAdAuthConfig$Outbound,
  AzureAdAuthConfig
> = z.object({
  clientId: z.optional(z.string()),
  tenantId: z._default(z.string(), "common"),
});

export function azureAdAuthConfigToJSON(
  azureAdAuthConfig: AzureAdAuthConfig,
): string {
  return JSON.stringify(
    AzureAdAuthConfig$outboundSchema.parse(azureAdAuthConfig),
  );
}
export function azureAdAuthConfigFromJSON(
  jsonString: string,
): SafeParseResult<AzureAdAuthConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureAdAuthConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureAdAuthConfig' from JSON`,
  );
}
