/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Sync strategy: MANUAL (user-triggered), SCHEDULED (interval/cron), WEBHOOK (event-driven), REALTIME (WebSocket)
 */
export const SelectedStrategy = {
  Manual: "MANUAL",
  Scheduled: "SCHEDULED",
  Webhook: "WEBHOOK",
  Realtime: "REALTIME",
} as const;
/**
 * Sync strategy: MANUAL (user-triggered), SCHEDULED (interval/cron), WEBHOOK (event-driven), REALTIME (WebSocket)
 */
export type SelectedStrategy = ClosedEnum<typeof SelectedStrategy>;

/**
 * Configuration for scheduled sync strategy
 */
export type ScheduledConfig = {
  /**
   * Sync interval in minutes
   */
  intervalMinutes?: number | undefined;
  /**
   * Cron expression for advanced scheduling
   */
  cronExpression?: string | undefined;
  /**
   * Timezone for scheduled sync
   */
  timezone?: string | undefined;
};

/**
 * Configuration for webhook-based sync
 */
export type WebhookConfig = {
  /**
   * URL to receive webhook events (auto-generated)
   */
  webhookUrl?: string | undefined;
  /**
   * Subscribed event types
   */
  events?: Array<string> | undefined;
};

/**
 * Synchronization configuration for a connector instance
 */
export type ConnectorSyncConfig = {
  /**
   * Sync strategy: MANUAL (user-triggered), SCHEDULED (interval/cron), WEBHOOK (event-driven), REALTIME (WebSocket)
   */
  selectedStrategy?: SelectedStrategy | undefined;
  /**
   * Configuration for scheduled sync strategy
   */
  scheduledConfig?: ScheduledConfig | undefined;
  /**
   * Configuration for webhook-based sync
   */
  webhookConfig?: WebhookConfig | undefined;
  /**
   * Sync setting values specific to the connector
   */
  values?: { [k: string]: any } | undefined;
  /**
   * Custom sync values
   */
  customValues?: { [k: string]: any } | undefined;
};

/** @internal */
export const SelectedStrategy$outboundSchema: z.ZodMiniEnum<
  typeof SelectedStrategy
> = z.enum(SelectedStrategy);

/** @internal */
export type ScheduledConfig$Outbound = {
  intervalMinutes: number;
  cronExpression?: string | undefined;
  timezone: string;
};

/** @internal */
export const ScheduledConfig$outboundSchema: z.ZodMiniType<
  ScheduledConfig$Outbound,
  ScheduledConfig
> = z.object({
  intervalMinutes: z._default(z.int(), 60),
  cronExpression: z.optional(z.string()),
  timezone: z._default(z.string(), "UTC"),
});

export function scheduledConfigToJSON(
  scheduledConfig: ScheduledConfig,
): string {
  return JSON.stringify(ScheduledConfig$outboundSchema.parse(scheduledConfig));
}

/** @internal */
export type WebhookConfig$Outbound = {
  webhookUrl?: string | undefined;
  events?: Array<string> | undefined;
};

/** @internal */
export const WebhookConfig$outboundSchema: z.ZodMiniType<
  WebhookConfig$Outbound,
  WebhookConfig
> = z.object({
  webhookUrl: z.optional(z.string()),
  events: z.optional(z.array(z.string())),
});

export function webhookConfigToJSON(webhookConfig: WebhookConfig): string {
  return JSON.stringify(WebhookConfig$outboundSchema.parse(webhookConfig));
}

/** @internal */
export type ConnectorSyncConfig$Outbound = {
  selectedStrategy: string;
  scheduledConfig?: ScheduledConfig$Outbound | undefined;
  webhookConfig?: WebhookConfig$Outbound | undefined;
  values?: { [k: string]: any } | undefined;
  customValues?: { [k: string]: any } | undefined;
};

/** @internal */
export const ConnectorSyncConfig$outboundSchema: z.ZodMiniType<
  ConnectorSyncConfig$Outbound,
  ConnectorSyncConfig
> = z.object({
  selectedStrategy: z._default(SelectedStrategy$outboundSchema, "MANUAL"),
  scheduledConfig: z.optional(z.lazy(() => ScheduledConfig$outboundSchema)),
  webhookConfig: z.optional(z.lazy(() => WebhookConfig$outboundSchema)),
  values: z.optional(z.record(z.string(), z.any())),
  customValues: z.optional(z.record(z.string(), z.any())),
});

export function connectorSyncConfigToJSON(
  connectorSyncConfig: ConnectorSyncConfig,
): string {
  return JSON.stringify(
    ConnectorSyncConfig$outboundSchema.parse(connectorSyncConfig),
  );
}
