/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Pagination information for connector lists
 */
export type ConnectorPagination = {
  /**
   * Current page number
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Total number of items
   */
  total?: number | undefined;
  /**
   * Whether more pages exist
   */
  hasMore?: boolean | undefined;
};

/** @internal */
export const ConnectorPagination$inboundSchema: z.ZodMiniType<
  ConnectorPagination,
  unknown
> = z.object({
  page: types.optional(types.number()),
  limit: types.optional(types.number()),
  total: types.optional(types.number()),
  hasMore: types.optional(types.boolean()),
});

export function connectorPaginationFromJSON(
  jsonString: string,
): SafeParseResult<ConnectorPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConnectorPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConnectorPagination' from JSON`,
  );
}
