/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
 */
export const ConnectorToggleRequestType = {
  Sync: "sync",
  Agent: "agent",
} as const;
/**
 * Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
 */
export type ConnectorToggleRequestType = ClosedEnum<
  typeof ConnectorToggleRequestType
>;

/**
 * Request to toggle connector active status
 */
export type ConnectorToggleRequest = {
  /**
   * Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
   */
  type: ConnectorToggleRequestType;
};

/** @internal */
export const ConnectorToggleRequestType$outboundSchema: z.ZodMiniEnum<
  typeof ConnectorToggleRequestType
> = z.enum(ConnectorToggleRequestType);

/** @internal */
export type ConnectorToggleRequest$Outbound = {
  type: string;
};

/** @internal */
export const ConnectorToggleRequest$outboundSchema: z.ZodMiniType<
  ConnectorToggleRequest$Outbound,
  ConnectorToggleRequest
> = z.object({
  type: ConnectorToggleRequestType$outboundSchema,
});

export function connectorToggleRequestToJSON(
  connectorToggleRequest: ConnectorToggleRequest,
): string {
  return JSON.stringify(
    ConnectorToggleRequest$outboundSchema.parse(connectorToggleRequest),
  );
}
