/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Request to send password reset email
 */
export type ForgotPasswordRequest = {
  /**
   * Email address to send reset link to
   */
  email: string;
  /**
   * Cloudflare Turnstile CAPTCHA token (optional)
   */
  cfTurnstileResponse?: string | undefined;
};

/** @internal */
export type ForgotPasswordRequest$Outbound = {
  email: string;
  "cf-turnstile-response"?: string | undefined;
};

/** @internal */
export const ForgotPasswordRequest$outboundSchema: z.ZodMiniType<
  ForgotPasswordRequest$Outbound,
  ForgotPasswordRequest
> = z.pipe(
  z.object({
    email: z.string(),
    cfTurnstileResponse: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cfTurnstileResponse: "cf-turnstile-response",
    });
  }),
);

export function forgotPasswordRequestToJSON(
  forgotPasswordRequest: ForgotPasswordRequest,
): string {
  return JSON.stringify(
    ForgotPasswordRequest$outboundSchema.parse(forgotPasswordRequest),
  );
}
