/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request to initialize authentication session
 */
export type InitAuthRequest = {
  /**
   * User email address (RFC 5321 compliant)
   */
  email: string;
};

/** @internal */
export type InitAuthRequest$Outbound = {
  email: string;
};

/** @internal */
export const InitAuthRequest$outboundSchema: z.ZodMiniType<
  InitAuthRequest$Outbound,
  InitAuthRequest
> = z.object({
  email: z.string(),
});

export function initAuthRequestToJSON(
  initAuthRequest: InitAuthRequest,
): string {
  return JSON.stringify(InitAuthRequest$outboundSchema.parse(initAuthRequest));
}
