/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Credentials for OAuth authentication (Microsoft, Azure AD, generic OAuth)
 */
export type OAuthCredentials = {
  /**
   * OAuth access token
   */
  accessToken: string;
  /**
   * OAuth ID token (JWT)
   */
  idToken?: string | undefined;
};

/** @internal */
export type OAuthCredentials$Outbound = {
  accessToken: string;
  idToken?: string | undefined;
};

/** @internal */
export const OAuthCredentials$outboundSchema: z.ZodMiniType<
  OAuthCredentials$Outbound,
  OAuthCredentials
> = z.object({
  accessToken: z.string(),
  idToken: z.optional(z.string()),
});

export function oAuthCredentialsToJSON(
  oAuthCredentials: OAuthCredentials,
): string {
  return JSON.stringify(
    OAuthCredentials$outboundSchema.parse(oAuthCredentials),
  );
}
