/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OAuthAppResponse,
  OAuthAppResponse$inboundSchema,
} from "./o-auth-app-response.js";

export type Pagination = {
  /**
   * Current page number
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Total number of items
   */
  total?: number | undefined;
  /**
   * Total number of pages
   */
  totalPages?: number | undefined;
};

/**
 * Paginated list of OAuth apps
 */
export type OAuthAppListResponse = {
  /**
   * List of OAuth apps
   */
  data?: Array<OAuthAppResponse> | undefined;
  pagination?: Pagination | undefined;
};

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .object({
    page: types.optional(types.number()),
    limit: types.optional(types.number()),
    total: types.optional(types.number()),
    totalPages: types.optional(types.number()),
  });

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}

/** @internal */
export const OAuthAppListResponse$inboundSchema: z.ZodMiniType<
  OAuthAppListResponse,
  unknown
> = z.object({
  data: types.optional(z.array(OAuthAppResponse$inboundSchema)),
  pagination: types.optional(z.lazy(() => Pagination$inboundSchema)),
});

export function oAuthAppListResponseFromJSON(
  jsonString: string,
): SafeParseResult<OAuthAppListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OAuthAppListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OAuthAppListResponse' from JSON`,
  );
}
