/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * OneDrive/Microsoft 365 connector configuration
 */
export type OneDriveConfig = {
  /**
   * Microsoft application client ID
   */
  clientId: string;
  /**
   * Microsoft application client secret
   */
  clientSecret: string;
  /**
   * Microsoft/Azure tenant ID
   */
  tenantId: string;
  /**
   * Whether admin consent has been granted
   */
  hasAdminConsent?: boolean | undefined;
};

/** @internal */
export const OneDriveConfig$inboundSchema: z.ZodMiniType<
  OneDriveConfig,
  unknown
> = z.object({
  clientId: types.string(),
  clientSecret: types.string(),
  tenantId: types.string(),
  hasAdminConsent: z._default(types.boolean(), false),
});
/** @internal */
export type OneDriveConfig$Outbound = {
  clientId: string;
  clientSecret: string;
  tenantId: string;
  hasAdminConsent: boolean;
};

/** @internal */
export const OneDriveConfig$outboundSchema: z.ZodMiniType<
  OneDriveConfig$Outbound,
  OneDriveConfig
> = z.object({
  clientId: z.string(),
  clientSecret: z.string(),
  tenantId: z.string(),
  hasAdminConsent: z._default(z.boolean(), false),
});

export function oneDriveConfigToJSON(oneDriveConfig: OneDriveConfig): string {
  return JSON.stringify(OneDriveConfig$outboundSchema.parse(oneDriveConfig));
}
export function oneDriveConfigFromJSON(
  jsonString: string,
): SafeParseResult<OneDriveConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OneDriveConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OneDriveConfig' from JSON`,
  );
}
