/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Credentials for OTP authentication
 */
export type OtpCredentials = {
  /**
   * 6-digit one-time password
   */
  otp: string;
};

/** @internal */
export type OtpCredentials$Outbound = {
  otp: string;
};

/** @internal */
export const OtpCredentials$outboundSchema: z.ZodMiniType<
  OtpCredentials$Outbound,
  OtpCredentials
> = z.object({
  otp: z.string(),
});

export function otpCredentialsToJSON(otpCredentials: OtpCredentials): string {
  return JSON.stringify(OtpCredentials$outboundSchema.parse(otpCredentials));
}
