/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type PaginationInfo = {
  /**
   * Current page number
   */
  page?: number | undefined;
  /**
   * Items per page
   */
  limit?: number | undefined;
  /**
   * Total number of items
   */
  totalCount?: number | undefined;
  /**
   * Total number of pages
   */
  totalPages?: number | undefined;
};

/** @internal */
export const PaginationInfo$inboundSchema: z.ZodMiniType<
  PaginationInfo,
  unknown
> = z.object({
  page: types.optional(types.number()),
  limit: types.optional(types.number()),
  totalCount: types.optional(types.number()),
  totalPages: types.optional(types.number()),
});

export function paginationInfoFromJSON(
  jsonString: string,
): SafeParseResult<PaginationInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaginationInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginationInfo' from JSON`,
  );
}
