/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

/**
 * Platform-wide configuration settings for file uploads and feature toggles
 */
export type PlatformSettings = {
  /**
   * Maximum file upload size in bytes. Default is 30MB (31457280 bytes). Maximum allowed is 1GB.
   */
  fileUploadMaxSizeBytes?: number | undefined;
  /**
   * Key-value map of feature flags to enable/disable platform features.
   *
   * @remarks
   * Available flags:
   * - ENABLE_BETA_CONNECTORS: Allow usage of beta connector integrations that may be unstable
   */
  featureFlags?: { [k: string]: boolean } | undefined;
  /**
   * Timestamp of last settings update (read-only, set automatically). May not be present in the response.
   */
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const PlatformSettings$inboundSchema: z.ZodMiniType<
  PlatformSettings,
  unknown
> = z.object({
  fileUploadMaxSizeBytes: types.optional(types.number()),
  featureFlags: types.optional(z.record(z.string(), types.boolean())),
  updatedAt: z.optional(z.nullable(types.date())),
});

export function platformSettingsFromJSON(
  jsonString: string,
): SafeParseResult<PlatformSettings, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PlatformSettings$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PlatformSettings' from JSON`,
  );
}
