/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * OAuth 2.0 authentication with fine-grained scopes.
 *
 * @remarks
 * Supports authorization_code (with PKCE) and client_credentials flows.
 * OAuth tokens are Bearer JWTs — use the same Authorization header as regular tokens.
 */
export type SchemeOauth2 = {
  clientID: string;
  clientSecret: string;
  tokenURL?: string | undefined;
};

/** @internal */
export type SchemeOauth2$Outbound = {
  clientID: string;
  clientSecret: string;
  tokenURL: string;
};

/** @internal */
export const SchemeOauth2$outboundSchema: z.ZodMiniType<
  SchemeOauth2$Outbound,
  SchemeOauth2
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  tokenURL: z._default(z.string(), "/api/v1/oauth/token"),
});

export function schemeOauth2ToJSON(schemeOauth2: SchemeOauth2): string {
  return JSON.stringify(SchemeOauth2$outboundSchema.parse(schemeOauth2));
}
