/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  ConnectorAuthConfig,
  ConnectorAuthConfig$Outbound,
  ConnectorAuthConfig$outboundSchema,
} from "./connector-auth-config.js";

/**
 * Request to update authentication config (clears OAuth tokens, requires re-auth)
 */
export type UpdateConnectorAuthRequest = {
  /**
   * Authentication configuration for a connector instance
   */
  auth: ConnectorAuthConfig;
  /**
   * Base URL (if changed with auth update)
   */
  baseUrl?: string | undefined;
};

/** @internal */
export type UpdateConnectorAuthRequest$Outbound = {
  auth: ConnectorAuthConfig$Outbound;
  baseUrl?: string | undefined;
};

/** @internal */
export const UpdateConnectorAuthRequest$outboundSchema: z.ZodMiniType<
  UpdateConnectorAuthRequest$Outbound,
  UpdateConnectorAuthRequest
> = z.object({
  auth: ConnectorAuthConfig$outboundSchema,
  baseUrl: z.optional(z.string()),
});

export function updateConnectorAuthRequestToJSON(
  updateConnectorAuthRequest: UpdateConnectorAuthRequest,
): string {
  return JSON.stringify(
    UpdateConnectorAuthRequest$outboundSchema.parse(updateConnectorAuthRequest),
  );
}
