/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Updated provider configuration
 */
export type UpdateAIModelProviderRequestConfiguration = {};

/**
 * Request to update an existing AI model provider
 */
export type UpdateAIModelProviderRequest = {
  /**
   * Provider name
   */
  provider: string;
  /**
   * Updated provider configuration
   */
  configuration: UpdateAIModelProviderRequestConfiguration;
  isMultimodal?: boolean | undefined;
  isReasoning?: boolean | undefined;
  isDefault?: boolean | undefined;
  contextLength?: number | null | undefined;
};

/** @internal */
export type UpdateAIModelProviderRequestConfiguration$Outbound = {};

/** @internal */
export const UpdateAIModelProviderRequestConfiguration$outboundSchema:
  z.ZodMiniType<
    UpdateAIModelProviderRequestConfiguration$Outbound,
    UpdateAIModelProviderRequestConfiguration
  > = z.object({});

export function updateAIModelProviderRequestConfigurationToJSON(
  updateAIModelProviderRequestConfiguration:
    UpdateAIModelProviderRequestConfiguration,
): string {
  return JSON.stringify(
    UpdateAIModelProviderRequestConfiguration$outboundSchema.parse(
      updateAIModelProviderRequestConfiguration,
    ),
  );
}

/** @internal */
export type UpdateAIModelProviderRequest$Outbound = {
  provider: string;
  configuration: UpdateAIModelProviderRequestConfiguration$Outbound;
  isMultimodal?: boolean | undefined;
  isReasoning?: boolean | undefined;
  isDefault?: boolean | undefined;
  contextLength?: number | null | undefined;
};

/** @internal */
export const UpdateAIModelProviderRequest$outboundSchema: z.ZodMiniType<
  UpdateAIModelProviderRequest$Outbound,
  UpdateAIModelProviderRequest
> = z.object({
  provider: z.string(),
  configuration: z.lazy(() =>
    UpdateAIModelProviderRequestConfiguration$outboundSchema
  ),
  isMultimodal: z.optional(z.boolean()),
  isReasoning: z.optional(z.boolean()),
  isDefault: z.optional(z.boolean()),
  contextLength: z.optional(z.nullable(z.int())),
});

export function updateAIModelProviderRequestToJSON(
  updateAIModelProviderRequest: UpdateAIModelProviderRequest,
): string {
  return JSON.stringify(
    UpdateAIModelProviderRequest$outboundSchema.parse(
      updateAIModelProviderRequest,
    ),
  );
}
