/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

/**
 * Request to update connector instance name
 */
export type UpdateConnectorNameRequest = {
  /**
   * New display name for the connector instance
   */
  instanceName: string;
};

/** @internal */
export type UpdateConnectorNameRequest$Outbound = {
  instanceName: string;
};

/** @internal */
export const UpdateConnectorNameRequest$outboundSchema: z.ZodMiniType<
  UpdateConnectorNameRequest$Outbound,
  UpdateConnectorNameRequest
> = z.object({
  instanceName: z.string(),
});

export function updateConnectorNameRequestToJSON(
  updateConnectorNameRequest: UpdateConnectorNameRequest,
): string {
  return JSON.stringify(
    UpdateConnectorNameRequest$outboundSchema.parse(updateConnectorNameRequest),
  );
}
