/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const UserBasicAccountType = {
  Individual: "individual",
  Business: "business",
} as const;
export type UserBasicAccountType = OpenEnum<typeof UserBasicAccountType>;

/**
 * Basic user information
 */
export type UserBasic = {
  /**
   * User ID
   */
  id?: string | undefined;
  email?: string | undefined;
  fullName?: string | undefined;
  /**
   * Organization ID
   */
  orgId?: string | undefined;
  accountType?: UserBasicAccountType | undefined;
};

/** @internal */
export const UserBasicAccountType$inboundSchema: z.ZodMiniType<
  UserBasicAccountType,
  unknown
> = openEnums.inboundSchema(UserBasicAccountType);

/** @internal */
export const UserBasic$inboundSchema: z.ZodMiniType<UserBasic, unknown> = z
  .pipe(
    z.object({
      _id: types.optional(types.string()),
      email: types.optional(types.string()),
      fullName: types.optional(types.string()),
      orgId: types.optional(types.string()),
      accountType: types.optional(UserBasicAccountType$inboundSchema),
    }),
    z.transform((v) => {
      return remap$(v, {
        "_id": "id",
      });
    }),
  );

export function userBasicFromJSON(
  jsonString: string,
): SafeParseResult<UserBasic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserBasic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserBasic' from JSON`,
  );
}
